### ISSUE TITLE
Basic question re setting up Json

### ISSUE THREAD

**Issue by JCCcccspud** [jvmahon/Homebridge-HomeSeer4#101]
My question deals with setting up the Json file.  I enabled ASCII commands in HS.  Then I went here
https://github.com/jvmahon/homebridge-homeseer4/tree/master/config

What do I do next?  Can I copy and paste the config.simple.json example and paste it somewhere?  Where do I paste it?

I think I understand about the device numbers,

Thanks

**Comment by jvmahon** [comment]
Sorry, haven't had time to respond - a bit too busy with my "real" work.
Yes, copy config.simple.json, but rename it "config.json"

As to where to put the file, if you look here, it tells you want to do for Linux on Pi it typically goes in /home/pi/.homebridge. There is some more info here on setting permissions:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Linux-Installation-and-Errors

For windows, there is usually a ".homebridge' folder created for the user in the user's top-level directory. So, for example, if your windows user directory is   /users/JCCcccspud, you'd put the config.json in   /users/JCCcccspud/.homebridge

**Comment by jvmahon** [comment]
There's more info. available at the homebridge wiki, here: https://github.com/homebridge/homebridge/wiki

**Comment by jvmahon** [comment]
I haven't heard back further, so I assume you resolved your issues. If not, please re-open this comment and provide an update. Thanks.

**Comment by JCCcccspud** [comment]
Just been busy with other things and haven’t had time to focus on it.
