### ISSUE TITLE
Wonderful!  Few kinks

### ISSUE THREAD

**Issue by CodingKideon** [jvmahon/Homebridge-HomeSeer4#102]
This is amazing!  I've been meaning to play around with Homebridge for a while and after upgrading to HS4 am putting some quality time into this and some other initiatives.  It works so well on the simple configuration...almost flawlessly.  The three items that are not working automagically are:

Z-Wave Leak Sensor (reporting leak when there isn't one)
Z-Wave Smoke Detector (reporting smoke when there isn't any)
MyQ Garage Door opener (native H4 bundled plugin not the 3rd party) reporting door as open when it's closed

Looking into all three items it's just a matter of different values being set in Homeseer.  I'll set them up manually later but wanted to make sure you were aware.

Looking forward to continuing the integration - next up will be the presence detection...

**Comment by jvmahon** [comment]
I'll have a look - all those things work for me on HS3, but maybe there was a change in HS4.

Can you post the "Status Graphics" pages for your Leak Sensor, Smoke Sensor, and Door Opener.  I just need the top half with the numeric values (not the section of icons). Thanks.

**Comment by CodingKideon** [comment]
<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/22333343/89830818-d660d100-db2a-11ea-9736-afdd3c16e8c3.png">
<img width="1194" alt="PNG image 2" src="https://user-images.githubusercontent.com/22333343/89830832-dbbe1b80-db2a-11ea-9045-c293697619ec.png">
<img width="1194" alt="PNG image 3" src="https://user-images.githubusercontent.com/22333343/89830841-dfea3900-db2a-11ea-9873-1e6b3392535c.png">
<img width="1194" alt="PNG image 4" src="https://user-images.githubusercontent.com/22333343/89830847-e2e52980-db2a-11ea-847b-43aa7d6a937c.png">

**Comment by jvmahon** [comment]
As for the Garage Door issue, that seems to be a MyQ plugin bug. I've just reported it here: https://forums.homeseer.com/forum/hs4-products/hs4-plugins/security-plug-ins-aa/myq-homeseer/1411163-control-use-error#post1411163

You may be able to fix it by manually changing the "Control Use" settings as I indicated in my post. Else, perhaps they'll update the MyQ plugin soon.

**Comment by jvmahon** [comment]
Also, the "Control Use" for your detector devices make no sense. They have values like "2.255" which shouldn't be possible as that is not a "single" value nor is it a value range.

I think that what you are seeing is that HS4 still has a range of bugs that need to be fixed before its really ready.

**Comment by mwolter805** [comment]
@CodingKideon I believe this is similar to the issue reported [here](https://github.com/jvmahon/Homebridge-HomeSeer4/issues/109). Please see that issue for more info.

**Comment by jvmahon** [comment]
Thanks @mwolter 
Update 1.0.9 has been published which should address the issue for the alarms / sensors.

The garage door issue remains a problem with HomeSeer 4.

**Comment by CodingKideon** [comment]
Still seeing leak and smoke reported on the sensors.  Using the homebridge MyQ plugin rather than HomeSeer and that’s working

**Comment by mwolter805** [comment]
@CodingKideon please post your config.json removing all sensitive info.

**Comment by CodingKideon** [comment]
"SmokeSensors": [
                414
 "LeakSensors": [
                321
            ],

Just using simple config currently should I set it up manually?

**Comment by mwolter805** [comment]
@jvmahon will need to respond to be sure but I believe you need to do the more detailed setup so it knows to certain status values are offValues.

**Comment by teladog01** [comment]
> Just using simple config currently should I set it up manually?

I think you'll need to enter this as a "complex device" in the config.json. You need to add to the "offValues" all the values that are not an "alarm" state. HomeKit will show the sensor in the Alarm state for any value that is not listed in the "offValues".

See [here](https://github.com/jvmahon/Homebridge-HomeSeer4/issues/109#issue-692008968) for an example.

**Comment by jvmahon** [comment]
By default, the SmokeSensor and LeakSensor "offValues" are [0, 254] so if you need other values, you have to do them in a complex setup.

My  recollection is that I choose these values because they were the "expected" values of no alarm, and "unknown" from the Z-Wave standards. I don't know where these x.255 values came from (at least in the Z-Wave standards, from what I recall, all the report values were integers). If I had some "official" guidance about the values being used in HomeSeer,  I could code in better defaults, but the information is lacking.

**Comment by jvmahon** [comment]
I'm not sure if these problems still exist with the updated versions of HS4. If so, please re-open as a new issue and describe the continuing problem.

I've mostly stopped developing this plugin, but I'll try to help.
