### ISSUE TITLE
Integration with Homebridge Config UI X

### ISSUE THREAD

**Issue by mwolter805** [jvmahon/Homebridge-HomeSeer4#103]
Hi,
First, thank you for making it possible for your plugin to work with temperatures over 200c. It works perfectly!

Would like to see if you can publish config.schema.json with your plugin so Homebridge Config UI X can generate user-interface allowing users to set up the plugin without having to manually manipulate the config.json. The developer instructions for formating the config.schema.json file are [here](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers%3A-Plugin-Settings-GUI). 

This would make installing and setting up the plugin simple for average users and reduce the number of questions and documentation complexity on your side. I think people would greatly enjoy this!

Thanks again!

**Comment by jvmahon** [comment]
You're welcome on the plugin.

As for the schema addition, I have to admit, I don't really understand how to set that up (though I haven't given it much through either). If someone else sees this and has a suggestion -- perhaps as a Pull Request -- , that would be welcome. Else, I might try it using one of my other (simpler) plugins as a starting point and then come back to this one in the future. It might be a while though.

**Comment by mwolter805** [comment]
No rush, whenever you have time would be great. It's definitely not a high priority.

**Comment by mwolter805** [comment]
Worked on this the past few days and have a basic interface for adding communication parameters, as well as the simple and complex device schema. Functionality is there and it appears to work well. The next step is to polish the UI layout. 
![Screen Shot 2020-08-22 at 8 30 04 AM](https://user-images.githubusercontent.com/24851651/90959728-b0ec9500-e451-11ea-8442-4f29266e009f.jpg)

**Comment by mwolter805** [comment]
Created a pull request for the config.schema.json file. Please take a look and let me know if anything needs to be changed.

**Comment by jvmahon** [comment]
@mwolter805 - Can you take a look at this post: https://github.com/jvmahon/Homebridge-HomeSeer4/issues/109

I think the config-ui-x implementation is causing problems for some people. Do you know what's going on and how to fix it?  I don't know enough about the config-ui-x to fix.

**Comment by jvmahon** [comment]
Thanks @mwolter 
Update 1.0.9 has been published.
Closing this for now - will reopen if anything else comes up.
