### ISSUE TITLE
ETIMEDOUT while connecting after update to 1.0.6.

### ISSUE THREAD

**Issue by wavi-web** [jvmahon/Homebridge-HomeSeer4#107]
Using the Homebridge/Homeseer4 plugin version 1.06 on HOOBS on a Rpi4, version 3.6.2.

Just installed version 1.0.6, after configuration the service won't start. See config.json and logging:
Edit 19:22: No problems when connecting to HS3 (old installation). 

config.json:
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYxxxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "NL",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-xxx",
        "username": "44:A8:BF:8F:xx:xx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "HomeSeer",
            "plugin_map": {
                "plugin_name": "homebridge-homeseer4"
            },
            "name": "HomeSeer",
            "host": "http://homeseer.local",
            "ASCIIport": 11000,
            "login": "xxxxx",
            "password": "xxxxxx"
        }
    ]
}
Log:
26-8-2020 19:07:08 (node:25535) UnhandledPromiseRejectionWarning: FetchError: request to http://hoobs:homebridge@homeseer.local/JSON?request=getstatus failed, reason: connect ETIMEDOUT 192.168.1.10:8026-8-2020 19:07:08 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1455:11)26-8-2020 19:07:08 at ClientRequest.emit (events.js:310:20)26-8-2020 19:07:08 at Socket.socketErrorListener (_http_client.js:426:9)26-8-2020 19:07:08 at Socket.emit (events.js:310:20)26-8-2020 19:07:08 at emitErrorNT (internal/streams/destroy.js:92:8)26-8-2020 19:07:08 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)26-8-2020 19:07:08 at processTicksAndRejections (internal/process/task_queues.js:84:21)26-8-2020 19:07:08 (node:25535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)26-8-2020 19:07:08 (node:25535) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Others have said there was a homebridge error (rather than the plugin). Try updating nodejs, homebridge, and the plugin and try again. If I don't hear back by end of week, I'll close this issue.
