### ISSUE TITLE
Fan's added as binary instead of multilevel devices

### ISSUE THREAD

**Issue by Jmaddox71** [jvmahon/Homebridge-HomeSeer4#108]
I copied the fans section from my working config...

"Fans": [
                212,
                406,
                428,
                241,
                415
            ],

These all get added as binary devices

When I first noticed this behavior I tried adding using this format
I also tried using the "levels":99, parameter but it threw an error to the effect it was depreciated/no longer supported.
{
	"type": "Fan",
	"name":null,
	"ref": 0,
	"uuid_base": 0,
	"batteryRef": 0,
	"batteryThreshold": 25,
	"onValue": 255,
	"offValue": 0
},

I did not try to define the fans as dimming lights, so that may still be a work around.  Although years ago when homebridge was first released I had an issue with adding fans and non contact relays as dimming lights/lights and having unexpected behaviors when I tried to use commands like 'turn all the lights on/off'  Took me a few of those to figure out why I'd have ceiling fans at full power and my gate standing wide open

here is a copy of my status/graphics page (I think this is what you wanted to see, if not please let me know)

![status page](https://user-images.githubusercontent.com/70618227/91927731-e1c59900-ec9f-11ea-87f7-5fa922ce23b5.jpg)

**Comment by jvmahon** [comment]
On the "Status Graphics" page -- to clarify - what I need is a copy of the HomeSeer "Status Graphics" page for the Fan device (e.g., in the above case, it would be the HomeSeer device with the refernce # 428) and let me know what type of control device you are using (e.g., is it the HomeSeer HS-FC200+ Fan Controller?).

**Comment by jvmahon** [comment]
Also, try adding an Fan (say #428) using the following form:

`````
{    "type":"MultilevelFan",
     "ref":428,
     "onValue": 255,
     "offValue": 0
}
`````
Let me know if this works.

Normally, when a Fan is added, there is a check performed and the code tries to determine if the fan is a binary fan or a multi-level (variable speed) fan, and there is a internal conversion from "type":"fan" to either "type":"BinaryFan", or to "type":"MultilevelFan". If yo specify it explicitly, this should override the type checking code. 

I still want to try and fix the type-checking code, but let's see if this is another solution in case I can't.

**Comment by Jmaddox71** [comment]
adding using MultilevelFan worked!
After I realized you meant the HS status/graphics page I bet that's why the Fan config option didn't work, I remove 'on last level' and the slider bar and just have off, low, med and high buttons on all my fans.

[status graphis page.pdf](https://github.com/jvmahon/Homebridge-HomeSeer4/files/5162933/status.graphis.page.pdf)

**Comment by jvmahon** [comment]
Oh, I see you are also using the HS4 Alpha software - yes, I know, they are calling it a release, but ...

I think some additional edits are needed to your Status Graphics page, but before I suggest that, let me know:

- On the "MultilevelFan" device, if you slide the speed slider to an intermediate position, say from the "low" range to about 90%, what happens? Does it make the change to 99 or do you have to be extremely "delicate" and get the slider "just right"?

**Comment by Jmaddox71** [comment]
In homekit the slider stops when I do and doesn't 'snap' to any ranges.  ie if I pull it from the bottom to 90% it stays at 90%.  Asking siri to set the fan to low, medium or high works as expected.

**Comment by jvmahon** [comment]
So if you're in "low" and slide to 90%, does the fan go to "high" or "medium" or does it stay at "low" 

I'm asking because the Status Graphics page only shows three values - 30, 60, 99.  I wanted to make sure you don't have to set the slider to exactly 30, 60 or 99 in the iOS app to trigger a change at HomeSeer -  that would be pretty annoying. If that does happen, I think the fix is to edit the Status Graphics page to also include 1-29, 31-59, 61-98 as range values.

**Comment by Jmaddox71** [comment]
I had a fan that I didn't change the status graphics page; moving the slider in Homekit changes from low/med/high with no problems.  Initially in testing it looked like a fan on low that's had it's status graphics page changed stays on low; but it might just be that homebridge isn't working properly.

unfortunately Homebridge v1.0.6 has become very unstable; I can make changes in Homekit that then reflect in homebridge but aren't passed to HS.  Or all devices become unreachable on Homekit and I can control devices on HS via the Homebridge config UI-X.  It's weird, sort of like homebridge can either talk to one or the other but not both.  After multiple attempts I'll sometimes get lucky and be able to send one command from Homekit to HS that makes it.

I added node-red today and replaced my Z-net

**Comment by Jmaddox71** [comment]
got another update.  fixed my instability.  The error in case you're curious was

Error: send EHOSTUNREACH 224.0.0.251:5353
    at doSend (dgram.js:683:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
    at afterDns (dgram.js:629:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

I believe this was a bonjur issue from homebridge.  solved it by rolling back to the previous version of each of my plugins and homebridge itself.  

homekit is back to normal and I can confirm that the slider doesn't control the fan (428) other than on and off at the very top and bottom.  Interestingly the slider change is reflected in the homebridge-config-ui-x page; but the homebridge log shows no command is forwarded (except when it's off or full on)

**Comment by jvmahon** [comment]
OK, so I'm closing this issue now. re-open if there's a continued problem. Thanks.
