### ISSUE TITLE
v1.0.6 corrupted the config of my smoke detectors and thinks my house is burning down

### ISSUE THREAD

**Issue by teladog01** [jvmahon/Homebridge-HomeSeer4#109]
Hi there. I don't see anything on the version history page for v1.0.6, but apparently something has changed with regard to the plugin handling of smoke sensors. After upgrading, all my smoke detectors showed as triggered..."Smoke Detected"...nearly gave me a heart attack as I was not at home at the time.

After checking the config.json, all of the "Off" values I had configured were gone. The only "Off" value left was "0". Here is an example of the config I had before the upgrade to 1.0.6:
```
                {
                    "type": "SmokeSensor",
                    "name": "Hallway Smoke Detector",
                    "ref": 1546,
                    "batteryRef": 1547,
                    "batteryThreshold": 78,
                    "offValues": [
                        0,
                        1,
                        2,
                        9,
                        12,
                        14,
                        13.255,
                        13.355
                    ]
                }
```
And after the upgrade they looked like this:
```
                {
                    "type": "SmokeSensor",
                    "name": "Hallway Smoke Detector",
                    "ref": 1546,
                    "batteryRef": 1547,
                    "batteryThreshold": 78,
                    "offValues": [
                        0
                    ]
                }
```
These are the First Alert ZCOMBO units...they are both smoke and carbon monoxide detectors. Here is what the status/graphics tab looks like for these units:

<img width="814" alt="Screen Shot 2020-09-03 at 8 57 40 AM" src="https://user-images.githubusercontent.com/210898/92124873-eb482180-edc3-11ea-9618-b22ab4a9e1cc.png">

Interestingly, I was able to add the missing "Off" values back, and the plugin seemed to have no problem with that. Also of note, I see there is a new "Settings" section for the plugin in Config UI X. When I open the settings for one of these smoke/co sensors, I don't see the "Off" values that were removed (which I added back), but they are still present in config.json.

<img width="756" alt="Screen Shot 2020-09-03 at 9 08 30 AM" src="https://user-images.githubusercontent.com/210898/92126216-82fa3f80-edc5-11ea-8cdd-9eecf3e9c338.png">
<img width="485" alt="Screen Shot 2020-09-03 at 9 11 18 AM" src="https://user-images.githubusercontent.com/210898/92126235-85f53000-edc5-11ea-940d-8e4bb82a61e5.png">

**Comment by jvmahon** [comment]
I am glad to to hear that your house did not burn down!

Version 1.0.6 added support to config-ui-x.  

I'm not sure why this would have changed your configuration, but I'll try to look into this.

**Comment by teladog01** [comment]
> I am glad to to hear that your house did not burn down!
> 
Ha! Me, too 😁 

Let me know if you need any more info...

**Comment by teladog01** [comment]
Update on this...I have restarted Homebridge several times while working on other stuff, and now HomeKit thinks my house is burning down again. Looks like the plugin has a problem with the "13.255" and "13.355" device values, as they are now missing again...

<img width="493" alt="Screen Shot 2020-09-03 at 12 35 27 PM" src="https://user-images.githubusercontent.com/210898/92148501-4db01a80-ede2-11ea-94f6-275c65d82b11.png">

Interestingly, I didn't lose all the other "Off" values this time, only the two non-Integer ones.

**Comment by shawnparr** [comment]
I'm also seeing the issue with non-integer values being lost on restart. My smoke/co detectors also use X.255 for status values.

Mine are also combination units, so I'm creating two advanced devices and manually setting the UUID_base value. For these devices it might be easier to have an "onValue" vs "offValue" since the have multiple values and one will be used for CO detected and another for Smoke detected.

**Comment by mwolter805** [comment]
@teladog01 and @shawnparr, sent a pull request with an updated config.schema.json awaiting @jvmahon's approval. This update allows decimals to be entered in the offValues for all Advanced Device types that support offValues. offValues with decimals now also remain after a reboot. You will need to update Homebridge to version 1.1.6 and Homebridge Config UI X to version 4.27.1 for this to work. There is still an issue where multiple offValues are not displayed but remain in the config when saving and over a reboot of the server. I believe this is an issue with Config UI X as I believe the schema is good.

**Comment by jvmahon** [comment]
Thanks @mwolter 
Update 1.0.9 has been published.
I'll close out this comment in a few days if no other issues are reported.

**Comment by teladog01** [comment]
Yea 🙌  My house is no longer burning down 😄

Looks good here. I am seeing the noted issue that only the 0 off value shows in Config UI X, but all the off values, including the non-integer ones, are still there in the actual config.json. Thanks very much 👍

**Comment by jvmahon** [comment]
@shawnparr - Regarding the suggestion of using "onValue" rather than "offValue" - I intentionally didn't do that. I was considering what happens if someone misconfigures the device - I'd rather a false alarm due to a missing "offValue" (as that can then be corrected) then missing an alarm due during a fire due to forgetting an "onValue."
