### ISSUE TITLE
Notifications automatically turned on?

### ISSUE THREAD

**Issue by devMarcus** [jvmahon/Homebridge-HomeSeer4#114]
Thank you so much for developing this plugin. 

One issue that I have noticed is that some devices (for example my Garage Doors) are by default set to have notification within HomeKit as enabled. Specifically, the setting “notifications on this iPad” are set to enabled. It seems that this is auto set that way on all of my devices. 

I know how to disable, but I am about to add many HomeSeer devices, and changing this setting after the fact across 10 plus IOS devices will be a pain.   

Is there a setting or code that I can change so that it doesn’t by default enable this setting?

Thank you so much.

**Comment by devMarcus** [comment]
I forgot to add that this is a HomeKit contact sensor based on a ELK M1G HomeSeer device. Using homebridge-homeseer4 v1.0.10 plugin IOS 14 GM.

**Comment by devMarcus** [comment]
Nevermind.   The version of the bridge is old. I will wipe out my HomeKit configuration and re-test/resubmit if needed.

**Comment by jvmahon** [comment]
No worries. Also, you can't control the "Notifications" setting from the plugin (there's just now way to do it), so you do have to set it for each device when you add it to the iOS Home App.

**Comment by devMarcus** [comment]
You probably already know this.

One can potentially manage the sensor notifications from the “home settings” interface. The key being that I didn’t want to go to each sensor and manually change it. This seems more of a central configuration interface. This makes more sense in terms of how Apple designed this. Now I will have to see how these settings flow to different devices.

What is interesting is that I much more prefer the HomeKit/Homebridge Integration look and feel than any HomeSeer interface has created has created.

Keep up the awesome work!  This is huge!

[cid:666D6458-2AB4-4FE6-A84F-35B8B713256A]

Sent from my iPad

On Sep 17, 2020, at 2:46 PM, jvmahon <notifications@github.com> wrote:

﻿

No worries. Also, you can't control the "Notifications" setting from the plugin (there's just now way to do it), so you do have to set it for each device when you add it to the iOS Home App.
