### ISSUE TITLE
after a while I get no response on the IOS home app

### ISSUE THREAD

**Issue by funsurfer558** [jvmahon/Homebridge-HomeSeer4#115]
setting up and using homebridge works when I first start it up I can control and all of my homeseer lights and power switches. but after a period of time running my home app in all of my IOS devices report no response. Home bridge and homeseer plugin  continues to run with not indication of an error. shutting down homebride and restarting makes everything work again but that is a pain in the butt. what can I do to get homebridge to continue to be reliable.

windows 10 pro version 10.0.19041

npm -g list --depth=0 results
C:\Users\homeseer user\AppData\Roaming\npm
+-- homebridge@1.1.6
`-- homebridge-homeseer4@1.0.10

node -v results
v12.18.3 

Thank you
Kurt

**Comment by jvmahon** [comment]
Try updating homebridge. Current version is 1.2.3.  My understanding is that the problem you describe may be linked to homebridge or one of its underlying libraries ("ciao") and was corrected in that code.

Just to be sure all its sub-libraries install correctly, I'd un-install and re-install
`````
npm -g uninstall homebridge homebridge-homeseer4
npm -g install homebridge homebridge-homeseer4
`````

**Comment by funsurfer558** [comment]
thank you for responding I uninstalled homebridge-homeseer4 and homebridge
and reinstalled upon reinstall of homebridge I did see the following
warning

npm WARN deprecated bonjour-hap@3.5.11: bonjour-hap is no longer
maintained. Refer to the Notice section of the README.md. The library
should not be used anymore
Could this be the reason for my lost connectivity to my homebridge server?

Kurt

**Comment by jvmahon** [comment]
That's odd to me. I think "bonjour-hap" is the library that was replaced by "cairo" so you shouldn't be seeing that.

Try 
`````
npm -g list --depth=1
`````

And look for "hap-nodejs" in the homebridge section - what's its version? It should be 0.8.2 or later.

As a last-ditch measure, I'd uninstall all the npm packages and remove the cache directory, then re-install.

To remove the cache directory, go to

`````
cd %HOMEPATH%\AppData\Roaming
`````

Then delete the folders "npm" and "npm-cache"

Then re-install homebridge and homebridge-homeseer4

**Comment by jvmahon** [comment]
Closed as there was no further response. Re-open if an issue remains.
