### ISSUE TITLE
Homekit events behaviour

### ISSUE THREAD

**Issue by Rudi6** [jvmahon/Homebridge-HomeSeer4#117]
Hello,

Is it possible toe have HS events to act like a button instead of a switch?
I have a room with 3 states: Off, On, Dim. Now I have 2 switches On/Off, Dim/Off but setting one to off leaves the other on. This is confusing for my wifi so I would like to have 3 buttons. An event is in fact a trigger that behaves like a button.

I could make 3 virtual devices to act like a button but that gives another 3 virtual devices in HS

Greetings Rudi

**Comment by jvmahon** [comment]
Unfortunately, HomeKit doesn't have a straightforward "button" type so I don't have any way of doing this.
