### ISSUE TITLE
Battery Reporting

### ISSUE THREAD

**Issue by jameswestcott** [jvmahon/Homebridge-HomeSeer4#118]
When a battery in HomeSeer goes flat it reports a value of 255. Some devices may report other fault values between 101 and 254. Currently plugin is reporting to HomeKit any battery level above 100 as 100 when it should report as 0.

**Comment by jvmahon** [comment]
Fixed in new version 1.0.11.
Thanks.

**Comment by jameswestcott** [comment]
Wow! thanks for doing that so quickly

**Comment by jvmahon** [comment]
Yeah, it was an easy fix.  But I haven't tested it, so let me know if it doesn't work.
Re-open this issue and post if there is a problem.
