### ISSUE TITLE
Water Valve

### ISSUE THREAD

**Issue by XiozTzu** [jvmahon/Homebridge-HomeSeer4#119]
Used the GUI to add valve and it seems to work fine from Home app manually changing but it does not show up as an accessory to control when setting up an automation.

**Comment by jvmahon** [comment]
Nobody has ever mentioned that before -- and I never noticed it myself, but you're right!  I also found several internet postings that this is an Apple limitatin. See: https://github.com/RavenSystem/esp-homekit-devices/issues/316

My recommendation - set up the valve as a switch instead.
