### ISSUE TITLE
Advanced Thermostat Temp and Mode Issues

### ISSUE THREAD

**Issue by taylorwmj** [jvmahon/Homebridge-HomeSeer4#122]
I have an Aprilaire 8840 thermostat that I have gotten working with a plug-in for HomeSeer. Lots of control broken out on it (see attach). I am able to add it to Homebridge, but have some weird experiences. 

1). In the home app, both the Heat and Cool setpoint temps are being read and thus showing as a range, even if the stat is off. 

2). When attempting to set the stat mode, the mode will proceed to then auto switch down the list through heat, cool, and then end at auto. 

![image](https://user-images.githubusercontent.com/11332705/98756355-015bfa80-2390-11eb-81a1-8cc32c73a480.png)

![image](https://user-images.githubusercontent.com/11332705/98757225-af1bd900-2391-11eb-8942-1acddf8bb3db.png)

![RPReplay_Final1605051810](https://user-images.githubusercontent.com/11332705/98757408-16d22400-2392-11eb-8632-3f44eb307d80.gif)

**Comment by jvmahon** [comment]
I don't think that thermostat is compatible. There should be a reference for the current room temperature. I don't see that in the set of HomeSeer controls that you posted. HomeKit requires that thermostats have a current temperature reference to work.

If you have a separate temperature sensor in the room, maybe that could be used instead. In which case, the proper configuration would be something like what I've shown below.

However, given this is already an odd-looking implementation, I'd also need to see how the "status graphics" page is set up for your device (specifically, for the controls 26 and 29) to be confident. You could always give it a try and report back if it works or doesn't. Thermostats are very tricky code and require that the plugin maker carefully conform to the HomeSeer specs or it won't work.


`````
"accessories":
[
	{
		"type": "Thermostat",
		"name":"My Thermostat Name",
		"ref": (your temperature sensor reference #),
		"controlRef": 29,
		"stateRef": 26,
		"heatingSetpointRef": 31,
		"coolingSetpointRef": 30,
		"humidityRef": 
	}
]
`````

**Comment by taylorwmj** [comment]
Thanks for the specifics and reply @jvmahon. I've since decided to go a different route for home automation instead of rowing my own as I have the last few years as my time is becoming a bit more valuable than my money. I've gone the Control4 route and it's working well
