### ISSUE TITLE
Custom Open / Closed Values not working

### ISSUE THREAD

**Issue by AdamCavaliere** [jvmahon/Homebridge-HomeSeer4#123]
I have 2 ZWave Window Coverings that are not showing the correct status. I tried using the advanced device option to set the custom open / close values and they are not working. Please let me know what data I can provide to help troubleshoot this.

**Comment by jvmahon** [comment]
Please explain what type of device and show the device page as well as the status graphics page.

**Comment by AdamCavaliere** [comment]
Here is the configuration:
            "accessories": [
                {
                    "type": "WindowCovering",
                    "name": "Great Room Drapes",
                    "ref": 2057,
                    "openValue": 99,
                    "closedValue": 0
                }
            ],

![image](https://user-images.githubusercontent.com/26278721/100144884-15f2c500-2e5d-11eb-992c-4a8416dbf19c.png)

![image](https://user-images.githubusercontent.com/26278721/100144925-26a33b00-2e5d-11eb-81ed-96848258c7e3.png)

![image](https://user-images.githubusercontent.com/26278721/100144955-37ec4780-2e5d-11eb-9a01-dc2e83d1ea53.png)

![image](https://user-images.githubusercontent.com/26278721/100145007-49cdea80-2e5d-11eb-8f1c-24c97b1f2764.png)

**Comment by jvmahon** [comment]
When you say the window coverings don't show the correct status - what do you mean?
What are they showing and what do you think they should show?

**Comment by jvmahon** [comment]
Closed since there wasn't a response.

**Comment by Duc1198** [comment]
Hi Jvmahon,

I'm similar issue.

I'm running the homeseer arduino plugin. 

I can't seem to get the status to update correctly in homebridge. I can see the homebridge logs record the correct status change but the icon will not show device is on.
If I try and turn device on in home up I have to turn on twice to get it to stick.

{
"type": "LightSwitch",
"name": "Backyard Garden Lights",
"ref": 4223,
"onValue": 0,
"offValue": 1
}
![2022-11-06_8-01-26](https://user-images.githubusercontent.com/71119249/200142177-5d0deece-3305-49c5-b91f-686c616345c7.jpg)

**Comment by jvmahon** [comment]
Sorry, really don't know what to do about arduino - no experience with it.
