### ISSUE TITLE
Solution Proposed - Omni Thermostats

### ISSUE THREAD

**Issue by JCCcccspud** [jvmahon/Homebridge-HomeSeer4#124]
I have Homeseer interfacing with an Omni system, which includes Omni thermostats.  In Homeseer, each of the thermostats has about 10 reference numbers:   root device, temperature, heating setpoint, cooling setpoint etc.

I tried adding the root device number under simple device in the Homebridge Config UX I app but then Homebridge would not restart.  I have not tried using the advanced device as I am not sure what some of the boxes are for like Uuid base, Control ref etc.

How do I properly set up these thermostats?  Thanks.

**Comment by jvmahon** [comment]
Please post your device page for the thermostat showing all of the devices and reference numbers and I'll take a look.

**Comment by JCCcccspud** [comment]
On Monday, November 16, 2020, 10:36:22 AM CST, jvmahon <notifications@github.com> wrote:  
 
 


Please post your device page for the thermostat showing all of the devices and reference numbers and I'll take a look.

**Comment by JCCcccspud** [comment]
![image](https://user-images.githubusercontent.com/63560486/100551149-9130ee00-3244-11eb-8052-7484f333a0c3.png)

**Comment by jvmahon** [comment]
There's a section on Thermostats in the wiki explaining what to do. See https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Thermostats

But to help you out ... In the "accessories" section of your config.json, try entering the following:

`````
"accessories":
[
	{
		"type": "Thermostat",
		"name":"Upstairs Thermostat",
		"ref": 171,
		"controlRef": 174,
		"stateRef": 178,
		"heatingSetpointRef": 172,
		"coolingSetpointRef": 173,
		"humidityRef": 175
	}
]
`````					

You generally don't need to enter the other parameters except under special circumstances. For example, if your Thermostat controlled the temperature in multiple rooms, you could make multiple copies of the configuration data in your config.json, but would need to distinguish each one with a unique uuid_base. See  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Show-the-same-device-in-multiple-rooms

I'd have to go back and check if I actually implemented the Humidity Target, but you could also try including:

`````
"humidityTargetRef": 179
`````

Please let me know if this works

**Comment by jvmahon** [comment]
No further response, so I'm closing this out.
