### ISSUE TITLE
ETIMEDOUT while connecting on HOOBS Homebridge

### ISSUE THREAD

**Issue by wavi-web** [jvmahon/Homebridge-HomeSeer4#125]
Using the Homebridge/Homeseer4 plugin version 1.011 on HOOBS 3.2.10 on a Rpi4, nodeversion 12.16.3.
I posted this issue a while ago, but now several updates have past and still no solution. 

Posted this problem on the HOOBS github, but got no response. 
Any help in how to solve this issue would be welcome.

Log:
19-11-2020 08:37:59 Loaded plugin 'homebridge-homeseer4'
19-11-2020 08:37:59 homebridge API version: 2.6
19-11-2020 08:37:59 [11/19/2020, 12:37:59 AM] Registering platform 'homebridge-homeseer4.HomeSeer'
19-11-2020 08:37:59 Loading 1 platforms...
19-11-2020 08:37:59 [HomeSeer] Initializing HomeSeer platform...
19-11-2020 08:37:59 [HomeSeer] Start
19-11-2020 08:38:31 (node:17161) UnhandledPromiseRejectionWarning: FetchError: request to http://xxx:xxx@192.168.1.10/JSON?request=getstatus failed, reason: connect ETIMEDOUT 192.168.1.10:80
19-11-2020 08:38:31 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
19-11-2020 08:38:31 at ClientRequest.emit (events.js:310:20)
19-11-2020 08:38:31 at Socket.socketErrorListener (_http_client.js:426:9)
19-11-2020 08:38:31 at Socket.emit (events.js:310:20)
19-11-2020 08:38:31 at emitErrorNT (internal/streams/destroy.js:92:8)
19-11-2020 08:38:31 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
19-11-2020 08:38:31 at processTicksAndRejections (internal/process/task_queues.js:84:21)
19-11-2020 08:38:31 (node:17161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
19-11-2020 08:38:31 (node:17161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Sorry, I don't know much about Hoobs so I have very limited ability to help, but ...
I assume that in the line:
`````
 http://xxx:xxx@192.168.1.10/JSON?request=getstatus
`````
shown above, you inserted the xxx:xxx in place of your user name / password.

Try taking the "real" version of this url (i.e., with your HomeSeer user name / password in place of the xxx:xxx) and pasting it into a browser.

Do you get a response?  

You should get a significant amount of JSON code back representing the status of all your devices.

If you don't get that back when in the browser, there may be a user name / password problem.

Remember - this is not your computer system password, but the separately set password for HomeSeer.  Check to make sure you have the user name / password for HomeSeer properly set and it matches what is entered in the config.json.

**Comment by wavi-web** [comment]
Hi Jvmahon, thanks for responding, that is correct. The xxx;xxx is in place of u/pw. Copied the url in a browser, it gives a response with the status of the devices. User/pw in json.config are the same as in hs4.

**Comment by wavi-web** [comment]
Hello, any input on this issue would be appreciated. 
Thx.

**Comment by jvmahon** [comment]
Sorry, I am not familiar with HOOBS and I have no idea what is wrong.  The only thing I can suggest is try updating Node. I'm currently using 14.15.1
