### ISSUE TITLE
Homebridge cannot reach Homeseer on local IP address and connection is dropped using MyHS url.

### ISSUE THREAD

**Issue by Elbowman5675** [jvmahon/Homebridge-HomeSeer4#126]
I have downloaded and installed the latest version of HomeBridge Homeseer 4 and am running it on RPi 3.  set it up to connect to a client's HomeSeer account and initially connects just fine with config.json set up to use external address of connectedca.homeseer.com with login and password.  Hombridge connects and gets status of all devices, then reports a fatal error on connection. 
setup device at clients site and change config.json to use the IP address that has been bound by homeseer (setting in settings.ini file), but the IP Address cannot be reached by any device locally.  Homebridge error says EONOHOSTFOUND. Try connecting homebridge using the IP address of the Homeseer device and get a connection refused error ECONNREFUSED.  This could be an issue with router or with HomeSeer.  Homebridge will repeatedly attempt to re-connect using external address (after changing back to that in config.json) and reports same fatal error.  I'm looking to confirm that the Homeseer platform connection must be a local one and that login and password must be included in config file.  Any insight on why HomeSeer web server cannot be accessed locally or why device address connection is refused would be of great help.

**Comment by jvmahon** [comment]
The plugin uses both a http connection as well as a telnet connection (which HomeSeer refers to as an ASCII control port).
By default, HomeSeer is configured with the telnet / ASCII connection turned off.
Did you turn it on and then restart HomeSeer?

See Section 2 of this Wiki: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki

**Comment by Elbowman5675** [comment]
Yes.  This is set up and working, as evidenced by the fact that Homebrige received an initial status of each device defined in the config.json file.  The issue is the external connecting being dropped, then reconnection failing for all subsequent retries from Homebridge.
![Homeseer_ntwrk_settings_20201119](https://user-images.githubusercontent.com/74702582/99704672-91173e00-2a4d-11eb-8115-bf59a896bbe8.png)

**Comment by Elbowman5675** [comment]
The issue and solution became apparent after googleing the error in  the homeseer log when initializing the web server.  To support homebridge, the IP address for the web server was  bound to a static IP which did not exist on the network.  The fix was to make a DHCP address reservation for the IP address, then restart Homeseer.  Homebridge was then able to connect locally to the network IP address and all is good.
