### ISSUE TITLE
SecuritySystem enhancements

### ISSUE THREAD

**Issue by bradhs** [jvmahon/Homebridge-HomeSeer4#127]
Hello,
Would it be possible to expand on the SecuritySystem by adding a Exit Delay in Progress status.  This way HomeKit knows that the alarm has been activated and is currently counting down to arming.

**Comment by jvmahon** [comment]
I'm not aware of any way to do this in HomeKit.  I'll leave this comment open a few days to see if anybody else has any ideas.

**Comment by bradhs** [comment]
Also, would like status for "NOT READY" when the alarm is not ready to be armed.

In summary, add statuses: "EXIT DELAY IN PROGRESS" and "NOT READY TO ARM"
It would also be cool to be able to list the sensors that are "open"

**Comment by jvmahon** [comment]
That would be useful, but I can't do it. HomeKit allows only the valid values listed below and I can't add to them. I implemented to Release 2 of the HomeKit Accessory Protocol -- this was last updated in 2019 - maybe they'll update the specification at some point to give some more flexibility, but it isn't there now.

![image](https://user-images.githubusercontent.com/15061942/103008582-5c424f00-4503-11eb-868a-bc417e5f2118.png)
