### ISSUE TITLE
Simple thermostat structure and parameters

### ISSUE THREAD

**Issue by mbaastrup** [jvmahon/Homebridge-HomeSeer4#132]
I have created a virtual thermostat (as I dont have a physical, but a lot of z-wave radiator valves and temp sensors) in HS4 but would like to use your simple setup method - can I find the specs for how to design the parent (a tempsensor I guess) and the parameters that are used to discover child devices. I can the do the linking between them in HS4 in the right way by editing the device json file.

/MB

**Comment by jvmahon** [comment]
I think it would be difficult to use your virtual thermostat with the "simple" setup method. The "simple" method looks at a number of underlying HomeSeer data structures which I don't think can be set up properly with a virtual device.

**Comment by jvmahon** [comment]
If you did want to try, put the following confirmation information into the  "accessories" section of your config.json and set it up as indicated .  .
`````
					{
						"type": "Thermostat",
						"name":null,  // Whatever name you choose
						"ref": 0,    // Set to a device that measures temperature. Any thermostat device will do.
						"controlRef": 0, // Set to a device that can control the mode (off, heating, cooling, see note below)
						"stateRef": 0,
						"heatingSetpointRef": 0,
						"coolingSetpointRef": 0,
						"humidityRef": 0,
						"humidityTargetRef": 0
					},
`````

For the controlRef, create a virtual device with the following states / valuesthat :  Off = 0, Heat = 1, Cool = 2, Auto = 3

**Comment by mbaastrup** [comment]
Thanks again - I have done it with the complex, not a big problem at all. It was just if you had it at hand, i can navigate the device.json and rearrange the parent/childs but there might be limitations for sure.

Just close this one :-)

**Comment by mbaastrup** [comment]
This is exactly what I did, and it work fine (didn’t use the humidity devices though)

**Comment by jvmahon** [comment]
OK, glad to hear you solved it - I'm closing this out. Re-open if there are further questions.
