### ISSUE TITLE
Device in use parameter for Outlet

### ISSUE THREAD

**Issue by jameswestcott** [jvmahon/Homebridge-HomeSeer4#135]
Any chance you could add the “device in use” parameter to the Outlet type?

I can trigger this from a virtual device based on the wattage of a zwave device and would be useful to know if an appliance plugged in to a zwave outlet is actually in use or not.

**Comment by jvmahon** [comment]
Sorry, I can't do this. I've moved off of HomeSeer to hubitat, so I'm doing very little development on this plugin.
