### ISSUE TITLE
This plugin generated a warning from the characteristic 'Color Temperature'

### ISSUE THREAD

**Issue by amdanas** [jvmahon/Homebridge-HomeSeer4#138]
I have an Ikea FLOALT panel WS 60x60 which is a dimmable color temperature light. 

I created an advanced device  in Homebridge-Homeseer4 plugin, identified as LightBulb and using  for "Ref" the device number from HomeSeer and for "Color Temperature Ref" the Color temperature number used in HomeSeer. "On Value" set to 255 and "Off Value" to 0.  HomeKit shows a dimmable light that has 6 color tones.
The dimming works as expected but when I try to choose any color, nothing happens. 

I noticed these in Homebridge Logs:
- When I choose any of 6 colors on my iPhone, I can see the corresponding value logged in Homebridge. This is one example: "Received a new ColorTemperature Value of: 140 when On was set to: true and while Multilevel Value was 4". But the color doesn't change. I suppose that because the value is out of the required range in HomeSeer(2000-6500).
- When I modify the device's temperature from HomeSeer the color changes accordingly but in Homebridge console appears this message: "This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 3906 exceeded maximum of 500. See https://git.io/JtMGR for more info."

Could you give me any guidance how to manage this? 
Thanks!

**Comment by jvmahon** [comment]
Sorry, no idea. Color isn't well supported - I have no color devices, so I it isn't well tested.

**Comment by jvmahon** [comment]
I just published update 1.0.16 which (I hope) fixes (or at least reduces) this problem..

I am no longer using HomeSeer so I can't test this -- can you test and confirm that the update doesn't cause any crashes and that you no longer see this error.

Please post a confirmation so I can close this issue.

**Comment by amdanas** [comment]
Thank you for updating the plugin. I confirm that there is no issue related to color temperature. I really appreciate your effort.

**Comment by jvmahon** [comment]
You're welcome.
