### ISSUE TITLE
This plugin generated a warning from the characteristic 'Current Ambient Light Level'

### ISSUE THREAD

**Issue by CyberRad** [jvmahon/Homebridge-HomeSeer4#139]
OS- Raspbian Buster
Node - 14.5.5
Plugin - homebridge-homeseer4 v1.0.13

Seeing the following in Homebridge logs since the 1.3.0 update. [homebridge-homeseer4] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.

Homebridge 1.3.0 release mentions that these warnings were hidden in previous versions but are now visible.

> Compatibility
Homebridge v1.3.0 does not introduce breaking changes for the majority of existing plugins, while you may see Characteristic Warnings in the logs, these are just issues that were already present prior to v1.3.0 - just hidden from view. You should update your plugins before updating Homebridge.

Might be similar to #138

**Comment by dibble9012** [comment]
I got the same exact error as well.

**Comment by jvmahon** [comment]
Thanks. I'll add range checking to the code.

**Comment by jvmahon** [comment]
I just published update 1.0.14 which (I hope) fixes this.

I am no longer using HomeSeer so I can't test this -- can one of you test and confirm that it doesn't cause any crashes and that you no longer see this error.

Please post a confirmation so I can close this issue.

**Comment by CyberRad** [comment]
This popped up upon restart but the plugin is running.

> [25/02/2021, 08:57:12] Homebridge v1.3.1 (Homebridge) is running on port 51826.
[25/02/2021, 08:57:12] [HomeSeer] Successfully connected to ASCII Control Interface of HomeSeer.
[25/02/2021, 08:57:12] [HomeSeer] Sent Authorization Data
[25/02/2021, 08:57:12] [HomeSeer] Successfully authorized Telnet port
(node:31258) UnhandledPromiseRejectionWarning: ReferenceError: updateValue is not defined
    at CurrentAmbientLightLevel.<anonymous> (/usr/lib/node_modules/homebridge-homeseer4/lib/Sensor Setup.js:160:20)
    at CurrentAmbientLightLevel.emit (events.js:315:20)
    at HomeSeerSystem.processReceivedData (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerSystemObject.js:253:15)
    at pollHomeSeer (/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Listener.js:145:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Oops. Published 1.0.15 -- Please Try again.

**Comment by CyberRad** [comment]
I installed and restarted. Looks like the same error.

> [25/02/2021, 09:30:05] [HomeSeer] Successfully authorized Telnet port
(node:32689) UnhandledPromiseRejectionWarning: ReferenceError: updateValue is not defined
    at CurrentAmbientLightLevel.<anonymous> (/usr/lib/node_modules/homebridge-homeseer4/lib/Sensor Setup.js:160:20)
    at CurrentAmbientLightLevel.emit (events.js:315:20)
    at HomeSeerSystem.processReceivedData (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerSystemObject.js:253:15)
    at pollHomeSeer (/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Listener.js:145:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Yeah, I probably should have hit "save" on my updated file before I uploaded it to github.

One more time. 1.0.16

**Comment by CyberRad** [comment]
Looks promising so far. No errors and the initial issue seems to be gone. Thanks

**Comment by jvmahon** [comment]
OK - I'll close this out. Re-open the issue if you notice a problem.
