### ISSUE TITLE
Possible to change decimals on Lightsensor?

### ISSUE THREAD

**Issue by malosaa** [jvmahon/Homebridge-HomeSeer4#141]
Hi,

Right now on homeseer i have an device that checks the power consumption.
i added it as an lightsensor device, sadly it shows 15 decimals.
Is there a way to change that?

regards

**Comment by jvmahon** [comment]
Update to version 1.0.18 - it should now round to 2 decimals.

**Comment by malosaa** [comment]
i just see your message, thank you ill try it.

regards

**Comment by malosaa** [comment]
@jvmahon 

I did update but still low value like 1 shows as 0.0001 the rest works perfect.
regards

**Comment by jvmahon** [comment]
Hi,

0.0001 is the minimum value in HomeKit for a light sensor. I guess they are saying you can never have absolute darkness!

See following table from the  HomeKit standard.
![image](https://user-images.githubusercontent.com/15061942/125159670-cdb3b900-e146-11eb-85de-55c25588425b.png)
