### ISSUE TITLE
Critical Error on Startup

### ISSUE THREAD

**Issue by splineGear** [jvmahon/Homebridge-HomeSeer4#142]
Hi there, I'm getting this error on the startup of the plugin:

`(node:2879) UnhandledPromiseRejectionWarning: TypeError: getStatusInfo.Devices is not iterable`
`    at HomeSeerSystem.initialize (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerSystemObject.js:486:42)`
`    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
 `   at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:96:24)`
`(Use 'node --trace-warnings ...' to show where the warning was created)`
`(node:2879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict\' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`
`(node:2879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This is on version 1.0.17, which I believe is the latest.
The plugin is running on Raspian using node 14.16.1 .

My config is pretty trivial:

`{`
 `   "name": "HomeSeer",`
 `   "host": "http://homeseer.mydomain",`
 `   "ASCIIport": 11000,`
 `   "login": "specialuser",`
 `   "password": "somepassword",`
`    "Switches": [`
`        123`
`    ],`
`   "platform": "HomeSeer"`
`}`

Any pointers as to how I might debug would be much appreciated.

Note that other plugins are working fine, I've tried various restarts and have verfied telnet connectivity from the homebridge server.

After this error occurs, homebridge fails to start. The following error given is:
`[homebridge-homeseer4] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.`

Thanks!

**Comment by jvmahon** [comment]
Given the error lines shown, it means that the plugin is having problems connecting to HomeSeer. Its possible its a login / password error.

From the Setup menu, choose the "Network" tab, and then select "No Password Required for Local (same subnet) Login"
![image](https://user-images.githubusercontent.com/15061942/114302394-da1c6d00-9a96-11eb-8ddc-0e395d5ffe44.png)


Make sure you've also turned on the ""Enable Control Using ASCII Commands" option.


![image](https://user-images.githubusercontent.com/15061942/114302381-ca048d80-9a96-11eb-87f2-6627a4661ccf.png)

**Comment by jvmahon** [comment]
Also, from that same configuration page, check the Server Port
![image](https://user-images.githubusercontent.com/15061942/114302484-41d2b800-9a97-11eb-83da-0d9713812e92.png)

And maybe try adding the port to the host line like:
"host": "http://homeseer.mydomain:80",

**Comment by splineGear** [comment]
Thanks for the pointers, I hadn't correlated that error with a network connectivity issue. I've checked the items you mentioned and verified connectivity from the host homebridge is running on by doing:

For verifying the ASCII interface:
`telnet homeseer.mydomain 11000`
From this I observe a stream of response like:
```
DC,363,6334484.6818334,6334483.869594
DC,364,1435.5613127,1434.7490733
DC,365,335.6362187,334.8239793
DC,234,116725843.743594,116725842.525233
DC,235,116730637.007762,116730635.789401
DC,354,1436.779674,1435.5613127
DC,361,11344007.7523945,11344006.5340332
DC,363,6334485.9001947,6334484.681833
```

For verifying the local access without password:
`wget homeseer.mydomain`
From this I get index.html with the Homeseer homepage.

I also appended the :80 you recommended, all to no avail.

Is it possible that this is an authentication issue? or that the configuration of the status on the ASCII interface is having difficulties? ... or this is failure earlier (i.e. at the creation of the socket)?

Is there a way to increase the log verbosity? or should I just focus on network issues? Maybe I'll try a network trace to debug...

Many thanks for your assistance.

**Comment by jvmahon** [comment]
Try using the actual IP number in the host line.
If you are running Homebridge on the same computer as you are running homeseer, you should be able to use:

"http://127.0.0.1:80"

**Comment by jvmahon** [comment]
also, try manually accessing homeseer from a browser (inserting your login name, password as indicated) using a HTTP url of the form: 
`````
http://specialuser:somepassword@homeseer.mydomain:80/JSON?request=getcontrol
`````

Do you get back a big block of data in JSON form (you should). If not, its an authenticatin / authorization issue.

**Comment by splineGear** [comment]
Ok, solved via tcpdump. Partly my stupidity for not enabling JSON and just the ASCII interface. Partly due to a glitch in the configuration in my version of homeseer. To enable the ASCII interface I had to **_remove_** the tickbox next to 'Enable control using ASCII commands'.  No kidding.


`Apr-12 9:22:30 PM |   | Info | ASCII connection authorization OK from IP: 42.42.42.42 for user someuser`
(IP and user mangled)

Thanks for your assistance @jvmahon .
