### ISSUE TITLE
Broken with HOOBS 3

### ISSUE THREAD

**Issue by jlrichar** [jvmahon/Homebridge-HomeSeer4#147]
`The plugin "homebridge-homeseer4" requires a Homebridge version of >=1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.`

This is with HOOBS 3.3.5 (up to date as of today)

**Comment by jvmahon** [comment]
Not sure I understand the issue. Version 1.3.4 of Homebridge is available. See: https://www.npmjs.com/package/homebridge
Update homebridge.  Were you unable to do that?
