### ISSUE TITLE
WindowCovering open/closed value

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/Homebridge-HomeSeer4#148]
According to config.complex.json the WindowCovering supports open/closed values. However If I create a device with open value 0 the HomeApps states it's closed. If I use the type GaragedDoorOpeners it does work.
              {
                    "type": "WindowCovering",
                    "name": "Rolluiken",
                    "ref": 553,
                    "openValue": 0,
                    "closedValue": 100
                },

**Comment by AlanSmithe** [comment]
I forgot that you told me in the previous bug that 0 can still never be "On". This is probably the same with windows covering right?

**Comment by jvmahon** [comment]
Not sure. The code is different for different devices. I'll try and look this weekend.
Can you try one thing - Use "BinaryWindowCovering" instead of "WindowCovering" and see if that works correctly.

Thanks,

**Comment by AlanSmithe** [comment]
Yes the "BinaryWindowCovering" does work correctly
However if the blinds are 70% closed the binary switch still says 100% Open. Only 100% closed (in my KNX app) makes Apple Home say 100% open.

**Comment by jvmahon** [comment]
What's happening then is that there is code that, if you just specify "WindowsCovering" it tries to determine if the window is a "variable" covering - which allows true 0 - 100% positioning, or a "Binary" type which only supports open/closed. 

This detection usually works, but not always. Can you post an image of the "Status Graphics" page for this device (particularly, the controls section). Maybe I can figure out why it didn't work right for you and I'll improve the detection.

**Comment by AlanSmithe** [comment]
Thank you again for your time.
https://i.imgur.com/xiVy6LE.png

**Comment by AlanSmithe** [comment]
Where you able to look into this?

**Comment by jvmahon** [comment]
No, sorry. As a practical matter, I'm so busy with work and other items, that I just don't see me spending time on this any time soon.
