### ISSUE TITLE
Lighting Values in Homebridge- HomeSeer 4

### ISSUE THREAD

**Issue by Silas888** [jvmahon/Homebridge-HomeSeer4#149]
First off I love this product. It works well with exposing Homeseer devices to IOS. I also use it with Alexa by coupling Homebridge-HomeSeer4  with another plug in called Homebridge Alexa. My question is with the latter. In HomeSeer all of my lighting devices have a dim range of "1-98". It has an OFF value of "0" and an ON value of "99". Until very recently, I could say to Alexa, "Kitchen Lights 100%" and she would do this setting the lights to its highest value without complaint.  Now she's very specific with her range values. When issued the same command, she replies "that command doesn't work on device "Kitchen" and sets the value to its "On Last Level" value which is 255. Unfortunately if the last level was 25%, that is the level I get.

My question: is there a way that Homebridge can correct this? To somehow expose that the lighting range is 0-100 is valid?

**Comment by jvmahon** [comment]
Sorry, no idea about the Alexa part - I didn't write that and that plugin works independently from mine.

In my "HomeSeer4" plugin, I have code that maps between the 100% value and the Z-wave "99" so it should work. The "Alexa" plugin author would have to figure out a mapping in his code to do the same.

**Comment by Silas888** [comment]
Does "HomeSeer4" plugin expose the lights ability as 0-100% or does it only show it up to 99% which _technically_ is its ability in Homeseer.

**Comment by jvmahon** [comment]
The plugin should allow HomeKit to treat it as 0 - 100%.

To be honest, I haven't looked at this code in a while (I've switched to using Hubitat), but I'm still maintaining the code. Here's how it should be working  . . .

If HomeKit (iOS) tells the plugin to set the device to 100%, then the plugin will recognize that Z-wave devices really only go up to 99, so the plugin will tell HomeSeer to use 99. So, in iOS you see 100%, but the plugin handles the conversion.

If HomeSeer tells the plugin that a device was set to 99, then the plugin recognizes that most of the time, this was really someone who wanted it to be set as "full on" and, in HomeKit this should be 100%, so the plugin tells the iOS device that the light is at 100%. even though HomeSeer shows 99.  

So, if HomeKit shows 100% but HomeSeer shows 99, don't worry - that's what is supposed to happen.


The plugin for your Alexa devices might not have implemented this extra "mapping" code - I really don't know.

**Comment by Silas888** [comment]
ok that is good information to have. 

May I ask why you switched to Hubitat?

**Comment by jvmahon** [comment]
A number of reasons. Some that stand out . . .

- I prefer the "Rule" engine in Hubitat. and find it is more powerful.
- Hubitat has better built-in Zigbee handling and allows me to easily mix Z-wave and Zigbee
- I also find it easier to write plugins for Hubitat (The Hubitat port of my HomeBridge plugin is significantly simpler).


But, there are also HomeSeer advantages that can't be overlooked either . . .

- The HomeSeer programming environment seems to be more powerful, so if you are doing a more complex plugin, HomeSeer may be a better choice.
- HomeSeer was always rock solid. Hubitat seems to have some growing pains with stability and I find myself rebooting more often.


If I was asked to recommend one versus the other, I'd pick Hubitat, but its not a "definitely, always, no doubt" kind of choice.

**Comment by Silas888** [comment]
Interesting. I've heard good things about Hubitat￼. Also the only serious contender to HomeSeer as it has local processing like HomeSeer. ￼As for me I guess I spent so much time perfecting my HomeSeer system￼ the thought of moving to another platform ￼would be frightening￼.
