### ISSUE TITLE
Confused about what file works. This seems to work but I want to add other switches not just my bulb

### ISSUE THREAD

**Issue by silverton38** [jvmahon/Homebridge-HomeSeer4#152]
Confused about what file works. This seems to work but I want to add other switches not just my bulb. I want to add a switches and thermostats. Does someone have a simple file that they can post?

{
    "accessories": [
        {
            "type": "Lock",
            "ref": 640
        }
    ],
    "platforms": [
        {
            "platform": "HomeSeer",
            "name": "HomeSeer",
            "host": "http://10.0.0.15",
            "ASCIIport": 11000,
            "login": "xxxxxxxx",
            "password": "xxxxxx",
            "accessories": [
                {
                    "type": "Lightbulb",
                    "ref": "1315"
                }
            ]
        }
    ]
}

**Comment by silverton38** [comment]
I do not know where the lock ref is coming from. Here is the file as I see it now.

{
    "platform": "HomeSeer",
    "name": "HomeSeer",
    "host": "http://10.0.0.15",
    "ASCIIport": 11000,
    "login": "xxxxxxxx",
    "password": "xxxxxxxxxx",
    "accessories": [
        {
            "type": "Lightbulb",
            "ref": "1315"
        }
    ]
}

**Comment by jvmahon** [comment]
Did you look in the Wiki pages: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki

Also, be sure to check "show Device Ref on Status Page" to see the proper Ref number to use. See:
![image](https://user-images.githubusercontent.com/15061942/132279022-e96370b3-15c9-4076-b2f3-7c63dc97bee9.png)

**Comment by silverton38** [comment]
I have. The config files do not work in Hoobs and Homebridge. I was able to get it working but it is not very clear so most people will not be able to make it work. I want to get the visual configuration working for both Hoobs and Homebridge. I am looking for people to assist in this project.

**Comment by silverton38** [comment]
By the way thank you so much for the work you did so far.

**Comment by jvmahon** [comment]
Have you tried setting up other devices from the config-ui-x interface?

**Comment by jvmahon** [comment]
Since there was no response, I assume you figured this out using the Config-Ui-X interface.
