### ISSUE TITLE
Plug-in with HOOBS 4

### ISSUE THREAD

**Issue by csullivan2005** [jvmahon/Homebridge-HomeSeer4#157]
Does your plug-in work with HOOBS 4?  I’m having a lot of issues.

**Comment by jvmahon** [comment]
There are people on the HomeSeer forums who are using it with Hoobs, but I never have. Perhaps they can help you resolve your issues. See, e.g., https://forums.homeseer.com/forum/homeseer-products-services/system-software-controllers/hs4-hs4pro-software/1348142-proper-homekit-support?q=hoobs

**Comment by bobsilver** [comment]
I just got this working.  There is an error in the configurator.  After you created a device you will need to edit the JSON config file by going into the advanced bridge settings and change the "name" to "ref".  After that I got access to the devices I wanted.  Note that each device must be added individually.  

Here are my devices from my config json.  

    "accessories": [
                {
                    "type": "DimmingLight",
                    "ref": "250"
                },
                {
                    "type": "LightSwitch",
                    "ref": "1165"
                },
                {
                    "type": "Outlet",
                    "ref":"269"

**Comment by bobsilver** [comment]
I missed some of the ending syntax.  Here it is complete

 "accessories": [
                {
                    "type": "DimmingLight",
                    "ref": "250"
                },
                {
                    "type": "LightSwitch",
                    "ref": "1165"
                },
                {
                    "type": "Outlet",
                    "ref": "269"
                }
            ]

**Comment by jvmahon** [comment]
Glad to see you got it working!
