### ISSUE TITLE
Doesn't import HS4 devices

### ISSUE THREAD

**Issue by ivanvach** [jvmahon/Homebridge-HomeSeer4#159]
I installed HomeBridge and this plug-in successfully. 
iPhone "Home" app did recognize and adopt HomeBridge.
However iPhone "Home" app doesn't show any of my HS4 devices.
Isn't the plug-in supposed to import all of my HS4 devices in HomeBridge ?
Please advise what to do. Manual entry of devices one by one is not an option for me.

Thanks,

**Comment by jvmahon** [comment]
No, the plugin does not automatically import your devices. You must identify the devices you want to be included into homebridge.

See item #3, here:

https://github.com/jvmahon/Homebridge-HomeSeer4/wiki

And further details here:

https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file
