### ISSUE TITLE
Adding Virtual device to HS4, add to Homebridge - HB fails on boot with UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by rjameson3** [jvmahon/Homebridge-HomeSeer4#161]
I have a new HomeBridge setup, using JVMahon homebridge-homeseer4 plug-in, added a bunch of devices and working well.  Attempted to add some cloud based devices (Tuya, Globe etc.) and they all crash on boot with Unhandled PromiseRejectionWarning.  Figured if Homeseer plugin is accessing a web based cloud device - perhaps the homebridge did not like it.   I added the Tuya plugin direct to Homebridge and solved that issue at least for Tuya based devices.

I have a Meross powerstrip - only in HomeKit and want to see/control HomeKit devices in Homeseer.   I created the Virtual devices in HS4, get the ref code and add to Homebridge config...restart, again - crashes and it then stalls saying plugin is taking long time to load and preventing homebridge from starting.   When I remove the offending device - homebridge works again.   Tried to add as a switch and lightbulb in homebridge - in case it mattered - both crashed.

Any way to determine why the virtual device is crashing homebridge?  Might also be why my other cloud based HS4 devices are not working.

![image](https://user-images.githubusercontent.com/14798911/144146730-321ad25f-6fd7-4148-b2cd-e7b651363dd1.png)
![image](https://user-images.githubusercontent.com/14798911/144146743-e2147842-6349-4825-b377-192535c85676.png)
![image](https://user-images.githubusercontent.com/14798911/144146751-e46cc6b9-470b-4eea-9c56-705427f1d63d.png)
![image](https://user-images.githubusercontent.com/14798911/144146932-5c8c7fb8-eec6-4f20-87f1-302844cfe577.png)

**Comment by jvmahon** [comment]
I have no idea what your "_bridge" entry is - it is not something supported in the Homebridge-Homeseer4 plugin.

**Comment by rjameson3** [comment]
I have no idea either…I only setup, added info needed, scanned the QR …it may have scanned a few times early on when things were not working, I rescanned into HomeKit…I could remove lines and see what is does.

Sent from Mobile Outlook<https://aka.ms/sdimjr>
________________________________

**Comment by rjameson3** [comment]
Would it happen to be when I put the plug-in in child bridge - I read performance was better suited in that so makes sense the bridge might be that.   Again, was prob early setup issues not seeing results.

Sent from Mobile Outlook<https://aka.ms/sdimjr>
________________________________

**Comment by jvmahon** [comment]
You're right - that gets automatically added when config-ui-x is used to set each plugin in its own bridge, so that shouldn't be the issue. I really have no idea what is going wrong in your setup.  Can you make sure you are using the latest version of the plugin by doing

`````
npm -g update
`````

**Comment by rjameson3** [comment]
After digging further, node.js was not updating (firewall block on my end) – was on v14 – now am current.   No longer a notice of promise rejections being deprecated – but have a new error (still hanging on the virtual device).

![image](https://user-images.githubusercontent.com/14798911/144172789-3d2df462-a4cf-4521-9e7e-1a256662508d.png)

I am still digging....noticed in HS4, the ID now shows a different number that does not match what is in () after the name of the device (shows under Associated Devices).   I changed it now to this new ID in the plugin and it shows up now (no error).   Next step - see if I can take it to the next level and get it to actually do something thru homeseer.

Ron

**Comment by jvmahon** [comment]
Try updating to 1.0.23
`````
npm -g update
`````

**Comment by jvmahon** [comment]
No further comment, so closing this.
