### ISSUE TITLE
Scale is not Celsius or Fahrenheit

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/Homebridge-HomeSeer4#162]
Hi, 
I'm trying to add some KNX temperature devices however this seems to fail.

[12/16/2021, 9:18:49 PM] Initializing platform accessory 'K1 - Sensor K1 - Temperature'...
(node:1464) UnhandledPromiseRejectionWarning: RangeError: Error setting up Temperature Sensor. Scale is not Celsius or Fahrenheit
    at Object.exports.setupSensor (/usr/lib/node_modules/homebridge-homeseer4/lib/Sensor Setup.js:272:12)
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:170:12)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:218:11)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:461:41)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:549:34
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:182:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My config looks like
                {
                    "type": "TemperatureSensor",
                    "name": "K1 - Temp",
                    "minCelsius": -100,
                    "maxCelsius": 100,
                    "ref": 832
                },

And the device status page looks like this:
<img width="888" alt="Screenshot 2021-12-16 at 21 25 53" src="https://user-images.githubusercontent.com/32204682/146444917-ce4512d4-3026-471c-a453-296aa44ed14d.png">

The Status Graph page:
<img width="1023" alt="Screenshot 2021-12-16 at 21 37 21" src="https://user-images.githubusercontent.com/32204682/146445558-7efc1484-031f-43ea-9ccf-d8d5317cd07d.png">
Even if I add a new value range and limit the decimals to 1 it still fails.

Is there a fix or a workaround?

**Comment by AlanSmithe** [comment]
Digging around in the code I see the plugin looks at the status value, in my case that's Dim which I cannot edit. Would it be an option to also look at the device string? If that contains a "F" or a "C"?

**Comment by jvmahon** [comment]
Zoom out a bit on your browser window until you see the control ...
![image](https://user-images.githubusercontent.com/15061942/146455115-4e23b925-3de5-44f4-a493-a0c9649448d0.png)

You then get the range options:
![image](https://user-images.githubusercontent.com/15061942/146455322-0fbe8f6f-5681-4231-9789-e52848b2bd97.png)

I think you can then enter " F" or " C"  as a suffix
There is also a code - you can use, I think its something like @S@  which will insert the appropriate symbol as used by your system.  The setup for your temperature sensors should have included the @S@, but ...

**Comment by jvmahon** [comment]
Another workaround, set up your device using the temperatureUnit "F" or "C", like ...

{
"type": "TemperatureSensor",
"name": "K1 - Temp",
"minCelsius": -100,
"maxCelsius": 100,
"ref": 832,
"temperatureUnit":"F"
},

**Comment by AlanSmithe** [comment]
> I think you can then enter " F" or " C" as a suffix
I tried that but that didn't work.

> Another workaround, set up your device using the temperatureUnit "F" or "C", like ...
Yes this did the trick. I tried searching this in the config folder but I couldn't find an example of it. 
Thank you very much
