### ISSUE TITLE
basic setup issue

### ISSUE THREAD

**Issue by rohitand** [jvmahon/Homebridge-HomeSeer4#164]
I followed all the instructions and checked the config file. I am able to see the configured devices in Home Accessories but I cannot turn them On/Off. Kept the devices to a min . Here is the config file, changed username / pwd to XX.... Id's are correct, ASCII port is also confirmed. 
{
    "bridge": {
        "name": "Homebridge E6CA",
        "username": "XXXXX",
        "port": 51959,
        "pin": "XXXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "HomeSeer",
            "host": "http://homeseer.local",
            "ASCIIport": 11000,
            "login": "XXXXXX",
            "password": "XXXXX",
            "Lightbulbs": [
                185
            ],
            "Outlets": [
                360
            ],
            "platform": "HomeSeer"
        }
    ]
}

**Comment by jvmahon** [comment]
Did you restart HomeSeer after turning on the ASCII port?

What type of devices (Z-Wave? Virtual?).

**Comment by rohitand** [comment]
sorry, I missed that step about restarting earlier.  Both the devices are working now,  this is pretty awesome, Thank you!
