### ISSUE TITLE
Device Field Descriptions in UI not showing

### ISSUE THREAD

**Issue by scoutbeer** [jvmahon/Homebridge-HomeSeer4#166]
Platform: **_Hoobs on Rasp Pi_**

Plugin Version:
hoobs@hoobs:~ $ npm -g list --depth=0
**_/usr/lib
└── npm@6.14.15_**

Node Version:
hoobs@hoobs:~ $ node -v
**_v14.18.3_**

Hi James,
I have the plugin working with my first device after many attempts of guessing what I needed to enter where in the UI field as the descriptors are not showing. (See screenshots).
I'm wondering how I can get the field descriptions to properly show up in the UI.  I've tried doing Hub Settings -> Cache -> Clear Cache and uninstalling and reinstalling the plugin but neither has resolved the issue.

Thank you!

![HomeseerPluginUI-01](https://user-images.githubusercontent.com/87205579/149169744-9723c3df-d77a-4f34-9220-e0cf37fe740a.jpg)
![HomeseerPluginUI-02](https://user-images.githubusercontent.com/87205579/149169760-7dbe0e98-5528-4e50-97b8-68cd56073360.jpg)

**Comment by jvmahon** [comment]
That screenshot is very odd - never heard of that happening to 
anybody before.

What browser are you using to access the UI?

If not Chrome, try the latest version of Chrome which is what I use and the UI works fine.

**Comment by scoutbeer** [comment]
Chrome (on a Mac)
Version 97.0.4692.71

**Comment by scoutbeer** [comment]
I just tried from a Windows machine as well using Chrome Version 97.0.4692.71.
The issue persists.

**Comment by jvmahon** [comment]
Sorry, but I have no idea. It certainly seems like its a browser rendering issue. I can only suggest you try a different browser.

**Comment by scoutbeer** [comment]
It is bizarre.  I just tried it across Safari and Firefox as well.  Same result.
Any chance you can share some screenshots of what it **_should_** look like?

**Comment by jvmahon** [comment]
For each of the categories under "Simple Device", there should be a list of boxes where you can insert the "reference ID" of the device.

![image](https://user-images.githubusercontent.com/15061942/149217122-428e5406-fdba-4594-b1df-d5886ecab6b6.png)

**Comment by jvmahon** [comment]
I don't know if it matters, but I'm using . . .

Node v16.3.1  (but 14.8 should work)
homebridge-config-ui-x v4.41.5
homebridge-homeseer4 v1.0.24
homebridge 1.3.9  (HAP v0.9.8)

**Comment by scoutbeer** [comment]
Maybe this is a Hoobs issue.  I'll open a ticket with them as well and in the mean time I'll spin up a Homebridge VM and see if i can get it working there.

**Comment by jvmahon** [comment]
As a suggestion - If you have a windows machine, I'd say the simplest way is to install node and homebridge there - that's what I'm using and it clearly works. You should then be able to create your configuration of devices in Windows, get it all working, then I think you can do a backup of Homebridge using the "Backup / Restore" function from the Homebridge "3 dots" menu and restore to Hoobs when you get the Hoobs issue figured out.

![image](https://user-images.githubusercontent.com/15061942/149228427-c765f095-b982-4b1c-b764-54c8866c0394.png)

**Comment by jvmahon** [comment]
I'll close this out for now. Re-open if Hoobs can't help you fix.

**Comment by scoutbeer** [comment]
Hi @jvmahon.  The ticket I opened with Hoobs finally got a reply.  See here: https://github.com/hoobs-org/HOOBS/issues/1777#issuecomment-1016886282

**Comment by jvmahon** [comment]
Great. Sounds like its a HOOBS / Config-UI-X fix then.  Good luck. Hope you enjoy the plugin once you get this fix lined up. I think you'll find it really useful!
