### ISSUE TITLE
Homeseer web control ssl 

### ISSUE THREAD

**Issue by funsurfer558** [jvmahon/Homebridge-HomeSeer4#167]
Is it possible to use your plugin when the homeseer web control is ssl enabled? I have your plugin setup on hoobs on a raspberry pi but the plugin won't connect when ssl is enabled on homeseer. 

I am using a self signed certificate named as the hostname of the homeseer server. I exported the certificate onto the raspberry pi and added it to the trusted certificate store. I also added the hostname and local ip of the homeseer server onto the raspberry pi. I am able to validate that the certificate is installed correctly by bringing up a chrome browser on the raspberry pi and connect to the homeseer web control with no name resolving or certificate issues and login.

**Comment by jvmahon** [comment]
I don't know.  When you tried it, did you specify port 443 as part of the host parameter instead of port 80?  I think 443 is usually used for ssl?  Other than that, I have no suggestions for you to try.
