### ISSUE TITLE
Homeseer + Wyze products

### ISSUE THREAD

**Issue by SteveQ2** [jvmahon/Homebridge-HomeSeer4#168]
The Homeseer4 plugin for HomeBridge works great. But I am extremely frustrated with the wyze plugin (rmcob v0.5.9).  I am able to configure and use the wyze plugin and the Homeseer4 plugin as Homebridge child devices when I first install hb-service. This initial setup is very time consuming especially when it comes to setting up the devices on iPhone! Once everything is setup, it works very well.  However, after any change to the HomeBridge config file, hb-service crashes.  The only way I can get it running again is to Uninstall and Reinstall hb-service. This is very painful.  So when I add a new device to your Homeseer4 plugin, everything stops working.   I know that the Wyze plugin is causing the problem (the log errors say so).   

Is there anything you can do? I would really like to continue using  Homebridge and the Homeseer4 plugin, but there is not much point to continue if I can't get my Wyze devices  integrated with my other Homeseer Stuff.

I am running Homebridge on Windows 10.

Steve Q

**Comment by jvmahon** [comment]
I'd try setting up each plugin as a separate "bridge" on homebridge. To do this . . .

Are you using config-ui-x?  If not, first install that. https://www.npmjs.com/package/homebridge-config-ui-x

Then, from the config-ui-x interface, configure each plugin as its own "bridge". This may help isolate the plugins from each other. You will have to pair each "bridged" plugins with  your phone again after setting them up on a bridge and may have to reset which "room" each device is in on your iOS device. Its worth doing as using separate bridges for each plugin generally makes homebridge faster and more reliable.

To configure each as a separate bridge:

I. Go to the "plugins" page of the config-ui-x interface

![image](https://user-images.githubusercontent.com/15061942/158026292-f9d1a884-da4b-4a67-8728-79cba1d037a9.png)


II. Then select the Tools icon (1), followed by the "Bridge Settings" option (2)

![image](https://user-images.githubusercontent.com/15061942/158026269-e6c0f535-3c8f-49a4-9030-cc32d6c5685c.png)

III.  Then turn on Child Bridge for the plugin

![image](https://user-images.githubusercontent.com/15061942/158026312-1b7961d1-9d23-4f09-8a0c-d5a7a2fac2c3.png)

IV.  Do this for each of your plugins

V.  Restart Homebridge

VI. Go back the Settings for each plugin (Step II.2, above).  Then Pair each bridged plugin to you iOS device.

**Comment by jvmahon** [comment]
No further response, so I'm closing this issue.
