### ISSUE TITLE
Lights 100% in homeseer4 

### ISSUE THREAD

**Issue by thetaz001** [jvmahon/Homebridge-HomeSeer4#170]
SO i am NOT using alexa, i am using homebridge -homeseer4 to Siri..
I have homeseer runing, and has been for years..
recently, i noticed that when i turn on a light bulb at the switch, In Homeseer, or using a HSTOUCH screen, the light goes to 100, then down to 99
Homebridge-Homeseer4 comes back and says this
[5/9/2022, 11:14:01 AM] [HomeSeer] HomeSeer device: 90: new value 100, had old value 0
[5/9/2022, 11:14:01 AM] [homebridge-homeseer4] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 100 exceeded maximum of 99. See https://git.io/JtMGR for more info.
[5/9/2022, 11:14:02 AM] [HomeSeer] HomeSeer device: 90: new value 99, had old value 100

If i turn off the homeseer-homebridge device, and break that connection, my lights go to 100 just like they should.
for some reason the homebridge-homeseer4 plug in is NOT allowing a light to be 100% its knocking it down to 99.
can you please advise if there was a fix for this.. its driving me crazy on my hs touch screens..
FYI IN my HOME app, it does in fact show 100%

Also be aware, just a bullet from above, IF I UNPLUG my Homeseer4 homebridge device, and turn on and off lights in homeseer the light goes on to 100, and off to 0, it appears the Homebridge-Homeseer4, is Knocking the number value down from 100 to 99 as seen in the log of homebridge as a illegal value?!

**Comment by jvmahon** [comment]
Z-wave lights only have the values 0 - 99 in HomeSeer. The value 100 doesn't exist for z-wave lights in HomeSeer  (which follows from the odd fact that the Z-wave standards only recognize 0 - 99 for multilevel devices -- seems like a bad engineering decision, but that's what's in the standard)

So if you set a light in your iOS Home app to 100%, there is code in the plugin that should translate this to a 99 for z-wave devices which will then cause the light to get set in HomeSeer to 99 while still indicating 100% in iOS Home. If this is what you are seeing, that is intentional.

**Comment by thetaz001** [comment]
I'm sorry i should have added I am using Insteon, NO z-wave lights at all..
Insteon devices DO allow for 100% and it screws up with my HSTOUCH screens, when it goes down to 99% when im using a toggle on/off button, and it goes on, down to 99% instead of staying at 100%, :(

**Comment by jvmahon** [comment]
The original code was written around Z-wave, but there is a work around for this which involves using the "levels" configuration parameter to change the allowed levels to 100.

The levels parameter is referenced in the wiki, here:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

But its a bit tricky.  If you want, post your config.json and let me know which is the insteon device, and I'll show you how to do it for one of the lights.

**Comment by jvmahon** [comment]
Or give me through the weekend and I'll see if I can implement a fix where I only use the "99" level setting for z-wave and use 100 levels otherwise.

**Comment by thetaz001** [comment]
> Or give me through the weekend and I'll see if I can implement a fix where I only use the "99" level setting for z-wave and use 100 levels otherwise.

PLease, I'm in no rush, so IF it's not a BIG deal and you can do something plugin wide, that would be amazing
i do have a ton of lights i would have to add this too, if its per device..
i'm sure i could use Notepad++ or something to modify, BUT if you can do something globally, i'd be happy to test 
thanks so much
let me know

**Comment by jvmahon** [comment]
Are you using config-ui-x (I assume so - if not, you should be)

First, be sure you're running at least Version 16 of node.  If you aren't, you'll need to update that

Then . . .

From the config-ui-x interface , go to your plugins settings, then for the Homeseer4 plugin, choose the tool, then "install Previous Version"

![image](https://user-images.githubusercontent.com/15061942/167715170-0070f89d-0ca2-46e0-9c49-3d95c1a61b1b.png)


Then from the Previous Version menu, select the 1.0.25-beta.2

![image](https://user-images.githubusercontent.com/15061942/167715266-3bdb5158-56d0-4dcc-8d64-afaef72af854.png)

Give it a try and see if that fixes it for you.

**Comment by jvmahon** [comment]
If you do need to update node, you can do it from a command line using

(for raspberry pi) ...
`````
sudo hb-service update-node 18.1.0
`````

**Comment by jvmahon** [comment]
This version is part of a much larger update to the code (I've been updating all the code to incorporate more recent improvements to javascript).  

I don't use HomeSeer anymore, so this isn't well tested. But if it fails, you can always revert back to the prior plugin version (or report the error messages and I'll try to get out some quick fixes as best I can).

**Comment by thetaz001** [comment]
> If you do need to update node, you can do it from a command line using
> 
> (for raspberry pi) ...
> 
> ```
> sudo hb-service update-node 18.1.0
> ```

I'm currently, running 14.15.4, 
should i go to 16 or 18, 
16 is supposed to be valid till april 2024, 18 is only valid till oct 2022 BUT is crossed out

**Comment by thetaz001** [comment]
> If you do need to update node, you can do it from a command line using
> 
> (for raspberry pi) ...
> 
> ```
> sudo hb-service update-node 18.1.0
> ```

I tried your command as well as 
sudo hb-service update-node
and when i run it i get a error
 Failed to update Node.js: Command failed: curl -sL https://deb.nodesource.com/setup_16.x | bash -

please advise..

**Comment by thetaz001** [comment]
> Are you using config-ui-x (I assume so - if not, you should be)
Yes i am
 
> First, be sure you're running at least Version 16 of node. If you aren't, you'll need to update that
I am now.


> Then . . .
> 
> From the config-ui-x interface , go to your plugins settings, then for the Homeseer4 plugin, choose the tool, then "install Previous Version"
> 
> ![image](https://user-images.githubusercontent.com/15061942/167715170-0070f89d-0ca2-46e0-9c49-3d95c1a61b1b.png)
> 
> Then from the Previous Version menu, select the 1.0.25-beta.2
> 
> ![image](https://user-images.githubusercontent.com/15061942/167715266-3bdb5158-56d0-4dcc-8d64-afaef72af854.png)
> 
> Give it a try and see if that fixes it for you.
Testing beta version now

**Comment by thetaz001** [comment]
OMG YES!
THANK YOU A MILLION TIMES!
if there is a place i can send Money to Assist in further development of this!
and to thank you for the unbelievable quick resolve to this!!
I WILL!! IN A HEART BEAT!

thank you

**Comment by jvmahon** [comment]
So then I assume its all working?

If so, I'll soon release as a "regular" version - hopefully, I didn't mess up anything for the "regular" z-wave folks!

**Comment by thetaz001** [comment]
OMG it sure is!
thank you!
and yeah i hope not!
thank you again!! for the super fast! quick change to adjust for it, that was awesome! and BEYOND apprecaited
