### ISSUE TITLE
HomeKit V2 Fan

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#175]
In iOS 16 Beta 1, unable to change fan icons. Apparently V1 fans icons cannot be changed while v2 homekit fan icons can. Config.json uses simple setup for fans, anyway to specify homekit v2 fan status so the icons can be changed?

**Comment by jvmahon** [comment]
The plugin code uses Fanv2, so I'm not sure what the issue could be.  Presumably, a iOS beta issue.
