### ISSUE TITLE
Unable to lock door from HomeKit

### ISSUE THREAD

**Issue by tundrageek-AK** [jvmahon/Homebridge-HomeSeer4#176]
Somewhere after the last updates (unsure if it was a plugin update, homebridge update, or homeseer update), I lost the ability to lock my Kwikset z-wave lock through HomeKit and this plug-in. I can unlock the lock just fine, but when I attempt to lock it, I get the following error in the HomeKit log:

[6/14/2022, 4:07:13 PM] [homebridge-homeseer4] This plugin threw an error from the characteristic 'Lock Target State': Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'lockValue'). See https://homebridge.io/w/JtMGR for more info.

Plug-in version: 1.0.29
Homebridge version: 1.4.1
Node.js Version: v16.15.1
HomeSeer version: 4.2.12.0

**Comment by jvmahon** [comment]
Sorry, no idea on tis one.  I don't think its the plugin - maybe something in homebridge itself?
Could you try updating nodejs to 18.3?

**Comment by jvmahon** [comment]
Try updating to the 1.0.30 version that I just published and let me know if that works.

**Comment by tundrageek-AK** [comment]
The plugin update seems to have done it for me. Thank you!
