### ISSUE TITLE
Issue on Shower

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/Homebridge-HomeSeer4#183]
I have an issue with using the following entry. The “valveType” which I need setting to Shower doesn’t seem to follow and is constantly set to a tap/faucet. 

{
	"type": "Valve",
	"name":null,
	"ref": 0,
	"uuid_base": 0,
	"batteryRef": 0,
	"batteryThreshold": 25,
	"valveType": 2,
	"openValve": 255,
	"closeValve": 0,
	"useTimer": false,
	"minTime": 30
}

Valve type. 0 = Generic, 1 = Irrigation, 2 = Shower Head, 3 = Faucet.

What am I doing wrong?

Thanks

Darren

**Comment by jvmahon** [comment]
I don't think you are doing anything wrong.

The simple answer is that I can't get the code to show anything other than the faucet.

From what I can tell, the code is correct, it is processing the valveType number, and it is passing it to the homebridge / hap-nodejs software correctly. It just doesn't make a difference what that valueType is.

I think this may be an iOS Home limitation.

I'm copying  @dibble9012 who has recently contributed some code on valves -- @dibble9012 - when you use different valve types, do you see any difference in the icon shown in the iOS Home App?

If you do, can you share some example configuration entries.

**Comment by dibble9012** [comment]
I’ll look into it later today or tomorrow. I have only been able to get a valve and sprinkler to show up in iOS no matter what I set. I agree. I think it is an iOS limitation or bug.

**Comment by darrenmcuk** [comment]
Sometimes…so sprinkler to tap/faucet yes but not shower head.

**Comment by dibble9012** [comment]
Correct

**Comment by jvmahon** [comment]
Thanks @dibble9012  @darrenmcuk . 

So it looks like there is nothing that I can "fix" here so I'm closing this as an Issue.

I also tried the "Eve" app. rather than iOS Home and it seems to have the same issue.

**Comment by dibble9012** [comment]
After a little troubleshooting on my system, this plugin does correctly set the valve type, HomeKit/iOS/macOS do not correctly reflect the icon at least in the latest public releases of those OSs. iOS 16 beta and the latest beta of macOS do show it correctly (screenshot attached).

![IMG_1975](https://user-images.githubusercontent.com/6963660/182731324-6c577062-1117-4a9c-99f2-317bb995451c.PNG)
.

**Comment by darrenmcuk** [comment]
Well that’s excellent news thanks
