### ISSUE TITLE
Homeseer

### ISSUE THREAD

**Issue by HOMESEERDUDE** [jvmahon/Homebridge-HomeSeer4#184]
I am looking for a better dashboard for my iPad. I am using homeseer and hs touch. I heard homekit is coming out with a cool interface. I am thinking about getting hoobs but want to know what to expect with the homeseer plugin?

**Comment by jvmahon** [comment]
I think you'll find its quite full-function and makes a great interface.
One thing - if you don't own an Apple TV, you'll want to get one (Amazon has them on sale: https://www.amazon.com/dp/B0933D8TNB?ref=nb_sb_ss_w_as-reorder-t1_ypp_rep_k0_1_10&amp&crid=21O3J5NS6Y66S&amp&sprefix=apple+tv+4). The Apple TV is necessary as a bridge in case you want to access your devices remotely (i.e., when you aren't on the same WiFi as the devices).  I think a HomePod Mini also works for this purpose.

I've never used Hoobs. Instead, I use a Raspberry Pi and recommend that if you can find one (very hard to find stock).

**Comment by HOMESEERDUDE** [comment]
I have an apple tv. I think that is what got me interested in upgrading my
ui. Do you have pictures or examples of what you have been able to do with
homebridge?  What do you use for your dashboard?   The hs touch is a little
weak.

**Comment by HOMESEERDUDE** [comment]
What do you use for your dashboard?  I like the action tiles but it doesnt
work with insteon.  In fact, nothing wants to play nicely with insteon
except homebridge.  Any help is much appreciated .

Saul
