### ISSUE TITLE
homeseer4 Not running

### ISSUE THREAD

**Issue by thetaz001** [jvmahon/Homebridge-HomeSeer4#185]
Does anyone know if there is a current issue with v1.0.33
All the sudden my homebridge service goes from starting to not running constantly
i came to find out it was the Homeseer4 plugin causing the error below.
i havent changed/added removed anything
I'm getting this error
[9/4/2022, 11:09:55 AM] TypeError: Cannot read properties of undefined (reading 'status')
    at /usr/lib/node_modules/homebridge-homeseer4/index.js:123:70
    at Array.forEach (<anonymous>)
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:119:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Any help would be super apprecaited
Thanks

**Comment by jvmahon** [comment]
I'm not aware of any issues and other seem to be using that version without problem.

Was it working previously?
Did you add any new devices?

The only possibility I see is that there is an incorrect accessory reference number added when you configured the plugin.

I just added some additional checking when an incorrect reference number is used. Maybe it will help.

Upgrade to 1.0.34 and try again.

**Comment by thetaz001** [comment]
Thanks so MUCH!! For still supporting this plug in I know you mention you don't use homeseer any longer!
First off If you take donations I would be happy to donate!
And two, in answer to your questions.
This has been working for months, I haven't added or changed ANY devices in months..
And whatever you did, NOW allows it to start successfully!
Everything is working perfect again!!

Thank you!!

Fred

**Comment by jvmahon** [comment]
You're welcome.

I don't (directly) take donations. Instead, I ask people to take whatever they would have given and give it as a donation. See post #19 here: https://forums.homeseer.com/forum/homeseer-products-services/general-discussion-area/1544201-homekit-plugin-homebridge-homeseer4?p=1564400#post1564400

**Comment by thetaz001** [comment]
Awesome!
Thank you so much!
I Will do that this weekend!

Thank you again!

Fred
