### ISSUE TITLE
Lightbulbs onValue not working.

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#19]
Maybe I'm being premature in trying to use this!  HAHA!

<pre>
config.json error: property: onValue is not a valid property for item named: Lamp of type: BinaryLight.
Valid Properties for this type are: type,name,ref,uuid_base,interface_name.
    at Object.hasValidProperties (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\DeviceDefaults.js:550:11)
    at Object.checkConfig (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\HomeSeerUtilities.js:320:18)
    at C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:179:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
</pre>

**Comment by jvmahon** [comment]
As a "fix" in this updated version, I've tried to simplyify the config.json by removing parameters which the plugin could figure out from HomeSeer itself. In this case, the plugin should be able to figure out the "on" and "off" values without you specifying them. It does this by checking the "Control Use" field which comes from the Status Graphics page of the device. In other words, you should be able to delete the "onValue" and "offValue" from your config.json. Please give that a try and let me know if that works for you.

This being said, I'll go back and modify the code to not throw an error on these values (to make it easier for users to transition from the old plugin to this new one).

**Comment by meluvalli** [comment]
Got it and like it!  :)  I actually removed it and got passed the error, but now I have a new one.  So, not sure if I need to open a new issue for it or not...  But as seeing that you will be updating it to not throw the error, it'll probably fix my other issue as well :)

The other issue is with Contact Sensors.  I use Vista Alarm plugin and the contact sensors are pre-set.   So, it's throwing a similar error as the above one except, it doesn't appear the plug-in can even detect the "Closed" value.

<pre>[12/17/2019, 10:48:02 AM] [HomeSeer] Initializing platform accessory '13 - Office Window 1'...
(node:11596) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'closedValue' of undefined
    at Object.exports.setupServices (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\HomeKitDeviceSetup.js:394:55)
    at HomeSeerAccessory.getServices (C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:397:11)
    at Server._createAccessory (C:\HomeBridge\node_modules\homebridge\lib\server.js:427:36)
    at Server.<anonymous> (C:\HomeBridge\node_modules\homebridge\lib\server.js:413:32)
    at C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:16:19
    at C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:353:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>



In HomeSeer it's setup like this:
![ContactSensor](https://user-images.githubusercontent.com/8729476/71017681-8d03d300-20bc-11ea-82fd-245f978d2f31.png)

**Comment by jvmahon** [comment]
Thanks. I'll try to look at this today.

**Comment by meluvalli** [comment]
Awesome.  Thanks.  I'll keep an eye out for updates.  Also, it's throwing that same error on my switches as well. (Device Type: Switches)

**Comment by jvmahon** [comment]
An updated has been posted which (hopefully) will address the onValue problem (but I will do some more testing tonight).

execute: 
`````
npm -g update
`````

As for the Contact Sensors, by default, "0" is the Off value, everything else is a trigger.
You'll need to change this by an array of Off values for your sensor - including everything that isn't a trigger ("on") value. In your case, I think the following would work for a device with the HomeSeer reference of 13:

`````
{    "type":"ContactSensor",    "ref":13,    "offValues":  [0, 1, 2, 3, 5, 103]     }
`````

**Comment by meluvalli** [comment]
Yay! Contact Sensors now work!  

However, Switches still don't :(

<pre>[12/17/2019, 12:15:48 PM] [HomeSeer] Initializing platform accessory 'Switch'...
(node:9608) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'closedValue' of undefined
    at Object.exports.setupServices (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\HomeKitDeviceSetup.js:394:55)
    at HomeSeerAccessory.getServices (C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:398:11)
    at Server._createAccessory (C:\HomeBridge\node_modules\homebridge\lib\server.js:427:36)
    at Server.<anonymous> (C:\HomeBridge\node_modules\homebridge\lib\server.js:413:32)
    at C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:16:19
    at C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:354:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>

I tried specifiying "closedValues" the same way as contact sensors, but then it yells at me and says closedValues isn't an option for type switch!

**Comment by meluvalli** [comment]
Also, same exact error on Events :(

**Comment by jvmahon** [comment]
For Switches, look at the file config.complex.json which is found here: https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config

This will show you the valid parameters for a device type.

For a switch, you should normally not have to specify any "on" or "off" parameters for the new plugin as it should be able to get them from HomeSeer (as long as your StatusGraphics page specifies the proper Control Use). In the rare case where you do need something "customized", you use the parameters "onValue" and "offValue". As an example . . .

			{"type":"Switch",      "name":"Hallway",  	"ref":620,  "onValue":255,  "offValue":0	},

**Comment by jvmahon** [comment]
Also see the Wiki here:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

**Comment by meluvalli** [comment]
That's exactly what I already have...
<pre>
				{"type":"Switch",				"name":"Switch", 					"ref":37,			"offValue":"0",			"onValue":"100"},
</pre>

**Comment by jvmahon** [comment]
can you post your config.json file for me.

**Comment by meluvalli** [comment]
Ok, well, after you asked for my config, I tried to make it simpler and remove a lot of duplicated device types...  In doing so, I came up with a very basic file with only 6 things in it :)....  Then I tested that config file before sending to you and it works!   Switches and Events that is!  

So, I started comparing what was different..   And I forgot one device type....  "GarageDoorOpener"...  When I through this in the config file, it killed it and started getting errors about closed status on events and on switches...

I'm thinking the error is actually garagedooropener that is causing it!  

<pre>
				{"type":"GarageDoorOpener",		"name":"My Garage", 					"ref":391,			"openValue":"100"},
</pre>

The thing is, I have the GarageDoorOpener as a virtual device in HomeSeer.   It actually kicks off an event in HomeSeer for when I arrive home.   I have it set this way because I use CarPlay in my vehicle and apple created a new feature on screen for your garage opener when you arrive home.  So to make it show up on CarPlay this way (In Maps), it has to be a "Garage Door" device.  Then when you click it, it's actually triggering an event on the backend.

**Comment by jvmahon** [comment]
That's quite useful information -  the GarageDoorOpener is one of the "least tested" parts of this beta.  I''m pretty sure I know what is wrong, but just to confirm - can you post a copy of the "status graphics" page for your virtual device and of your config.json setting for the Garage Door Opener.  I forgot that I hard-coded some numeric values into the beta plugin so it is currently ignoring some of the config.json settings,  so that may be the problem.

**Comment by jvmahon** [comment]
I also did a small update to the GarageDoorOpener code so do another . . .

`````
npm -g update
`````

**Comment by meluvalli** [comment]
Thanks!  I still get the error about Closed value on it though :(

I have tried
<pre>
{"type":"GarageDoorOpener",		"name":"Arrive Home", 					"ref":391},
</pre>

and
<pre>
{"type":"GarageDoorOpener",		"name":"Arrive Home", 					"ref":391,			"closedValue":"0", "openValue":"100"},
</pre>

Am I doing it wrong?

**Comment by meluvalli** [comment]
Sorry, just noticed you asked for status page.  Reminder, this is a virtual garage switch I have.  It's just a basic ON/OFF switch in my case.

![Garage](https://user-images.githubusercontent.com/8729476/71029384-dfe98480-20d4-11ea-89f2-33904200585e.png)

**Comment by jvmahon** [comment]
Garage door openers have 5 states:  Closed, Closing, Stopped, Opening, and Open.
The "default" values for these (as defined in the Z-Wave specifications) are 0, 252, 253, 254, 255
If you use different values, you should specify them all like:

`````
{
	"type": "GarageDoorOpener",
	"ref": 1234,			
	"closedValue": 0,	
	"closingValue": 252,	
	"stoppedValue": 253,	
	"openingValue": 254, 
	"openValue": 255
}
`````

In https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config there is a file "All Configuration Parameters.js" which, though not well documented, gives a bit more insight into setting configuration values.

**Comment by meluvalli** [comment]
Hmm.  Ok, so maybe create fake closingvalue, stoppedvalue, and openingvalue?

**Comment by jvmahon** [comment]
Give me a few minutes while I check the code - I'm trying to get it to work the way you set it up.

**Comment by jvmahon** [comment]
Its an error in the code. I think I can fix it tonight or tomorrow.

**Comment by meluvalli** [comment]
Ok.  Sweet!  Thanks again!  I really appreciate it!!!!

**Comment by meluvalli** [comment]
Ok, I know you said you would work on it this weekend, but thought I would take a look on my end as well...

Here is what I have found...

I looked at your code on v0.0.12..  I saw that I was using values that assumed I had a Z-Wave garage controller, but I don't.  My garage controller as you know is a virtual switch..

So, I updated my values based on your code to the below:
<pre>
				{
					"type": "GarageDoorOpener",
					"name":"Garage Opener.Home",
					"ref": 391,			
					"closedValue": 0,	
					"closingValue": 2,	
					"stoppedValue": 3,	
					"openingValue": 1, 
					"openValue": 100
				},
</pre>

This seems to get me MUCH further!  However, there are still issues with it.  

Now when I control the device from HomeKit, HomeBridge crashes complaining about "LockValue"..
<pre>
[12/20/2019, 8:23:33 AM] TypeError: Cannot read property 'lockValue' of undefined
    at Characteristic.TargetDoorState.<anonymous> (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\HomeKitDeviceSetup.js:474:49)
    at Characteristic.TargetDoorState.emit (events.js:305:20)
    at Characteristic.TargetDoorState.Characteristic.setValue (C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:321:10)
    at Bridge.<anonymous> (C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:822:8)
    at HAPServer.emit (events.js:305:20)
    at HAPServer._handleCharacteristics (C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:974:10)
    at HAPServer.<anonymous> (C:\HomeBridge\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:305:20)
</pre>

Not sure if this helps you or not, but thought  I would try!

**Comment by jvmahon** [comment]
No worries. I found the problem, I just have to test it a bit before posting the fix.

**Comment by jvmahon** [comment]
I think this is now fixed. Try again and let me know. Version 0.0.14

**Comment by meluvalli** [comment]
Confirmed working in v0.0.14!  THANK YOU!!!!
