### ISSUE TITLE
arduino device status not updating in homebridge

### ISSUE THREAD

**Issue by Duc1198** [jvmahon/Homebridge-HomeSeer4#192]
Hi jvmahon

I'm running the homeseer arduino plugin. 

I can't seem to get the status to update correctly in homebridge. I can see the homebridge logs record the correct status change but the icon will not show device is on.
If I try and turn device on in home up I have to turn on twice to get it to stick.

{
"type": "LightSwitch",
"name": "Backyard Garden Lights",
"ref": 4223,
"onValue": 0,
"offValue": 1
}
![2022-11-06_8-01-26](https://user-images.githubusercontent.com/71119249/200142177-5d0deece-3305-49c5-b91f-686c616345c7.jpg)

_Originally posted by @Duc1198 in https://github.com/jvmahon/Homebridge-HomeSeer4/issues/123#issuecomment-1304646137_

**Comment by jvmahon** [comment]
Sorry but I have no idea how the Arduino plugin works.

My Homebridge plugin was originally designed around Z-Wave devices and their behavior, but it has been flexible enough that it can work with other devices. Unfortunately, without having these other devices myself, I can't test them or do much to fix when there is problems.
