### ISSUE TITLE
[HomeSeer] Child bridge process ended

### ISSUE THREAD

**Issue by jordanhomeseer** [jvmahon/Homebridge-HomeSeer4#193]
I can't get it back up.  any advice?

**Comment by jvmahon** [comment]
Were you able to solve it on your own?

Has this ever worked for you?

Its a total cliché,  but have you tried turning it on and off again (reboot homeseer then restart homebridge)?

**Comment by jordanhomeseer** [comment]
I did. I accidentally typed in a switch code from hs4 2 times and it was in
an infinite loop
