### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by jordanhomeseer** [jvmahon/Homebridge-HomeSeer4#194]
Hombridge will not let me connect locally.  my static ip is red

**Comment by jordanhomeseer** [comment]
This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

**Comment by jvmahon** [comment]
I thik

**Comment by jordanhomeseer** [comment]
How do you get cameras from hs into homebridge?

**Comment by jvmahon** [comment]
You can't do it through this plugin. Its far beyond my ability to program.

There are other homebridge plugins available that might work depending on your camera. You have to search at

www.npmjs.org

Try searching  for "homebridge camera"

I've personally never had much luck setting those up.

**Comment by jordanhomeseer** [comment]
Thank you for clarification. The plugin camera ui works but slows down
homebridge and I get errors. I guess I will try scrypted.
