### ISSUE TITLE
Naming Switches

### ISSUE THREAD

**Issue by broberts01** [jvmahon/Homebridge-HomeSeer4#197]
Perhaps this is more of a question or feature request.  How can I go about naming the devices in the config.json?  In the old version I used to be able to do so:
    {"name":"Dining Main Pots", "ref":523 }
but now it's
  "Lightbulbs": [523]

While it correctly pulls the name from HS, these needs editing as the name prepends the room and takes the name from the child (which I name with the type "D" = "Dimmer" so I can tell what to associate in scripts). e.g.
   Dining Dining Main Pots D --> Dining Main Pots
I've 50 switches which need to be pulled into Home.app on 3 iOS/iPadOS devices.

Am I missing something?

**Comment by jvmahon** [comment]
You should also be able to use the "old" way of doing things.
