### ISSUE TITLE
Thermostat stuck in Celsius

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#20]
Can't change to Fahrenheit per log...
<pre>
[12/17/2019, 2:57:53 PM] [HomeSeer] *Warning * -  Changing Hardware Display Units from iPhone Home Does Nothing!. Change must be made to HomeSeer config.json file to have effect
</pre>

However, Configuration file isn't setup to allow changing this!
<pre>
{
	"type": "Thermostat",
	"name":null,
	"ref": 0,					// Set to HomeSeer device reporting the current temperature.
	"uuid_base": 0,
	"batteryRef": 0,
	"batteryThreshold": 25,
	"controlRef": 0,			// Set to HomeSeer device by which you select the Off / Heat / Cool / Auto state.
	"stateRef": 0,				// Set to HomeSeer device reporting the actually running state (Off / Heat / Cool). Sometimes this is the same as controlRef!
	"heatingSetpointRef": 0,	// Either "heatingSetpointRef" or "coolingSetpointRef" must be set (usually both are!)
	"coolingSetpointRef": 0,	// Either "heatingSetpointRef" or "coolingSetpointRef" must be set (usually both are!)
	"humidityRef": 0,			// optional. Set to HomeSeer device that provides a humidity report.
	"humidityTargetRef": 0		// optional. Set to HomeSeer device that allows you to set humidity setpoint.
},
</pre>

**Comment by jvmahon** [comment]
It used to be that you had to set the temperature unit (Fahrenheit or Celsius) using the parameter:
"temperatureUnit":"F",  or "temperatureUnit":"C"

The updated plugin no longer requires this and it should be able to "learn" the proper temperatureUnit from HomeSeer. So you should be able to just delete any "temperatureUnit" parameters from your config.json file.

The actual Temperature Unit used in the iPhone's Home app is set in the iPhone's "General" settings under the "Language & Region" setting.  I have no idea why the iPhone Home app "seems" to allow selection of Celsius or Fahrenheit given that the "real" control is in the "Language & Region" settings.

On the HomeSeer side, the temperature unit is set on the [Toos] -> [Setup] -> [General] page.

If that isn't working, let me know.

**Comment by jvmahon** [comment]
But perhaps more relevant is that you shouldn't have to set any of the Thermostat parameters any more. You just need to specify the Root device. See the explanation here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

And look at the new config.json file here: https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config

In particular, see the sample config.simple.json file.

**Comment by meluvalli** [comment]
Got it.  Very good.  The temperature is displaying correctly, just when you click settings on the device it says it's set for Celsius.  (Even though it's showing the correct temperature in Fahrenheit).  So, I figured maybe this was something that could be fixed, but maybe not...  Maybe it's an iOS issue?

**Comment by jvmahon** [comment]
I will change the error message to be clearer.

**Comment by meluvalli** [comment]
So, just to confirm, the feature has been removed, but then where does iOS get that it's set to Celsius when EVERYTHING is set for Fahrenheit?  Is this an iOS Glitch?  So if you had a TRUE HomeKit approved hub with a HomeKit approved thermostat, would it be the same way?

See image below:

![Screenshot 2019-12-17 at 3 35 50 PM](https://user-images.githubusercontent.com/8729476/71036415-47a6cc00-20e3-11ea-9e0e-0a6099baf36e.png)

**Comment by jvmahon** [comment]
its an iOS quirk.  On the technical side, HomeKit only understands Celsius temperatures - that is, all values that you send to or receive from HomeKit are in Celsius. Internal to the iOS Home app, it does a conversion to what gets displayed on the user interface. That conversion is controlled by the iOS "Language and Regions" setting and not by the "Unit" setting in the iOS Home App. I have no idea why they have that setting in the Home app.

However, to make this less confusing, I can do a code update to force that indicator to match whatever units HomeSeer is using - for 99.9 % of users it is probably a safe assumption that they will use the same units on both HomeSeer and iOS.

**Comment by meluvalli** [comment]
Ok.  That sounds great!  I appreciate you taking the time to explain it to me :)  Thanks!

**Comment by jvmahon** [comment]
I've now update the code and publishe a new version which now "locks" this control to the value receive from HomeSeer. For example, if HomeSeer is set to use Fahrenheit, this will always show "Fahrenheit" as selected and can't be change by the user. I think this is less confusing than allowing the user to change the value but doing nothing in response to the change. Please give it a try and if you have no more issue with this setting, the comment can be closed.

**Comment by meluvalli** [comment]
Ok.  I have tested this.  My unit is now Fahrenheit.  That's the good news...  Now for the bad news... :(

I assume that you told it to read the HomeSeer setting under Setup/General TAB?  (See screenshot)

![image](https://user-images.githubusercontent.com/8729476/71058462-8d848400-2125-11ea-927f-c6496f37eb02.png)

If I'm correct, then I would assume that if I set it to Celsius, then HomeKit would show under Device Setting, Celsius and lock on that correct?  If so, this isn't working. (And YES I restarted HomeSeer AFTER making this change)

It now appears to be stuck in Fahrenheit no matter what you do in HomeSeer (Assuming this is where you are getting the setting).

So, yes it works for Fahrenheit users, but now it appears it broke Celsius.  While I'm ok with this, others may not be!

Also, as a side note, "GSH - THERMOSTAT DISPLAY UNITS" that you added for logging before is still in the code ;)  Wasn't sure if you remembered that or not :)

**Comment by jvmahon** [comment]
I'll work on this over the weekend.

**Comment by jvmahon** [comment]
Done. Update to 0.0.12
The solution I implemented is:
1) A more detailed error message is displayed
2) A timer is started and after 3 seconds, the display resets to the proper indicator (matching the Temperature Units used by HomeSeer.

I tried to hide the control and to make it so it wasn't changeable but these didn't work so this is all I can do for now.
