### ISSUE TITLE
Homeseer integration

### ISSUE THREAD

**Issue by HOMESEERDUDE** [jvmahon/Homebridge-HomeSeer4#202]
I use your homeseer integration to work with homebridge. It works perfectly. Can I integrate homeseer with home assistant?   I think there are tools with home assistant plugins that are not available on homeseer. I would rather not start all over.

**Comment by jvmahon** [comment]
Sorry, I don't know anything about homeseer <-> Home Assistant integration.
I do understand, however, that Home Assistant does have its own HomeKit integration (though I haven't tried it myself), so if you do end up using Home Assistant, you wouldn't need my plugin.
