### ISSUE TITLE
thermostat advanced add error with remotec zxt-600

### ISSUE THREAD

**Issue by Duc1198** [jvmahon/Homebridge-HomeSeer4#204]
Hi all,

Any pointers on getting my thermostat / air con working with homebridge?

I'm pretty sure its all configured correctly. 

Error log....

[HomeSeer] Setting up a Thermostat with configuration values: {"type":"Thermostat","name":"Jordan AC","ref":5587,"batteryRef":5586,"controlRef":5589,"heatingSetpointRef":5590,"coolingSetpointRef":5591,"temperatureUnit":"C","uuid_base":"Ref5587","interface_name":"Z-Wave","batteryThreshold":25,"model":"Z-Wave Sensor Multilevel"}

**SyntaxError: Incorrect configuration data. Missing one of 'ref', 'controlRef', 'stateRef', and at least one of 'coolingSetpointRef' or 'heatingSetpointRef'.**

**![2024-01-12_12-59-11](https://github.com/jvmahon/Homebridge-HomeSeer4/assets/71119249/7dec7e2e-c14c-41b5-9f16-3e9528814fc0)** 

{
                    "type": "Thermostat",
                    "name": "Jordan AC",
                    "ref": 5587,
                    "batteryRef": 5586,
                    "controlRef": 5589,
                    "heatingSetpointRef": 5590,
                    "coolingSetpointRef": 5591,
                    "temperatureUnit": "C"
                },

**Comment by jvmahon** [comment]
Notice the error message:
`````
SyntaxError: Incorrect configuration data. Missing one of 'ref', 'controlRef', 'stateRef', and at least one of 'coolingSetpointRef' or 'heatingSetpointRef'.
`````


Your setup is missing a "stateRef".

Most thermostats show the current operating state - for example, when you put it in "heat" mode, the heating system might be idle, or actually generating heat, and there is usually a current state that gets shown.

Try setting stateRef to 5589 . Not sure if this will work, and it will cause the thermostate on iOS to always indicate it is running in the given state, but if your thermostate doesn't show current state, this may be the best you can do.
