### ISSUE TITLE
Speed Question

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#21]
I have noticed on my iOS devices, i'll get "Devices Not Responding" or "Updating" for 10-30 seconds.  I thought it was an issue with HomeBridge-HomeSeer-2018/HomeBridge-HomeSeer4 plugin, but I realized that it actually seems to happen (at least a lot more often) when I have another plugin like HomeBridge-GSH or HomeBridge-Alexa.   

If I strictly have ONLY the HomeBridge-HomeSeer plugin installed, everything seems REALLY fast.

Have you heard of this or know of any resolutions to try?  I have also posted this on the HomeBridge-GSH github just for there feedback as well.

**Comment by jvmahon** [comment]
Yeah, I noticed this "Device Not Responding" problem myself. Its due to the fix for the Celsius / Fahrenheit problem you raised in another. I have a few ideas of how to fix this, but it may have to wait until Saturday for this and the Garage Door Fix. The more pressing issue is the network one.

**Comment by meluvalli** [comment]
Understand that 😀.   I remember the HomeSeer-2018 doing this as well though.  Granted, I’m not 100% sure without going back to it if it was also noticeably slower only with Alexa/Google plugins or not.

**Comment by meluvalli** [comment]
Guess it's not just when I have alexa/google installed :(
![Error](https://user-images.githubusercontent.com/8729476/71119863-c4e44680-21a0-11ea-88fb-951079899e13.png)

**Comment by jvmahon** [comment]
Sometimes you need to do a shutdown of the Home app and then restart it.
I.e., double-click the Home button, and then swipe up on the Home app to shut it down completely. Then restart.
