### ISSUE TITLE
Enhancement Request - batteryRef on Switch

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#22]
Not sure if it's possible because I don't know if Apple HomeKit even supports it, but it does exist, so maybe?

Would be nice to be able to add Battery Status (batteryRef) to Switch type.

I use a Switch to activate my Roomba.  I have to have two devices, one for Roomba Status to get Battery level, and another to turn on/off roomba.  If Switch supported batteryRef parameter, I could eliminate one.

I know this is probably low priority, but just a thought :)

**Comment by jvmahon** [comment]
Done. Update to 0.0.11

Regards,
Jim

**Comment by meluvalli** [comment]
Awesome!  Thank you!!!
