### ISSUE TITLE
Events ignore "Name" field.

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#23]
Below are my events in Config.json.  
EventGroup: Name of Group HomeSeer
EventName: Name of Event in HomeSeer
Name: Should be Display name shown in HomeKit (iOS)

<pre>
            "events": [
                {
                    "eventGroup": "1-TEST_Events",
                    "eventName": "MyEvent-HomeSeerName1",
                    "name": "My Event 1"
                },
                {
                    "eventGroup": "1-TEST_Events",
                    "eventName": "MyEvent-HomeSeerName2",
                    "name": "My Event 2"
                }
            ],
</pre>

However, "name" is actually completely ignored.  It only uses EventName.

![IMG_0278](https://user-images.githubusercontent.com/8729476/71237725-f572d000-22c7-11ea-908b-e7533f5cab8d.jpg)

![IMG_0279](https://user-images.githubusercontent.com/8729476/71237727-f9065700-22c7-11ea-8c4c-b0d3e250f364.jpg)

**Also Note:** This issue is true in HomeBridge-HomeSeer-2018 as well.

**Comment by jvmahon** [comment]
This should be fixed in the 0.0.12 release.
Re-open this issue if you are still having problems.

**Comment by meluvalli** [comment]
Yep!  All fixed :)  Confirmed working :)  Thank you!
