### ISSUE TITLE
Adjustable Speed Fan

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#27]
Adjustable speed fan does not work. "can_dim": true, returns that it is not a valid property of type BinaryFan.

**Comment by dibble9012** [comment]
Figured out "type" needs to be "MultilevelFan". Didn't see it in the sample JSON. Might want to add this for future reference.

**Comment by jvmahon** [comment]
Thanks! 
As mentioned on the Readme page, "can_dim" is no longer a valid property, but the code "should" have automatically detected that the fan was a multilevel fan.

Can you provide some more information so I can try and diagnose this:

1) What type of fan controller are you using?   Are you using a ordinary dimmer switch as a fan controller, or something else?  

2). Can you post the "Status Graphics" page for your fan controller.

**Comment by dibble9012** [comment]
I am using a HomeSeer FC-200+ controller. 
![48F2B7B5-79AD-4A8B-8C84-2B040C315DC6](https://user-images.githubusercontent.com/6963660/71619066-642d1480-2b77-11ea-981f-f71ff3a6e918.jpeg)
![EDEAA937-8DAD-420E-AA73-8867999E1938](https://user-images.githubusercontent.com/6963660/71619067-642d1480-2b77-11ea-8200-00735c1e4034.jpeg)

**Comment by jvmahon** [comment]
Thanks. Also, what version of the plugin?
Enter the following to determine this:

npm -g list --depth=0

**Comment by dibble9012** [comment]
0.0.26

**Comment by jvmahon** [comment]
O.K., thanks.
I'll check into this. There was a similar issue about lights not being detected as dimming. I had fixed that, but must have missed this one.  Can you confirm - when the device is created in HomeKit, does it appear only as an "On/ Off" Binary type device, or is there a slider that is created?

**Comment by dibble9012** [comment]
Only off/on. I had to update the type for the slider to show. The lights were automatically added as dimming and not dimming correctly.

**Comment by jvmahon** [comment]
Thanks. Finally, can you show me how you set them up in your config.json file.

I'll try to look into this today.

**Comment by dibble9012** [comment]
This is how it is currently set up (and working as it should). Previously the “type” was just “fan”. 
![D5AAB9B6-DB58-4F82-84AA-EDCAC129339D](https://user-images.githubusercontent.com/6963660/71619538-abb4a000-2b79-11ea-9c0a-66ce0b1a15ea.jpeg)

**Comment by jvmahon** [comment]
I think I found the problem. The "Control Use" field on your status graphics page is set to "Fan" for the values 1-98. I had tested with an ordinary dimmer switch, so I was checking for "Dim" rather than "Fan".  I'll fix this on my end and will let you know once it is fixed. Should be pretty quick (will be out today).

**Comment by dibble9012** [comment]
Awesome. Thanks! I’ll test it tomorrow.

**Comment by jvmahon** [comment]
An update 0.0.27 has been published which I think will fix this.
Update using ...

npm -g install homebridge-homeseer4

and let me know if this works.

**Comment by dibble9012** [comment]
Works! Thanks!

**Comment by jvmahon** [comment]
You're welcome. I'll close this out now.
