### ISSUE TITLE
config.json value not being used "openValue : 99"

### ISSUE THREAD

**Issue by mbaastrup** [jvmahon/Homebridge-HomeSeer4#28]
This new platform seems promising! Currently testing on HS3:

In config.json I have a window setup as:

            "accessories": [
                {
                    "type": "Window",
                    "name": null,
                    "ref": 1294,
                    "uuid_base": 0,
                    "batteryRef": 0,
                    "batteryThreshold": 25,
                    "openValue": 99,
                    "closedValue": 0
                }
            ]
When I open or close from ios it sends correct closedValue, but not openValue:

[1/1/2020, 10:07:10 AM] [HomeSeer] Sending new value to HomeSeer on ASCII Port, HomeSeer device: '1294', sent value: '100'
[1/1/2020, 10:07:11 AM] [HomeSeer] Sending new value to HomeSeer on ASCII Port, HomeSeer device: '1294', sent value: '0'

I have tryed rebooting both the HomeKit server and the container.

Looking forward to a lot more testing

**Comment by jvmahon** [comment]
Currently, the code for those devices only works for a Z-Wave binary switch with 0 being Open and 1 being closed. However, I think I can quickly fix this (possibly today or over the coming weekend).

In order to do this, can you . . .

1. Post a copy of the "Status Graphics" page for the window covering that you are using.  I need to see the upper section with the values (the "Edit Status Text for device ..." section), I don't need the section where you define the graphics icons.
2. Explain - what controller are you using -- the 0 and 99 values suggest its a Z-Wave dimmer switch - is that correct?  If so, are you actually using the intermediate values 1-98, or are the only relevant values 0 and 99?
3. Or are you using an actual Z-Wave window / shade controller - if so, which one?
4. If its not a Z-Wave dimmer switch, what are you using?

**Comment by mbaastrup** [comment]
ad2: It is a dimmer switch. It works very well for intermediate values 0-99 so it closes at 0 and from 0 to 99 it put the switch where it should as a percentage. So with the slider in iOS I can actually send everything from 0-99 and it works - but the tap value is 100 which it cant understand.
Its a Qubino 12/24 DC shutter: https://qubino.com/products/flush-shutter-dc/  I have 4 of them for controlling window opening mounted with an actuator I think its called. A mini version of attached
![200_light_industrial](https://user-images.githubusercontent.com/42763302/71642168-a5244680-2ca7-11ea-9be9-5c2d1f7a5ae1.jpg)
<img width="1001" alt="Screenshot 2020-01-01 at 14 49 26" src="https://user-images.githubusercontent.com/42763302/71642170-a5244680-2ca7-11ea-9cda-a6badcb6f8d2.png">
<img width="994" alt="Screenshot 2020-01-01 at 14 49 18" src="https://user-images.githubusercontent.com/42763302/71642171-a5244680-2ca7-11ea-8a27-cd9bff582c7b.png">





Status page attached and also the total device group in needed. As you can see it makes two devices that can be used, a binary and a multilevel. I use the multilevel on you "2018" bridge today - maybe we actually wrote about that a few years ago?

**Comment by mbaastrup** [comment]
Thanks for your support and great work btw. I will do some testing on one or two other devices I remember needed special attention in the former plugin too.  I am quite sure that the Danfoss LC-13 which a lot of people use, needs a bit of tweaking too as it is not a full blown Thermostat but a radiator valve thermostat.

**Comment by jvmahon** [comment]
I have a fix just about ready. I'm testing it a bit. May only need a couple hours more then you can test it for me  (I have to "fake"a window covering using a dimmer  and a light switch, so it would be great if you can test it using the "real" thing).

Also, do you know - what happens if you send the value "255". Z-wave dimmer devices often use this to go to the "last" setting - does your device support that?

**Comment by mbaastrup** [comment]
Will be happy to test whatever you need - of course. The Danfoss Thermostats I will look into in an hour. I can send you how I manage it today in the 2018 bridge, running it std in HS. 
I also have some of the also pretty popular rollers for window covering, running 433mhz RFXcom - I can fake those in HS which is the setup today, no prob.
Rest of my 50+ devices are pretty std. Lightbulb, simple switches (controlling fans) etc. 
I just re-add'ed the full Qubino HS device (registers as a Z-Wave Switch Multilevel) incl. root to be sure we start with a clean layout (see attached). It seems a value of 255 triggers a 99 setting which is a full open according to the controller - I find this a bit strange, but it seems to be the case. 

In general I think the setup with getting as much infor from the registration in HS is the right direction, but with the huge - and growing - volume of devices, override through config.json will take care of the ones that are too special. 
That also goes for limits in the iOS devices, e.g. a thermostat default in iOS are 0 to 35 degrees, while the HS device in some cases are 4 to 28 and if you set the value outside it doesnt default to anything but just dont react. I changed that in the HomeKitDevices (or something like that) in one of the versions on the 2018
<img width="994" alt="Screenshot 2020-01-01 at 16 21 51" src="https://user-images.githubusercontent.com/42763302/71642985-aa878e00-2cb3-11ea-8322-1be0b4709e89.png">

**Comment by jvmahon** [comment]
I have published an update 0.0.28. Please update and let me know if that works for you.
Update using:
`````
npm -g  install homebridge-homeseer4
`````

I've also added some (rough) notes to the Wiki which you may want to review first . . .

https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Windows-and-Window-Converings-Settings

**Comment by mbaastrup** [comment]
From the notes it looks good! I will start testing in an hour, and get back to you asap.
The update npm -g... is can be run from the terminal in the UI right?

**Comment by jvmahon** [comment]
I'm on Windows, so I just run it form a 'cmd' window, but I think its basically the same in Linux.

**Comment by mbaastrup** [comment]
It is - and the update worked. 
Using the simple way   "Windows": [ 1294  ] it seems it does not take the name from the HS device but the z-wave type. I am not sure yet, It can be a cashing or something else.
Using the {"type":"VariableWindow", "ref": 1294}  I took the full setup: 
                {
                    "type": "VariableWindow",
                    "name": null,
                    "ref": 1294,
                    "uuid_base": 0,
                    "batteryRef": 0,
                    "batteryThreshold": 25,
                    "openValue": 99,
                    "closedValue": 0
                }

It works too, still I have the issue with the parsing of the HS name. Is there a cashing file I need to erase in these situations? I just setup another window that has not been setup before, name worked perfect here. So I guess cashing is the thing here.

**Comment by jvmahon** [comment]
Also, FYI - regarding the thermostats you mentioned, if those aren't working, please open that as a separate issue. As for the issue you mentioned concerning the range of correct values for a thermostat, my plan is to try and read the range data from HomeSeer and use that to set the range that can be selected in HomeKit. However, my early attempts at doing this didn't work well (the HomeKit interface was a mess!). This is more of a minor issue as the essential functionality is now working. I plan to add some more "polish" at a later date.

**Comment by mbaastrup** [comment]
Copy that, will put in different issue for better tracking - I will look out for small UI stuff too (there is something with a dash in the iOS UI when including HS room. I will describe in separate issue.
The scal in iOS interface is a mess, I tried to deal with it myself but gave up 

Thanks for this! Testing rollers/covering later, but as they are pretty much the same it should work.

**Comment by jvmahon** [comment]
You just mentioned using the "full" setup . . .
So, just in case, you didn't understand the setup

for 'name', substitute a string in place of 'null'

for uuid_base, by default, the plugin sets it to "Ref" plus the "ref" number. It must be unique for every HomeKit / HomeSeer device. So, in the example below, it would become  "uuid"base":"Ref1294". Generally, leave this one out of your config. json. The only time you need to include it is if you are adding the same HomeSeer device as two separate HomeKit devices.  See an example here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Show-the-same-device-in-multiple-rooms


The "name" only matters when the device is first added. If you've changed it from within the iOS application, the "new" name sticks.   The default name "should" be the Room Name, a dash, then the HomeSeer Name.   I included the Room Name and "-" so you don't have a huge number of devices called "Lights". I think its easier to include the room name and then the user can edit that in the iOS app.


`````
{
"type": "VariableWindow",
"name": null,
"ref": 1294,
"uuid_base": 0,
"batteryRef": 0,
"batteryThreshold": 25,
"openValue": 99,
"closedValue": 0
}
`````

**Comment by jvmahon** [comment]
You mentioned controlling some 433 MHz shades. I have a number of roller shades with bofu 433 MHz motors that I would like to connect to HomeSeer. I was wondering how you are doing this (i.e., what devices, software, etc.). Currently, I'm controlling them through a NEO Smart Shade controller and I wrote software (homebridge-smartshades) to interface that to HomeKit.  Because these 433 MHz motor remotes are not bi-directional, you can't be sure of the position of the shades, so for my NEO controller, I allow 3 states, closed, open, and half-way.  The shades always reset to half way and the user can either flick up on the shade icon to open them, or down to close them (and then, regardless, after about 20 seconds they show as being at the 50% position).  Just curious as to what other solutions are out there.

**Comment by mbaastrup** [comment]
Thanks for the details on the naming methods - I will see if I can get it right.
I use the same BOFU motors for very cheap IKEA curtains (rollers) and the RFXCOM plugin in HS. The hardware is a transmitter/reciever http://www.rfxcom.com/ - everything has worked for 4 years now with no issues.
It's very simple, and too simple for your use case. I only need to have the curtains either up (to the set limit) or down (to the set limit) and no status as I never control them manually. 
 I guess your solution is a bit more advanced. I have tried to work with timers because the motors are pretty precise (up for 13 sec, stop) which works, but with two windows next to each other, even a 0,5 cm difference is visible. And also you will need to base line them position wise due to the uni direction. But it could give you the middel limit option or even an arbitrary - but never 100% precise. 

I run generally everything into HS and use HomeKit only for front end to not loose track of rules, maintain master devices etc. Next step is upgrading to HS4 and add Google Home in my Sonos as voice control. The regular one directly from HS to Google via myHS is not very elegant at this point and I would like to have a simple stack (homebridge-gsh). Thats why I keep the back end clean, all rules there - and then HomeKit and gsh as simple slave front ends.

I have used this shop in Sweden - very helpful staff. They sell a z-wave kit with the bofu but I have not tried it. But it is a Qubino type controller like i use on the windows: https://www.m.nu/rullgardin-markis/motorisera-rullgardin-1-motor-z-wave-24v at least based on logic it should be what you are looking for as an alternative?

**Comment by mbaastrup** [comment]
Regarding this: "I included the Room Name and "-" so you don't have a huge number of devices called "Lights". I think its easier to include the room name and then the user can edit that in the iOS app."

I agree, and did that in my setup of the 2018 of exactly that reason. There is though a small thing to consider with the dash, which I suggest you replace with a simple space after room name. The HomeKit app will not use the room name in the name field if you use the exact same room name convention in HS and in the HomeKit, except on the status page (I believe). So if you have a device named Living Room - Lamp1 and you assign that in the iOS app to a room named Living Room the device will show up like this: "- Lamp1". Keep the idea, but replace the dash with a space after the room name from HS should be fine I guess

**Comment by mbaastrup** [comment]
I will not open an issue on the Danfoss thermostats as I got it working (except for the UI part with the scale)
                    "type": "Thermostat",
                    "name": null,
                    "ref": 1117,
                    "uuid_base": 0,
                    "batteryRef": 0,
                    "batteryThreshold": 25,
                    "controlRef": 786,
                    "stateRef": 786,
                    "heatingSetpointRef": 290,
                    "coolingSetpointRef": 290,
                    "humidityRef": 0,
                    "humidityTargetRef": 0

1117: An external temperature sensor in the same room (could be just the SetPointDevice if no sensor available)
290: The Danfoss SetPoint device
786: A dummy State device, used on all Thermostats (Values 0,1,2,3 set to 1/Heat)

**Comment by jvmahon** [comment]
I'll make the naming change you suggested (eliminating the dash) in the next build - 0.0.29.

I assume you have no further issues with the Windows coverings.

As for your Thermostat, as I understand your comments, this only controls heating - is that correct?
If so, if you only set the heatingSetPointRef and don't define coolingSetpointRef, you should get a "heating only" thermostat.

Similarly, if you only set coolingSetpointRef you get an Air Conditioning-only thermostat.

There is a brief note on this in the Wiki section on "Thermostats" - but this hasn't been tested that thoroughly, so if it doesn't work for you, let me know and I'll work with you to fix it.

I'll close out this comment for now, but if there is anything else on these subjects, please re-open or start a new thread.

**Comment by mbaastrup** [comment]
Danfoss is heating only - confirmed. I will try setting only the heatingSetpoint and let you know if this does not work.
Window covering works very well too.
Thanks for you help. Let me know if you need support for testing
