### ISSUE TITLE
Automatically populate tamper sensors

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#29]
Is there any way to auto-populate tamper sensors just like you do with batteries? Thanks!

**Comment by jvmahon** [comment]
Unfortunately, I don't think there is.
Batteries have a unique set of identifiers that I can look for (Device_API == 4, Device_Type == 0, Device_SubType == 128) so I use that to detect batteries. I haven't found anything similar for tamper devices.
