### ISSUE TITLE
Migration tips

### ISSUE THREAD

**Issue by rrman** [jvmahon/Homebridge-HomeSeer4#30]
Hi,

Happy New Year!

I have some questions regarding migrating from Homebridge-homeseer-plugin-2018 to Homebridge-HomeSeer4 (maybe some answers can be put in a short migration blurb in the new plug-in's documentation to help other users):

1. Before migration, should I first remove the Homebridge bridg(es) from the iOS Home App?

2. Also, before migration, should I first remove the contents of /var/lib/homebridge* ?

3. If HomeSeer is configured to not require user id & password for logging in from the local network, what should we put for login and password in the config.json file?

4. I use JowieHue for my Philips Hue lights, but I don't use Homebridge for my Philips Hue lights, since HomeKit can talk to the Philips Hue bridge directly. I read in a HomeSeer thread that a beta version of the Homebridge-HomeSeer4 plugin doesn't yet work properly if we use the JowieHue plugin. Does it matter for me, given that I don't use Homebridge for controlling my Philips Hue lights?

5. I was looking to migrate to the new Homebridge-HomeSeer4 plugin even before migrating to HS4. Is that okay/supported?

Regards,

Randy (randman)

**Comment by dibble9012** [comment]
Here is my experience (jvmahon may have something to add):

1. I did not do anything with the home app on iOS for the migration. 

2. I did not remove that folder. Although I did uninstall homebridge through the command line. 

3. Not sure about this. I added a user name and password to make sure it worked. 

4. If you add hue to HomeKit directly (and don’t add jowlhue devices to the config.json) it’ll be fine. 

5. Yes. I’m using with the latest version of HS3 and it works fine.

**Comment by dibble9012** [comment]
I will add I’m that for the migration I updated my config.json to be compatible with the new version of homebridge. But easily done.

**Comment by jvmahon** [comment]
@dibble9012 has it correct - there is generally no need to change var/lib/homebridge* except to edit config.json. If you were to delete the other folders ("persist" and "accessories") it would, essentially, result in a "full reset" of homebridge and you'd have to re-pair with your iOS device and then reset each HomeKit device into a new room.  Basically, all you *should* need to do is add the "login" and "password" parameters and then delete some now-unused parameters from config.json. 

See https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file for some additional info.

**Comment by rrman** [comment]
Thanks folks! I’m glad I don’t need to remove the existing bridges. Migration sounds like it will be very easy for me!

**Comment by jvmahon** [comment]
Though I still recommend backing up your existing homebridge directory first.

**Comment by jvmahon** [comment]
Let me know how your migration went and if you encountered any problems - that way, I can either improve the plugin, or add instructions to the wiki.

Note that the latest update is 0.0.31

**Comment by rrman** [comment]
Okay. I may not get to it right away, since I'll be in and out of town in the short term and don't want to risk any changes when I'll be out of town.

**Comment by jvmahon** [comment]
I've updated the Linux installation and troubleshooting Wiki to incorporate additional information derived from these comments, so I"m now closing this issue. Re-open or make suggestions for inclusion in the Wiki if you think an issue remains. Thanks.
