### ISSUE TITLE
Invalid Thermostat Type

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#31]
Randomly getting this error, which shuts down/crashes homebridge. ![Image](https://i.imgur.com/TzZbEOT.jpg)

Config.json
![Image](https://i.imgur.com/HxkVA35.jpg)

**Comment by jvmahon** [comment]
Try the updated "Simplified Setup" method of configuring your thermostat as explained at:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Thermostats

Let me know if that works for you.

**Comment by dibble9012** [comment]
I don’t think I can do that since I don’t really have a root device (it’s a Nest using the nest plugin). ![Image](https://i.imgur.com/f2qljTT.jpg)![Image](https://i.imgur.com/xLpBlYB.jpg)

**Comment by jvmahon** [comment]
Based on the devices shown in your last post, your Nest thermostat does not work anything at all like my plugin expects.

There are several Nest-specific homebridge plugin. Have you tried any of them? Here's some info on one of them: https://www.npmjs.com/package/homebridge-nest

If you can't get one of these to work, let me know and I'll see if there is anything I can do to get my plugin to work for you.

**Comment by dibble9012** [comment]
I tried adding it again to the complex config (but made sure I followed the new template for thermostats.) See what happens. I use the nest in multiple automations in HomeSeer so I’d rather not move it to a homebridge specific plugin. Might create issues with two plugins trying to control it.

**Comment by dibble9012** [comment]
Yes it worked fine with the old version of homebridge HomeSeer 2018.

**Comment by jvmahon** [comment]
O.K., I'll look into this a bit more. If it worked in the old version, I should be able to get it to work in this version.

**Comment by jvmahon** [comment]
Also, can you execute the following two commands on your HomeSeer computer and send me the results by email (you can also execute them remotely by substituting your HomeSeer computer's IP address for 127.0.0.1):

http://127.0.0.1/JSON?request=getcontrol&ref=1177,1178,1179,1180,1181,1182,1183,1184,1185

http://127.0.0.1/JSON?request=getstatus&ref=1177,1178,1179,1180,1181,1182,1183,1184,1185

**Comment by jvmahon** [comment]
Also, can you . . .

Update to plugin version 0.0.29
Tell me which version of node are you using (run  node -v to check).
and let me know - are you on Windows or Linux?

**Comment by dibble9012** [comment]
I believe it was .26, I have updated to the latest now. Also updated to 12.14 for node. I am on MacOS. I am using Nest Devices (Spud) for HomeSeer.

**Comment by jvmahon** [comment]
Thanks. Actually, from your error messages, I think I see at least one of the errors. Can you post a copy of the "status graphics" page for device 1181. I need to see the upper-half of it -- the part with the numeric values and "Control Use" settings.

**Comment by dibble9012** [comment]
Here you go, and I'm working on getting command results.

<img width="1011" alt="Screen Shot 2020-01-02 at 8 00 24 PM" src="https://user-images.githubusercontent.com/6963660/71706562-a1bdb780-2d9a-11ea-874f-f8dae4b231ff.png">

**Comment by jvmahon** [comment]
Thanks. The first problem at issue is my plugin  doesn't handle the "Eco" value. That's why you got the crash shown in your first post. I have to map this to something else. It seems this is a lot like "Auto" - is that correct? That is, if I map "Eco" so it appears in HomeKit as "Auto" would that be logical?

**Comment by dibble9012** [comment]
I've never actually used Eco in the home app. Heat-Cool is usually what the home app uses I believe. Eco is if all users are away from home, it changes the heat and cool set points to user defined more energy efficient temperatures.

**Comment by dibble9012** [comment]
I just tested it, it is indeed the Eco setting causing the crash. As soon as I select it in Homeseer or the Nest app, Homebridge crashes.

**Comment by dibble9012** [comment]
Also, it seems like like now when I set the temperature through the Home App it won't change the HomeSeer setpoints. I can see in terminal where it sends the temperature, but it does not change in HomeSeer.

**Comment by jvmahon** [comment]
O.K., well I'll take care of the Eco crashing issue first - I think that's an easy one. Then we can  move on to fixing the temperature setting.

**Comment by jvmahon** [comment]
Try updating to 0.0.30

npm -g install homebridge-homeseer4

Note that for your Nest thermostats,  the device labeled "Nest Thermostat" is the root device (i.e., device 1177 in your case).

So you should be able to configure it using the simplified form.
I left in a debugging statement that will print (at startup, in yellow, beginning with the word **Debug** ) the configuration that was automatically determined -- this will be printed right before the QR code is shown.

**Comment by dibble9012** [comment]
![Screen Shot 2020-01-02 at 21 23 04](https://user-images.githubusercontent.com/6963660/71708443-3c6fc380-2da6-11ea-9460-83a619170672.png)

**Comment by jvmahon** [comment]
The good news is this is a lot closer to working.
However, I'll need to create an update with some extra debugging code in it for you in order to solve that final issue. I may not get to that until Saturday.

**Comment by dibble9012** [comment]
No problem. Appreciate the work you do on this plugin!

**Comment by jvmahon** [comment]
I found the problem - that was the difficult part.
I should be able to fix it pretty easily. But not tonight. Hopefully tomorrow or else Saturday.

**Comment by jvmahon** [comment]
Update to version 0.0.31 of the plugin and try it using the simplified setup process and let know if it works. Thanks.

**Comment by dibble9012** [comment]
Updated to .31.

Humidity and modes works fine. Eco does not crash homebridge. Still can’t seem to change the temperature set points.

**Comment by jvmahon** [comment]
O.K., getting closer. See my email.

**Comment by dibble9012** [comment]
I will note, controlling the thermostat over HTTP commands, such as below, using the same values that are sent by the Homebridge plugin, works fine, instantly. So it's not the value of the commands that is the issue. Something is being lost in translation between the Homebridge plugin and HS3.

http://10.0.1.2/JSON?request=controldevicebyvalue&ref=1179&value=69.08000000000001

**Comment by jvmahon** [comment]
That is strange.
Maybe the thermostat doesn’t like the long data value when it is sent over telnet.
Can you try an experiment.
Assuming 11000 is your telnet port number of Homeseer (that’s the default ASCII/telnet port #)

1. connect by telnet. This assumes you use the default telnet port of 11000
telnet  10.0.1.2 11000

2. Authenticate by entering the following command (substitute your login, password where indicated). You should receive the response “OK” after authenticating.
au,login,password

3. Send a command to your thermostat
                CV,1079,69.08000000000001

4. If the thermostat doesn’t respond, try entering another temperature but without fewer digits. E.g.,
                cv,1079,69.1

IF #4 works but #3 doesn’t, then the solution is simple.

Thanks.
Jim

**Comment by dibble9012** [comment]
Both 3 and 4 work when manually entering in telnet, instantly.

**Comment by jvmahon** [comment]
I understand you got this working, so I'm closing the issue. Re-open if there are further problems.
