### ISSUE TITLE
Garage Door Event writing with Momentary & Sensor Contacts

### ISSUE THREAD

**Issue by Bi7** [jvmahon/Homebridge-HomeSeer4#39]
Moving to a new issue from another conversation.

{
	"type": "GarageDoorOpener",
        "ref": 123,                 // HomeSeer reference # for the device
	"openValue": 255,     // Control Value used to cause the door to open.
	"closedValue": 0,    // Control Value used to cause the door to close.
	"openingValue": 254,        // Status Value used to indicate the door is opening.
	"closingValue": 252,       // Status Value used to indicate the door is closing
	"stoppedValue": 253       // Status Value used to indicate the door has stopped part-way.
}

JVMahon:
"You may not need to rewrite your events if they worked with the "old" plugin as that plugin also had opening / stopped / closing statuses -- you probably just didn't realize that. So if it worked then, it should work now."

I should state this setup is using an Omni panel with one contact sensor and a momentary contact to open/close the garage door.

"You may not need to rewrite your events..."

Maybe so for opening and closing, but how would Homeseer know for stopped without an event?
There is only the one contact sensor for open or closed. I would think a timer used from state to state (in an event) would be the only way to get that stopped value ( by explicitly setting 253).

I have found the event writing for this difficult because both the action to close/open and the state come from the virtual device. The way I have written my events are to, say for opening, set the virtual device from 0 to 255.
It just seems that event writing would be much easier if I were to add another sensor to confirm open, rather than just the one I have. In other words, I have no way to confirm the open state except by using a timer (as in "it should be open now!") This has been an okay method but occasionally buggy.
The Homekit app does show opening or closing but that seems to be a separate assumption in the code.
Would you suggest writing the Event to set the virtual device to openingValue or closingValue to trigger the actions?

**Comment by jvmahon** [comment]
As a practical matter, the setup you mention doesn't easily mesh with managing the opening / closing / stopped states and I suppose you would have to manage the states through events, but the only events you "really" need to manage are Open and Closed. If you did nothing about the opening / stopped /  closing events, the plugin should work - the only downside would be that Homekit wouldn't show the opening / closing animations; instead, it would show only open or closed. 

So, assuming your momentary contact device is #111 and your contact sensor is #222, and the virtual device is # 333 , you just need . . .

If (virtual device 333) changes and is set to Open
Or (virtual device 333) change and is set to closed
Then pulse contact

If (device 111 indicates door is open) 
and (device 111 changes to indicate door is closed)
then set virtual device to closed.

If (device 111 indicates door is closed)
and (device 111 changes to indicate door is open)
then set virtual device to open.

If you had two contact sensors, one at the top and one at the bottom of the door, you could probably manage the intermediate states, but with just one, it isn't really that practical (at some point, given the cost of the various Z-Wave sensors, your close to the price of just buying a Z-Wave door controller)

**Comment by Bi7** [comment]
Thanks,
That is essentially what I have programmed now. Oddly enough I do get animations in Homekit for opening and closing.
I use a hardwire sensor now so may just go ahead and add another to get rid of occasional glitches.

( Just for completeness, I tested using openValue to trigger the garage door opener, it did NOT work)
Thanks again.

**Comment by jvmahon** [comment]
When you say that "openValue" did not trigger the garage door opener, do you mean that it didn't change the virtual device, or that the event didn't fire?

If it didn't trigger the virtual device, try the following instead:

Go to the "Status Graphics" page of the Virtual Device
Scroll down to the value that is used to Open the  door. Change its "Control Use" to "Door Unlock" as shown in the image below. Similarly, scroll to the value that is used to Close the door. Change its "Control Use" to "Door Lock".  They in your "config.json" you should be able to define your garage door using only 
{"type":"GarageDoorOpener", "ref": XXX}


![image](https://user-images.githubusercontent.com/15061942/72844226-15503780-3c6a-11ea-9065-d3074360fc7f.png)

**Comment by Bi7** [comment]
I apologize, I meant openingValue, not openValue. I will correct my statement.

**Comment by jvmahon** [comment]
Generally speaking, "openingValue", "closingValue" and "Stopped" are statuses, rather than controls. Normally, these would be something that a plugin sets to show the door is in a transitional state and you wouldn't want to set them from events. However, when you are using a virtual device to simulate a garage door opener, you can have your events "set" these statuses so as to more realistically simulate what a "real" garage door opener plugin should be doing. If you find that you can't "set" them from your events, make sure you have then set up as "both" status and control. If they are "status" only, the event may not be able to set them.

**Comment by Bi7** [comment]
I did try to use the "status"es as both status and control however the plugin would respond with unknown value 252 or such and say "expected 255". 
On a side note, strangely enough all my UPB OmniPro controlled light switches would dim on initial setup with HomeSeer4 but then a day later Homekit would allow a dimming setting but the lighting itself would only be on or off (0 or 100%).
I imagine from here I need to place all my non-z-wave in the complex section of config.json.

Thanks for everything

**Comment by jvmahon** [comment]
@Bi7 - before changing your config.json, try updating to the latest plugin version which I updated this morning. This may take care of the on/off problem with the dimmers (I hope). 

If you want to post your config.json and show me how you have the garage door openers set up, I'll take a look at your arrangement and the code to see if there is an error.
