### ISSUE TITLE
HomeSeerData is not defined

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#40]
Receive this error when starting homebridge on a brand new install:

`Jan 23 22:15:08 DibDabsPi homebridge[4143]: (node:4143) UnhandledPromiseRejectionWarning: ReferenceError: HomeSeerData is not defined
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at Object.exports.setupSensor (/opt/nodejs/lib/node_modules/homebridge-homeseer4/lib/Sensor Setup.js:170:22)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at Object.exports.setupServices (/opt/nodejs/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:170:12)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at HomeSeerAccessory.getServices (/opt/nodejs/lib/node_modules/homebridge-homeseer4/index.js:223:11)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at Server._createAccessory (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:427:36)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at Server.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:413:32)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at /opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at HomeSeerPlatform.accessories (/opt/nodejs/lib/node_modules/homebridge-homeseer4/index.js:187:5)
Jan 23 22:15:08 DibDabsPi homebridge[4143]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jan 23 22:15:08 DibDabsPi homebridge[4143]: (node:4143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jan 23 22:15:08 DibDabsPi homebridge[4143]: (node:4143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jvmahon** [comment]
Please confirm- what platform (windows / linux) and what verson of node?
Also, can you post your config.json file (you have to .zip it first).

**Comment by jvmahon** [comment]
I think I see the problem.

**Comment by jvmahon** [comment]
Updated to version 0.0.39 using
`````
npm -g install homebridge-homeseer4
`````
This should fix it. If it does, please just close the comment.
Thanks
Jim

**Comment by mbaastrup** [comment]
I had the same issue on .38, seems to be corrected with .39

**Comment by dibble9012** [comment]
That worked, thanks!
