### ISSUE TITLE
Random devices showing as not available. 

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#42]
Nothing odd to note in the logs. But randomly a good percentage of my devices are showing not available. 
![6387E21C-C011-4280-A110-80ECA33C6344](https://user-images.githubusercontent.com/6963660/73139595-5a86b780-4024-11ea-86e0-cf79c4b6aea0.png)

**Comment by jvmahon** [comment]
Obviously, that shouldn't happen.
I occasionally have that issue when I first start homebridge, particularly if I open the iOS app within the first minute or thereabouts. The solution is to shut down the iOS Home App (double-clicking than swiping up on the app to shut it down), and then re-start.

Are you running this plugin with any other plugins?   I strongly recommend that not be done, particularly if the 'other' plugins have to access cloud-based servers; many of those types of plugins seem to take too long to respond and can cause problems. I've posted instructions on how to run multiple instances of homebridge so you can separate out other plugins. See https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Running-Multiple-Instances-of-HomeBridge 

IF not, then . . ..
Is the problem always with Sensors? 
Is this just during the "startup" phase?
Dies it correct itself after a while? 
Are you running homebridge and homeseer on the same computer (I recommend that you do so if you can).
Is this a new issue with the current 0.39 version or have you also had this issue in prior versions and/or with the homebridge-homeseer-plugin-2018 version?
What version of node are you running?

**Comment by dibble9012** [comment]
I have tried restarting homebridge. It does have three different plugins installed (but they have never caused issues in the past).

I do not have this issue in the 2018 version of the plugin. Also did not have this issue before I updated to the two most current versions of the 4 plugin. The version before the one that I posted my last issue with worked fine.

**Comment by dibble9012** [comment]
Also if I close and open the app, it’s good for a few seconds then everything blanks out and goes unresponsive. I’d post a video but I don’t think you can on here.

**Comment by jvmahon** [comment]
See questions in prior post. IAlso, please post your config.json file (you'll need to zip it first) - I need to see what devices you are using so I can try and trace the problem. Do the devices work up until the point where they freeze?  

Also, there was a recent update to hap-nodejs. I'm not sure if that is affecting anything, but just in case, can you un-install homebridge and your plugins and re-install them. 

To see which plugins you have installed, use:
`````
npm -g list --depth=0
`````

To un-install, use:
`````
npm -g uninstall homebridge homebridge-homeseer 4  <and any others>
`````

Then re-install using:
`````
npm -g install homebridge homebridge-homeseer4  <and any others>
`````

**Comment by jvmahon** [comment]
Found a bug that was causing problems with sensors.
Please update to 0.0.40 and try again. Let me know if its working now.
Thanks for your help finding these bugs!

**Comment by dibble9012** [comment]
That update seems to have fixed it, I’ll give it a day just to make sure. Thanks for creating this plugin and the fast response to bugs! This is our main way of controlling our home from our devices (HomeSeer runs automations and scheduling, anything manual is from IOS devices).

**Comment by jvmahon** [comment]
You're welcome. I think (hope) that most of the bugs are now out of the code!.

**Comment by jvmahon** [comment]
I've closed this issue - but re-open if you have continuing problems.
