### ISSUE TITLE
Can Sonos devices be added to config?

### ISSUE THREAD

**Issue by ando01** [jvmahon/Homebridge-HomeSeer4#43]
Not an issue, but I am just wondering if it possible to expose the Sonos players in Homeseer to this plugin. I have tried a couple of the homebridge plugins for sonos but the don't seem to work well.

**Comment by jvmahon** [comment]
Sorry, but I'm not sure how I would do that.  I thought Sonos had built-in support for HomeKit (you might need to update to recent firmware- have you looked into that?).

**Comment by ando01** [comment]
Thanks for the reply. I have the older Play 1s that don’t support HK. I was also able to get one of the homebridge Sonos plug-ins to work so all is good!
