### ISSUE TITLE
OmniPro devices no longer dim

### ISSUE THREAD

**Issue by Bi7** [jvmahon/Homebridge-HomeSeer4#47]
I am having trouble with my Omni dimmer switches. When I first setup HomeSeer4 they were dimming but soon thereafter (next day) the dimming stopped. I don't think this from a version bump to handle the 401 error, but maybe. Oddly enough as you can see below, I send the value through the HomeKit app to dim but immediately a 2nd  command tells the switch to go to 255. I am not doing that. My devices are setup as dimmable in HS3, This is happening with both the simple part of config.json and the complex, as I used the complex section for a couple of my switches to address the problem. I tried both 99 and 255 as "levels".
I see there was a similar issue but saw nothing in the thread to address this.
Output from Homebridge:

Sending new value to HomeSeer on ASCII Port, HomeSeer device: '130', sent value: '9'
Sending new value to HomeSeer on ASCII Port, HomeSeer device: '130', sent value: '255'
[2/4/2020, 4:18:30 PM] [HomeSeer] Received HomeSeer status update data for HomeSeer device: '130', new value: '9,' old value: '0'
[2/4/2020, 4:18:30 PM] [HomeSeer] Received HomeSeer status update data for HomeSeer device: '130', new value: '255,' old value: '9'

**Comment by Bi7** [comment]
Here is my config.json
[config.json.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4156920/config.json.zip)

**Comment by jvmahon** [comment]
First,  update plugin to latest version 0.0.43 which fixed some problems with dimming lights. 
Use the following command to update:

`````
npm -g install homebridge-homeseer4
`````

Then, remove the "onValue", "levels", and "offValue" parameters and let the plugin figure these out.

If that doesn't work,, try to configure them by simply putting their reference numbers in the "Lightbulbs" array and see if that gets them to work properly. IF they are configured using the "Lightbulbs" array the plugin will (should) figure out whether they are dimming lights or not.

If neither of these work, can you post a screen shot of the "Status Graphics" page for the lights?

**Comment by Bi7** [comment]
Success!
I removed the values mentioned and tested after the update to 0.0.43. Both the simple and complex listed devices dimmed as they should. Finished up by converting the complex versions to simple.
All working--Thanks!
