### ISSUE TITLE
Homeseer thermostat setup

### ISSUE THREAD

**Issue by mgeorgeHome99** [jvmahon/Homebridge-HomeSeer4#51]
Hi Guys, I have tried to troubleshoot my OMNI Thermostats in Homeseer-Homnebridge, I think I hit the extent of my skills. I am on Linux,

npm -g list --depth=0,

├── homebridge@0.4.50
├── homebridge-config-ui-x@4.10.0
├── homebridge-homeseer4@0.0.43
└── npm@6.13.4

node -v,
v12.15.0

config.json, I have tried ref the Root device and the 

  "accessories": [
                {
                    "type": "Lock",
                    "ref": 76
                },
                {
                    "type": "Thermostat",
                    "name": "Main Floor Root Device",
                    "ref": 55,
                    "heatingSetpointRef": 19,
                    "coolingSetpointRef": 25,
                    "controlRef": 58,
                    "stateRef": 62
                }

crash report information,

[37m[2/12/2020, 8:32:13 PM][39m [36m[HomeSeer][39m Initializing platform accessory 'Main Floor Root Device'...
[37m[2/12/2020, 8:32:13 PM][39m [36m[HomeSeer][39m Setting up a Thermostat with configuration values: {"type":"Thermostat","name":"Main Floor Root Device","ref":55,"heatingSetpointRef":19,"coolingSetpointRef":25,"controlRef":58,"stateRef":62,"interface_name":"Unknown","uuid_base":"Ref55","model":"OMNI Thermostats"}
(node:10534) UnhandledPromiseRejectionWarning: RangeError: Error setting up Thermostat. Scale is not Celsius or Fahrenheit
    at Object.exports.setupThermostat (/usr/lib/node_modules/homebridge-homeseer4/lib/ThermostatSetup.js:230:12)
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:150:16)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:223:11)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:413:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:187:5)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:10534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

** The lights, locks and other functionality I have working fine, I think its something probably simple.  I tried simplistic to the Ref of the Root device but got the following error.

[37m[2/12/2020, 8:38:24 PM][39m [36m[HomeSeer][39m Initializing platform accessory 'Main Floor Main Floor Root Device'...
[37m[2/12/2020, 8:38:24 PM][39m [36m[HomeSeer][39m *Warning* - Found a Temperature device of Type 2, Subtype:0 but device is not using the 'Nest' thermostat plugin. Setting of 'ref' value may be incorrect. You may need to use the 'complex' configuration procedure. Please report this as an issue on github so a correction can be made. Also see wiki entry on Thermostats for additional information. Interface name is: undefined
[37m[2/12/2020, 8:38:24 PM][39m [36m[HomeSeer][39m Setting up a Thermostat with configuration values: {"ref":55,"heatingSetpointRef":56,"coolingSetpointRef":57,"controlRef":58,"stateRef":62}
(node:12219) UnhandledPromiseRejectionWarning: RangeError: Error setting up Thermostat. Scale is not Celsius or Fahrenheit
    at Object.exports.setupThermostat (/usr/lib/node_modules/homebridge-homeseer4/lib/ThermostatSetup.js:230:12)
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:156:16)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:223:11)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:413:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:187:5)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:12219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I really appreciate any help!

**Comment by jvmahon** [comment]
No problem. Thermostats are tricky to set up. As a starting point, there is a wiki entry on thermostats which you should review. See: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Thermostats

If that doesn't help you solve your problem, please post a screen shot of the group of devices for your thermostat so that I can check your configuration setting.  
Thanks.

**Comment by jvmahon** [comment]
Also, please clarify - which plugin are you using for this?

**Comment by jvmahon** [comment]
Finally, can you execute the following two commands on your HomeSeer computer and paste the results in a comment here (you can also execute them remotely by substituting your HomeSeer computer's IP address for 127.0.0.1) and replace the 1234 with the homeSeer reference number for your thermostat's root device.

http://127.0.0.1/JSON?request=getcontrol&ref=1234

http://127.0.0.1/JSON?request=getstatus&ref=1234

**Comment by mgeorgeHome99** [comment]
Wow thanks for the response, HomeSeer etc is an amazing community,  I will check for contribution links to help out. It could very well just be the OMNI plugin, but see below your requests:

Plugin-
Homeseer OMNI Plugin 3.02.17
Homebridge homebridge-homeseer4 v0.0.43


http://127.0.0.1/JSON?request=getcontrol&ref=1234

{"Name":"HomeSeer Devices","Version":"1.0","Devices":[]}

http://127.0.0.1/JSON?request=getstatus&ref=1234
{"Name":"HomeSeer Devices","Version":"1.0","Devices":[{"ref":54,"name":"Main Floor Root Device","location":"Main Floor","location2":"OMNI","value":0,"status":"Not Set","device_type_string":"OMNI","last_change":"\/Date(1537556746979)\/","relationship":2,"hide_from_view":false,"associated_devices":[55,56,57,58,59,60,61,62,63,64],"device_type":{"Device_API":16,"Device_API_Description":"Thermostat API","Device_Type":99,"Device_Type_Description":"Thermostat Root Device","Device_SubType":0,"Device_SubType_Description":"Main Floor"},"device_image":"","UserNote":"This device was built by the OMNI Plugin.","UserAccess":"Any","status_image":"images/HAI/alarmPlain_64.png","voice_command":"","misc":4624}]}


Settings

[cid:image001.jpg@01D5E26E.EF7BDE10]
[cid:image006.jpg@01D5E26E.EF7BDE10]

[cid:image007.jpg@01D5E26E.EF7BDE10]

Thanks again for the help, I had invested a night to the Wiki and my wife started looking at me incredulously so I thought I better seek some help…




[cid:Steelhauslogoside250px_29457f03-0298-44d6-8313-e551ea92e7b3.png]


Mike George
President & CEO, BCOMM, MBA



o: 587.779.4502 ext 10 | c: 403.200.3732


www.steelhausinc.com


[cid:sig_203410ed-a1d6-4fc0-aacb-c1ffa6fe8159.png]

**Comment by jvmahon** [comment]
It looks like you tried to paste the images I requested, but they didn't paste. Try again or email them to me at jvm33@columbia.edu.

**Comment by mgeorgeHome99** [comment]
Thanks, sent.


[cid:Steelhauslogoside250px_29457f03-0298-44d6-8313-e551ea92e7b3.png]


Mike George
President & CEO, BCOMM, MBA



o: 587.779.4502 ext 10 | c: 403.200.3732


www.steelhausinc.com


[cid:sig_203410ed-a1d6-4fc0-aacb-c1ffa6fe8159.png]

**Comment by jvmahon** [comment]
It looks like you simply misread the reference numbers of the heating and cooling setpoint devices - it seems you might have put in the temperature values rather than the reference numbers (?).

Try using the following for your thermostat setup and let me know if it works:

{
"type": "Thermostat",
"name": "Main Floor Root Device",
"ref": 55,
"heatingSetpointRef": 56,
"coolingSetpointRef": 57,
"controlRef": 58,
"stateRef": 62
}
