### ISSUE TITLE
Maybe a good easy option for linux user : Docker

### ISSUE THREAD

**Issue by MattL0** [jvmahon/Homebridge-HomeSeer4#53]
Maybe a good option for linux user would be to install homebridge in docker ?

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Docker

So maybe you can add this option in  your how to

**Comment by MattL0** [comment]
Allowing the user to setup your plugin via this web interface might be a nice add  too :

https://github.com/oznu/homebridge-config-ui-x

**Comment by jvmahon** [comment]
Thanks. I appreciate the suggestions and  I've added these as references / recommendations on the "Home" Wiki page in Section 1. See https://github.com/jvmahon/Homebridge-HomeSeer4/wiki
