### ISSUE TITLE
Request: option to remove room from device name when using simple config.json

### ISSUE THREAD

**Issue by goldriver2** [jvmahon/Homebridge-HomeSeer4#54]
With the new config.json, it is very interesting to go the easy way and giving only the light device id BUT this creates the devices in Homekit with 'room - Device name'

As this implies that you ask siri 'Open room device name', it is not very user friendly, at least in my situation, is there a way to add a parameter in the config,json giving the option that devices created are only created with the "Device Name:" OR even better with the "Voice Command"

thanks for this

**Comment by jvmahon** [comment]
I do want to keep the room name as it helps to identify devices when you have many similarly named devices.

But you can still achieve what you are after in one of two ways:

1. Simply rename the device in iOS.  The room name assigned by HomeKit and the plugin is used only when the device is first added. If you change the name using iOS, the changed name will be used every time after that. If you are not familiar with how to change the name, see: https://support.apple.com/en-us/HT204893

2. If the iOS room name is the same as your HomeSeer room name, then iOS should display the device name part only - that is, it should "hide" the room name part.

**Comment by goldriver2** [comment]
Ok then what about an option wher a user could select to use "voice command". This is what is done for the Alexa and Google integration, that way a user could choose how to create his devices ?

**Comment by jvmahon** [comment]
I'm not sure what you mean -- if you're talking about Siri voice commands, that isn't determined by the plugin. That's a function of the Home application and Siri on your phone. All you should need to do is put the device in the proper "room" on your ios Home app and rename it to the name you want to use using the iOS Home app.

**Comment by goldriver2** [comment]
I'll try to explain better, sorry english is not my primary language so please bare with me..
To simplify the process of adding devices to Homekit in my iphone and to eliminate the need to go in the homekit app and rename all devices or moved them to specific room, my wish would be that the homebridge-homeseer4 plugin creates the homekit the same way the Google and Alexa - Homeseer Interface do: They create their devices without any room or floor relations, they create their devices based on Homeseer "Voice Command:" field.

The "Voice Command:" field in Homeseer is like a second device name wich sole intent is to direct any "voice interface" to a specific device.

What I would like if possible would be a general parameter in the config.json file wich, if set to yes, would only push the "Voice Command:" field information to Homekit as the devive name and that all "room" in homekit are set to "Default"

If one would prefer to transfer the "room" and the "Device Name" to Homekit he would set that general parameter to NO

Hope it is more clear this time, sorry again
![homekit](https://user-images.githubusercontent.com/7215561/75397095-0b9e9d00-58c4-11ea-85a5-864ff59ab6c0.JPG)

**Comment by jvmahon** [comment]
Its an interesting idea, but I just don't have the time to do this right now. Maybe something for me to consider in the future. One complexity is that not all devices have "Voice Commands" associated with them, so there would still have to be a "default" used which would probably just be the room name + device name, which is what I already do.
