### ISSUE TITLE
HOOBS docker on Unraid - Node version and Homeseer Plugin

### ISSUE THREAD

**Issue by rmohsenn** [jvmahon/Homebridge-HomeSeer4#55]
installed HOOBS on unraid using the docker , everything is working except the homeseer plugin needs node js version above 12 , and i'm stuck trying to upgrade it 

```
Unexpected token =
Unable to determine plugin type for "homebridge-homeseer4"

```
`Plugin /hoobs/node_modules/homebridge-homeseer4 requires Node version of >=12.0.0 which does not satisfy the current Node version of v10.18.0. You may need to upgrade your installation of Node.`

**Comment by jvmahon** [comment]
Have you tried searching on www.nodejs.org  for the proper download and instructions? I think that would be the place to start.

**Comment by rmohsenn** [comment]
I got it resolved. Turned out the docker container itself must be rebuilt with the proper node js version. Hoobs guys just updated it and it’s working now
