### ISSUE TITLE
Lights do not change state, even though i can turn them on and off through home bridge

### ISSUE THREAD

**Issue by kenkomaromi** [jvmahon/Homebridge-HomeSeer4#56]
+-- homebridge@0.4.52
+-- homebridge-config-ui-x@4.12.0
`-- homebridge-homeseer4@0.0.43

-- homebridge-homeseer4@0.0.4

I dont know what isnt working but I have connected the lights to my bridge. I am able to switch the lights on and off through the home app and home bridge web portal, but the lights them self do not change state. I tried running the program with debugger on. When I flip the switch it in home-bridge it does not record any logs. I have pasted the config below. It seems i am so close, yet so far. 

{
    "bridge": {
        "name": "Homebridge 3A15",
        "username": "*******",
        "port": 51018,
        "pin": "*****"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "HomeSeer",
            "name": "HomeSeer",
            "host": "http://192.168.1.50:99/",
            "ASCIIport": 11000,
            "login": "*****",
            "password": "****",
            "lightbulbs": [
                66,
                69,
                81
            ],
            "Fans": [
                67
            ],
            "GaragedDoorOpeners": [],
            "Locks": [],
            "Thermostats": [],
            "Outlets": [],
            "Switches": [],
            "Windows": [],
            "WindowCoverings": [],
            "CarbonDioxideSensors": [],
            "CarbonMonoxideSensors": [],
            "ContactSensors": [],
            "HumiditySensors": [],
            "LeakSensors": [],
            "LightSensors": [],
            "MotionSensors": [],
            "OccupancySensors": [],
            "SmokeSensors": [],
            "TemperatureSensors": []
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "blue",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ]
}

**Comment by jvmahon** [comment]
Did you not include the login / password or did you just delete them from the posting so they wouldn't show?
login / password are mandatory.

What kind of lights are they?  Are they z-wave or something else?

I strongly recommend you start with my "simple" config file as a template. Look here:

https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config

Get it working with a single light, then add additional accessories and options.

**Comment by kenkomaromi** [comment]
I just deleted them for the post. I don’t believe they are z wave switches. They are the Leviton 35A00-1 600-Watt HLC UPB Dimmer Switch, White https://www.amazon.com/dp/B000AD3XYW/ref=cm_sw_r_cp_api_i_yeSAEbFCVF2RX

**Comment by jvmahon** [comment]
I don't know much about these switches. Sorry. If they can connect to HomeSeer they should work.

**Comment by kenkomaromi** [comment]
What would the reasoning be behind nothing showing up in the debugger when I press the button? 

-Ken Komaromi

**Comment by jvmahon** [comment]
No idea.  This is very odd. Can you post a screenship of the HomeSeer "Status Graphics" page for these devices.

**Comment by kenkomaromi** [comment]
Here is the details page for one of the lights, ref 81. agh i feel like im so close to getting it to work yet so far! any help to help me get this working would be much appreciated! 


![adbf06e4a8d446aadaf3e5725dba2407](https://user-images.githubusercontent.com/62118594/76697822-31b09500-6659-11ea-88a5-f58937cfc4dc.png)
![88fd333bcbad1fdbb7bed8d4dba40d17](https://user-images.githubusercontent.com/62118594/76697824-32492b80-6659-11ea-864d-07192a7ef5c9.png)

**Comment by jvmahon** [comment]
On the "Status Graphics" page, change the "Control Use" from "On" to "On Alternate" and see if that works. If it doesn't, then try using the attached config.json. I set up your 3 lights 3 different ways, so test to see if any of them work for you.


[config.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4334196/config.zip)

**Comment by kenkomaromi** [comment]
still same issue... oddly i am able to connect my motion sensors and contact sensors perfectly fine with home-bridge, its just my lights that arent working...

**Comment by jvmahon** [comment]
Sorry, but I don't know what to do for that particular type of light.

**Comment by kenkomaromi** [comment]
Hello,

Sorry I wasnt able to get back to you back then, I gave up on the issue at the time, but Id like to give it another go if you're still able to help out. Since the last time I posted this I've tried upgrading to HS4 and even tried running homebridge on raspberry pi, both of which do not work. Im still having the same issue of the light bulbs not changing state. 

Let me know if you can still help out, Thanks!
