### ISSUE TITLE
Request - TV Support

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#58]
Hello.  Not sure if this is possible, but would be nice to be able to support a TV.  I know HomeKit supports TV, so not sure if this can be implemented.  I have "MediaController" installed in HomeSeer, and would like to be able to use standard TV controls in HomeKit with it.

Is this possible?

See screenshots on: https://9to5mac.com/2019/01/31/homekit-tv-home-app-ios-12-2/

**Comment by jvmahon** [comment]
I tried at one time to support speakers, but wasn't able to figure it out. Unfortunately, the public HomeKit specification doesn't have details on TV support. I'd like to revisit this sometime, but I currently have an overwhelming amount of pay-the-bills work to do that I won't be able to turn back to this for several months at least. There are other media control plugins on npmjs.org - maybe you can find something there.
