### ISSUE TITLE
"doorSensorRef" not a valid property for type "lock"

### ISSUE THREAD

**Issue by Hillmar** [jvmahon/Homebridge-HomeSeer4#61]
When trying to configure a door sensor for an item of type "lock" i get the following json error:

> [37m[4/17/2020, 08:57:36][39m [36m[HomeSeer][39m Checking Configuration Data
(node:7664) UnhandledPromiseRejectionWarning: SyntaxError: 
config.json error: property: doorSensorRef is not a valid property for item named: Inngangsdør of type: Lock. 
Valid Properties for this type are: type,name,ref,uuid_base,batteryRef,batteryThreshold,lockValue,unlockValue,lockedStatusValues,unlockedStatusValues,interface_name.
    at Object.hasValidProperties (C:\Users\HS3\AppData\Roaming\npm\node_modules\homebridge-homeseer4\lib\DeviceDefaults.js:624:11)
    at Object.checkConfig (C:\Users\HS3\AppData\Roaming\npm\node_modules\homebridge-homeseer4\lib\HomeSeerUtilities.js:253:18)
    at HomeSeerPlatform.accessories (C:\Users\HS3\AppData\Roaming\npm\node_modules\homebridge-homeseer4\index.js:160:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:7664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The lock is set up in the config file according to examples given in "All Configuration Parameters.js"
`                {
                    "type": "Lock",
                    "name": "Inngangsdør",
                    "ref": 529,
                    "batteryRef": 528,
                    "batteryThreshold": 30,
                    "doorSensorRef": 1300,
                    "openValue": 22,
                    "closedValue": 23
                },
`

Is there something wrong in my config file?

**Comment by jvmahon** [comment]
It was an error in the code. I've fixed it now and re-published the package. Update using:
`````
npm -g update
`````

However, specifying the doorSensorRef doesn't do anything at the moment. It will just display a message saying the door is opened or closed. In a future release, my plan is to not lock the lock mechanism if the door is indicated as being open. So, no harm specifying the reference, just don't expect anything by it for now!.

**Comment by Hillmar** [comment]
Thank you for the quick response and fix.
After updating I'm now getting a similar error, but for "openValue"

Based on the error message I'm assuming that also the parameters "closedValue", "openingValue",	"closingValue" and "stoppedValue" will throw the same error:
> Valid Properties for this type are: type,name,ref,uuid_base,batteryRef,batteryThreshold,lockValue,unlockValue,lockedStatusValues,unlockedStatusValues,interface_name,doorSensorRef.

As I'm mainly are using the Home app to display status the described functionality would be sufficient for me (indicating if the door is open or closed).

**Comment by jvmahon** [comment]
Thanks for the warning - since the doorSensorRef doesn't do anything yet, I'm guessing nobody ever tried. Fixing this properly requires some more involved code changes since the values indicating the sensor is open or closed should actually be an array.  For the moment, as those values aren't used, I suggest you just not specify them at all. I'll fix this at some point, but can't do it today.

But in case it wasn't clear, you don't need to specify any of those values. Your lock should work just by specifying the simple configuration:
`````
{ "type": "Lock", "ref": 529 }
`````

**Comment by Hillmar** [comment]
Thank you again.
I understand that you need to prioritize, and that this issue is far down the list (both for this project, and probably even lower on your "real life" list :) ).

The lock is working (locking/unlocking) perfectly as is. And for now i will just setup the DoorSensor as a separate ContactSensor.

But might i suggest to make a note in the config examples that these parameters should not be set. ? To avoid that other users run into the same issue as me where the result is that HomeBridge refuses to start up.

**Comment by jvmahon** [comment]
My plan is to fix it this weekend so there isn't  a fatal error and have the code display a warning that it isn't yet implemented. I think that's the better solution as many people just don't read the documents !

**Comment by jvmahon** [comment]
I'm re-opening this as a reminder to fix the remaining issues.

**Comment by jvmahon** [comment]
The code now recognizes a door sensor and if the door is open, it prevents locking the door from your iOS device.  The sensor values indicating that the door is locked are set by the (new) parameter:
						"doorSensorClosedValues": [0]	
This parameter is specified as an array of values. If not specified, it defaults to 0 = closed, anything else is open.

After implementing this, I realized it would be better to handle the interaction between a door sensor and the door lock directly within HomeSeer as that would give better control. For example, by setting an event where, each time the door lock is switched from unlocked to locked, you could check the sensor and see if the door should be locked. That would allow you to catch both HomeSeer as well as iOS locking errors.

But I have the code working, so I might as well leave it in now.

New version is published as 1.0.0
