### ISSUE TITLE
Cannot read property "status" of undefined

### ISSUE THREAD

**Issue by reallybman1** [jvmahon/Homebridge-HomeSeer4#63]
I'm not sure why app is throwing this error:
[4/18/2020, 23:26:58] Loaded config.json with 0 accessories and 1 platforms.
[4/18/2020, 23:26:58] ---
[4/18/2020, 23:26:58] Loaded plugin: homebridge-config-ui-x
[4/18/2020, 23:26:58] Registering platform 'homebridge-config-ui-x.config'
[4/18/2020, 23:26:58] ---
[4/18/2020, 23:26:59] Loaded plugin: homebridge-homeseer4
homebridge API version: 2.4
[4/18/2020, 23:26:59] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[4/18/2020, 23:26:59] ---
[4/18/2020, 23:26:59] Loading 1 platforms...
[4/18/2020, 23:26:59] [HomeSeer] Initializing HomeSeer platform...
[4/18/2020, 23:26:59] [HomeSeer] Start
Load homebridge-HomeSeerPlatform.HomeSeer
[4/18/2020, 23:26:59] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[4/18/2020, 23:26:59] [HomeSeer] Checking Configuration Data
(node:10772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:166:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Please post your config.json file - you may need to zip it first.

Also, please confirm which version of the plugin you are using. To find this, run
`````
npm -g list --depth=0
`````

Has the plugin ever worked for you or are you a new user trying this for the first time?
I recently did a code update so if it previously worked and broke when you updated the plugin, that would be helpful to know.

**Comment by reallybman1** [comment]
I'm a new user. I'm migrating over from Vera to Homeseer.

Here is config file:
{
    "bridge": {
        "name": "Homebridge D94D",
        "username": "0E:9D:EC:17:D9:4D",
        "port": 51337,
        "pin": "787-41-297"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "HomeSeer",
            "name": "HomeSeer",
            "host": "http://192.168.1.85:80",
            "login": "homebridge",
            "password": "homebridge",
            "Fans": [],
            "GaragedDoorOpeners": [],
            "Lightbulbs": [
                3
            ],
            "Locks": [],
            "Thermostats": [],
            "Outlets": [],
            "Switches": [],
            "Windows": [],
            "WindowCoverings": [],
            "CarbonDioxideSensors": [],
            "CarbonMonoxideSensors": [],
            "ContactSensors": [],
            "HumiditySensors": [],
            "LeakSensors": [],
            "LightSensors": [],
            "MotionSensors": [],
            "OccupancySensors": [],
            "SmokeSensors": [],
            "TemperatureSensors": [],
            "Valves": [],
            "SecuritySystems": [],
            "accessories": [
                {
                    "type": "Lock",
                    "ref": 640
                }
            ]
        }
    ]
}

**Comment by reallybman1** [comment]
/usr/lib
├── homebridge@0.4.53
├── homebridge-config-ui-x@4.15.1
├── homebridge-homeseer4@0.0.45
└── npm@6.14.4

**Comment by jvmahon** [comment]
What's odd - and maybe just a point of confusion, is you have the same lock number as I do - I think maybe you didn't realize I had put that in the sample file as an example. So, I think you need to just delete that - thus, where you have the section:
"accessories": [
{
"type": "Lock",
"ref": 640
}
]

make that just:
"accessories":[]

**Comment by jvmahon** [comment]
Also, to be clear, in your Lightbulbs section, you have:

"Lightbulbs":[3],

I assume by this you are trying to get the plugin to work with a single bulb and that single bulb has the HomeSeer device reference number of 3 - if so, you got that right.

**Comment by reallybman1** [comment]
Ok - I corrected the accessory goof and yes, the lighbulb device is correct. Just trying to get one device to work first. Still same error.

**Comment by jvmahon** [comment]
I just did a simple code change which may give some more error information - the code change also allows the code to continue after the error you're seeing.

Please update to version 0.0.6 by doing . . .
`````
npm -g install homebridge-homeseer4
`````
Also, just to be sure you are putting the correct number into the configuration file, when looking at the HomeSee web page for the device, you would insert the "Ref" number, in the case of the example below, that would be 727

![image](https://user-images.githubusercontent.com/15061942/79677575-f1e14e00-81c0-11ea-95a9-63fbda14ca87.png)

**Comment by jvmahon** [comment]
Also let me know what platform you are running HomeSeer on and HomeBridge - is it windows (which version) or Linux?

**Comment by reallybman1** [comment]
Ok - the error changed a bit. First here is my device list. I do not see the numbers like you do:
![image](https://user-images.githubusercontent.com/63933441/79677796-f3ac1100-81c2-11ea-8628-6880eedc8f50.png)

New Error:
[4/19/2020, 03:18:27] [HomeSeer] Checking Configuration Data
[4/19/2020, 03:18:27] [HomeSeer] TypeError: Cannot read property 'status' of undefined resulting in problem creating new HomeSeerAccessory. This may be the result of specifying an incorrect HomeSeer reference number in your config.json file. You specified reference 2, Check all reference numbers and be sure HomeSeer is running. Continuing to add other accessories.
[4/19/2020, 03:18:27] [HomeSeer] TypeError: Cannot read property 'status' of undefined resulting in problem creating new HomeSeerAccessory. This may be the result of specifying an incorrect HomeSeer reference number in your config.json file. You specified reference 3, Check all reference numbers and be sure HomeSeer is running. Continuing to add other accessories.
Setup Payload:
X-HM://0024RT99TI3GC
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by reallybman1** [comment]
Also - running on rRaspberry Pi

**Comment by reallybman1** [comment]
Hi - it is working now! All i has to do was reboot homeseer for the ASCII port to work. Thank you for your help.

**Comment by jvmahon** [comment]
Great. In order to see the reference numbers, follow the instructions in Sections B of these instructions:
https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file
