### ISSUE TITLE
HomeKit Security Request

### ISSUE THREAD

**Issue by mike3y** [jvmahon/Homebridge-HomeSeer4#66]
Is there any chance we could get a homekit alarm? I’m not sure if this is possible.

Basically, under homekit (home app) you tap on the device and it gives you options to arm it away/home/night. 

This is a nicer feature because if something sets off the alarm it notifies within homekit. No need for pushover, emails, or text messages.

**Comment by jvmahon** [comment]
It's already there. See: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-the-SecuritySystem-Type

**Comment by jvmahon** [comment]
Re-Open request if you have further issues with this.
