### ISSUE TITLE
Upgrading to version 1.0.0

### ISSUE THREAD

**Issue by emiliosic** [jvmahon/Homebridge-HomeSeer4#67]
Any suggestions on why upgrade is not working?

```
npm -g update homebridge-homeseer4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-homeseer4@0.0.43.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```
```
# npm -g list | grep homebridge
├─┬ homebridge@0.4.53
├─┬ homebridge-config-ui-x@4.16.0
├─┬ homebridge-homeseer4@0.0.43
```

**Comment by jvmahon** [comment]
I ran into that problem myself. I'm about to post an update on the wiki about how to fix this.  I'll let you know when it is posted - should be ready soon.

**Comment by jvmahon** [comment]
A new wiki section has been added on this. 

See: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Problems-Updating-to-Version-1.0.0

Let me know if you are able to fix the update problem.

**Comment by emiliosic** [comment]
Somehow, this time worked after upgrading from the GUI (config-ui-x):
```[Config] Running Command: sudo -E -n npm install homebridge-homeseer4@latest```
I'll try reinstalling. Thanks for the tip. nom seems a bit unstable on my Centos Linux VM

**Comment by jvmahon** [comment]
Maybe I'll add the @latest to the npm instructions. Perhaps it doesn't like going from 0.x.x to 1.x.x versions.

**Comment by emiliosic** [comment]
That could be. Didn't think of that. @latest is the default though
