### ISSUE TITLE
Thermostat adding

### ISSUE THREAD

**Issue by malosaa** [jvmahon/Homebridge-HomeSeer4#68]
Hi,

I have added the device id of the thermostat but I get an error saying, I need to enter the device id of the root of the thermostat,
so I did that and now it says the same error.

I have a plugwise anna thermostat in homeseer 4 , running the plugwise pro plugin.

regards

**Comment by malosaa** [comment]
here is the screenshot of the device in homeseer

https://prnt.sc/sc2x83

**Comment by jvmahon** [comment]
I'm not familiar with the plugwise pro plugin and didn't consider it in the code (you're the first one to mention it), so that may be why the simplified method of setting up a thermostat using just the root isn't working. There's a more detailed method specified in the wiki - can you give that a try:

https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Thermostats

**Comment by malosaa** [comment]
hi,

i did check and add it that way, it sees the thermostat temperature but cant control it
when i put it like to 23celcius nothing happens.

i don't have a state device, and don't have "controlRef": 6051, stateRef": 6050, so i used these references.

"heatingSetpointRef": 6067 doest do anything.
and "ref": 6060, shows my temperature. 

u can see the above screenshot, that are the devices that i have.
the heatingSetpointRef device in homeseer goes up every 0.5 so i can select for example 20.0 - 20.5 21.0 21.5 and so on.

i really don't know why it doesn't work

regards

**Comment by malosaa** [comment]
https://prnt.sc/sc2x83

the above screenshot shows my devices, when i open up home on my phone it shows up the thermostat with the current temperature, when i want to change it it let me change and when open back the thermostat it jumps back to the normal temperature and doesn't change it.
on homeseer it doesnt get changed.

i know the plugwise anna is supported by homebridge,but down know how to use it
https://www.npmjs.com/package/homebridge-anna

**Comment by jvmahon** [comment]
I'd suggest trying again to get the thermostat-specific homebridge-anna plugin to work.  Thermostats are particularly trick to code for and I'm afraid I can't help much when a plugin doesn't seem to correspond to the "typical" behavior unless I had a working thermostat to test with.

**Comment by malosaa** [comment]
hi thanks for the reply,
i did install the plugin aswell but sadly cant get it to work together 

 Plugin 'homebridge-anna' tried to register with an incorrect plugin identifier: 'homebridge-anna-thermostat'. Please report this to the developer!

as the developer is not active anymore, i did check the GitHub aswell.

i don't know if my thermostat control device to set the heatpoint is different from other thermostats devices in homeseer?
if i knew someone who use this plugin together with some thermostats i could compare and see what the problem is.

regards

**Comment by jvmahon** [comment]
You might be in luck on the "anna" plugin. I just checked and that developer did an update to the files about 45 minutes ago. Sounds like he/she is working on an update. Note the change date for the "index.js" file here: https://github.com/petergerdes/homebridge-anna

I suggest you will want to track that and see when they post an update to npmjs.com

**Comment by malosaa** [comment]
i did get in touch with him, now is the question how can i add that accesory ?
he does register it but dunno how i add it .

**Comment by malosaa** [comment]
if i do this the homebridge start but i cant pair at all, but status is sshowing up in the logs 

`{

	"bridge": 

	{

		"name": "Test-Homebridge",

		"username": "CD:22:3D:E3:CE:31",

		"port": 51826,

		"pin": "032-45-155"

	},
	"accessories": [
           {
               "accessory": "Thermostat",
               "name": "Thermostaat",
               "ip": "192.168.1.XXX
               "password": "XXXXX
               "maxTemp": "26",
               "minTemp": "15",
               "interval": "3000"
           }
       ],


	"description": "This is an test configuration file.",
	


	"platforms": 

	[

	     {

			"platform": "HomeSeer",              

			"name": "HomeSeer",                 

			"host": "http://192.168.1.XXX:XX

			"ASCIIport":11000,

			"login":"telnet",

			"password":"XXXXX



			"events":

			[                           

				{ 

					"name":"Smoke mode",	

					"eventGroup":"ventilation system",	

					"eventName":"Smoke mode",	

					"uuid_base":"smoke mode" 

				},

				{ 

					"name":"Night Mode",		

					"eventGroup":"Home RGB",	

					"eventName":"Wholehouse Night",	

					"offEventGroup":"Home RGB", 

					"offEventName":"Wholehouse normal", 	

					"uuid_base":"1234593" 

				}																

			],

		     

			

			

			"GaragedDoorOpeners": 	[],

			"Lightbulbs": 	[4043,53,933,4022,4233,4222,4225,4026],
			"Windows": 	[4293,4288,4291,4292,4287],
			"ContactSensors": 	[4290,4289],
			"Thermostats": 	[],
			"HumiditySensors": 	[241,976,127,5685,5676],


		
			

		"accessories": 

		[
			{"type": "Fan",
						"name":null,
						"ref": 4036,
						"uuid_base": 0,
						"onValue": 99,
						"offValue": 0}
						



						
		]



    }

  ]

}`

**Comment by jvmahon** [comment]
I know you aren't running HomeBridge on Windows, but see section I.F of this wiki entry: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Windows-10-Installation

Homebridge / iOS may think you are already paired, so you have to delete the homebridge persist & accessories folders and then try to pair again.

**Comment by malosaa** [comment]
Hi jvahon,

yes i am running on windows 10, i did delete the persist and accessory folder
the strange thing is if i delete this part below, it actually pairs.
i did not test with another plugin, but it wont let me use accessories outside the platfirms

```
"accessories": [
       {
           "accessory": "Thermostat",
           "name": "Thermostaat",
           "ip": "192.168.1.XXX
           "password": "XXXXX
           "maxTemp": "26",
           "minTemp": "15",
           "interval": "3000"
       }
   ],
```

**Comment by malosaa** [comment]
i think its an issue with the developer's plugin 
because i can pair normally without his plugin added
so i did ask him, but he said he doesnt use it anymore so its not supported sadly.

but anyway thank you for your help anyway and for the good support
many thanks keeping this updated

regards and have a nice day

**Comment by malosaa** [comment]
I fixed it, its working together

I deleted 2 lines of the other plugin and it works now :)

**Comment by jvmahon** [comment]
Glad you solve it. Best regards,
Jim
