### ISSUE TITLE
Question on Accessories

### ISSUE THREAD

**Issue by XiozTzu** [jvmahon/Homebridge-HomeSeer4#71]
Homebridge now forces you to add an accessory ("accessory":) tag into your accessory config.  Does homeseer expect a certain string for an accessory type or is the just anything you want to put in?

I used the following but homeseer does not implement the accessory...
            "accessory": "Virtual Home Security",
            "type": "SecuritySystem",
            "ref": 123

**Comment by jvmahon** [comment]
I think you are misunderstanding the config.json file.

In Homebridge, you can add devices using either "platforms" or the "accessories" group.

If the devices are being added using the "platforms" feature, then the "platform" defines how it wants to use the rest of it's platform section in the config.json.

In that case, the platform itself can have its own "accessories" section and the platform writer determines how that is used.

In the case of the homebridge-homeseer4 plugin, its "platform" section has its own "accessories" section. Though the name is still "accessories", have to look at this as different from the separate "homebridge" accessories section.  Thus, the "accessories" section for the homeseer plugin did not change -- it still corresponds to the description in the Wiki and in the sample config.json files.

Thus, don't add "accessory":"Virtual Home Security" as you've done (though you could add it as "name":"Virtual Home Security".

**Comment by XiozTzu** [comment]
I did not realize that you could have a nested Accessories sections.  I did what you said and now it works.  Thank you!
