### ISSUE TITLE
Question on Dimmable Switches

### ISSUE THREAD

**Issue by XiozTzu** [jvmahon/Homebridge-HomeSeer4#72]
How do you configure a dimmable switch?  I can get the switch to come up as a binary switch in HomeKit but would like the slider.  Can you point me in the right direction?

**Comment by jvmahon** [comment]
There are several ways.

If you look in the "config" folder, here: https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config

There are example config.json files. Look at the file config.simple.json,  you'll notice there are a bunch of array definitions followed by an empty set of brackets, e.g., "Lightbulbs": []

All you need to do is fill the brackets with the HomeSeer reference number of each light, so if your lights were numbered 20, 228, 1037 you would have an entry like:

`````
"Lightbulbs": [20, 228, 1037],
`````

The code *should* detect whether the light is a Binary type or a dimmable light and configure it accordingly. The type detection works best with Z-wave lights, but should work for other types. This way of configuring the lights is shown in more detail here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

There is also the more "complex" setup method, as shown in the file config. complex.json where you configure each light separately in the "accessories" section of the file using a more fully defined description of the light. This might be useful for lights other than Z-Wave or where you need to customize other values. Generally, you don't need to set all of the values - but "type" and "ref" are always required. IF you use the type "Lightbulb", the code tries to figure out if it is a dimmable or a binary light. While if you use "DimmingLight" or "BinaryLight" you always get the type you specified

So if I wanted to override the automatic checking and set device 23 to be a Dimmable Light and device 237 to be a Binary light, you could use

`````
{"type":"DimmingLight", "ref":23 },
{"type":"BinaryLight", "ref":237 },
`````

You should review this entire file: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file


`````
					{
						"type": "Lightbulb",
						"name":null,
						"ref": 0,
						"uuid_base": 0,
						"batteryRef": 0,
						"batteryThreshold": 25,
						"onValue": 255,
						"offValue": 0
					},
					{
						"type": "DimmingLight",
						"name":null,
						"ref": 0,
						"uuid_base": 0,
						"batteryRef": 0,
						"batteryThreshold": 25,
						"onValue": 255,
						"levels":99,
						"offValue": 0
					},
					{
						"type": "LightSwitch",
						"name":null,
						"ref": 0,
						"uuid_base": 0,
						"batteryRef": 0,
						"batteryThreshold": 25,
						"onValue": 255,
						"offValue": 0
					},
					{
						"type": "BinaryLight",
						"name":null,
						"ref": 0,
						"uuid_base": 0,
						"batteryRef": 0,
						"batteryThreshold": 25,
						"onValue": 255,
						"offValue": 0
					},
`````

**Comment by XiozTzu** [comment]
Will this work for a dimmable switch?  I tried to set is as a bulb before and did not work.

Switch, such as... https://www.amazon.com/gp/product/B07B3LXZJ9/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1

**Comment by jvmahon** [comment]
Yes. That is what it is intended to work with. When you set up taht Switch in HomeSeer, it will probably create three devices (i) a Root device; (ii) a Central Scene device; and (iii) the dimmer control as shown in the example, below. You should use the reference number for the dimmer control -- in the example shown, that would be 210.

![image](https://user-images.githubusercontent.com/15061942/81518876-6ebd9e80-930d-11ea-8b34-9ce1069d2d78.png)

**Comment by XiozTzu** [comment]
Ok, that worked!  Calling a Switch a Light is what threw me off.  

Thanks for walking me through this stuff.   Now on to the DSC security system.

**Comment by jvmahon** [comment]
O.K., good.
Regarding calling a switch a Light - HomeKit and Siri generally want to "know" whether a switch is controlling a light, fan, or something else. Usually dimmer switches control light bulbs or else fans. So a dimmer can be configured as one of those. That way, when you say "Turn off all lights", homekit can tell if a particular dimmer is for a light bulb or a fan (those are the only "dimmable" choices). It's similar for Binary switches, but there you also get the more generic "Switch" which is used if it isn't a light or a fan.
