### ISSUE TITLE
Question Thermostat Fan State and Mode

### ISSUE THREAD

**Issue by XiozTzu** [jvmahon/Homebridge-HomeSeer4#74]
How should a HVAC's fan state and mode (auto, on, circulation) be controlled?  The thermostat accessory does not seem to handle this use case.  I see that there is a fan accessory, is that the way to control a HVAC fan?  If so, how?

**Comment by jvmahon** [comment]
The plugin is not set up to support fan control, so that is set using your physical thermostat.
