### ISSUE TITLE
Error on Homebridge start (v1.1.0)

### ISSUE THREAD

**Issue by woodgieboodgie** [jvmahon/Homebridge-HomeSeer4#76]
Recent update of Homebridge to v1.1.0 produces the following:

 _The plugin "homebridge-homeseer4" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!_

**Comment by darrenmcuk** [comment]
Yes got the same here as well

**Comment by jvmahon** [comment]
I plan to fix that soon - maybe today or tomorrow.

**Comment by darrenmcuk** [comment]
thanks

**Comment by jvmahon** [comment]
Try updating to 1.0.1 and let me know if its working for you now.

**Comment by woodgieboodgie** [comment]
error appears to have disappeared.  well done.
