### ISSUE TITLE
New strange error with 1.0.1 build

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/Homebridge-HomeSeer4#77]
Not too sure what I am doing wrong...but...

[37m[5/19/2020, 8:28:04 AM] Successfully authorized Telnet port
(node:2535) Warning: Accessing non-existent property 'Characteristic' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2535) Warning: Accessing non-existent property 'Service' of module exports inside circular dependency

**Comment by jvmahon** [comment]
Is this with Node 14?
This posting suggest there is a bug in node: https://github.com/electrode-io/electrode-native/issues/1558 

Do you know how to use the --trace-warnings function that is mentioned in the warning? I'm not sure how to activate it in homebridge

**Comment by darrenmcuk** [comment]
Yes this is with Node 14

**Comment by jvmahon** [comment]
Thanks. Given that the plugin seems to work fine, I'm going to wait this one out and see if the error gets fixed in node 14.3 or so.

**Comment by jvmahon** [comment]
Node 14.3 was released today, but it doesn't seem to fix this warning.

**Comment by jvmahon** [comment]
I re-installed node 12.16.3 and the warning does not happen on that node version, so this appears to be a node issue; thus, I'm closing this issue as it doesn't seem to be a plugin problem. I'll re-open if I find out differently in the future.
