### ISSUE TITLE
Issue setting up homeseer Air Conditioner (Zwave) 

### ISSUE THREAD

**Issue by homeconnector** [jvmahon/Homebridge-HomeSeer4#80]
** ZWAVE Temperature is unknown ** 
 | 822 | unknown |   | unknown  | Ground | Family | Temperature | E20F3165-009-Q73 | Z-Wave Sensor Multilevel | Today 9:29:54 AM
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | unknown

** After Refresh of ZWAVE - Temperature is corrected **
  | 822 | 17 C |   | 17 C | Ground | Family | Temperature | E20F3165-009-Q73 | Z-Wave Sensor Multilevel | Today 9:29:54 AM
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 17 C

Issue occurred upon a reboot of the Homebridge.   For some reason the Z-wave was not reporting thermostat status.   After triggering the device, it found it (via homeseer) and corrected the temperature.   I guess the previous plugin - accepted the temperature Unit = F or C.     Are you able to amend the complex setup to bypass the checking for F / C?

** ERROR MESSAGE **
6|connectmgr2  | [6/9/2020, 9:29:35 AM] [Homeseer] Setting up a Thermostat with configuration values: {"type":"Thermostat","ref":822,"name":"Ground Family Air Conditioner","heatingSetpointRef":825,"coolingSetpointRef":826,"controlRef":824,"stateRef":824,"interface_name":"Z-Wave","uuid_base":"Ref822","batteryRef":821,"batteryThreshold":25,"model":"Z-Wave Sensor Multilevel"}
6|connectmgr2  | (node:15532) UnhandledPromiseRejectionWarning: RangeError: Error setting up Thermostat. Scale is not Celsius or Fahrenheit
6|connectmgr2  |     at Object.exports.setupThermostat (/usr/local/lib/node_modules/homebridge-homeseer4/lib/ThermostatSetup.js:231:12)
6|connectmgr2  |     at Object.exports.setupServices (/usr/local/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:150:16)
6|connectmgr2  |     at HomeSeerAccessory.getServices (/usr/local/lib/node_modules/homebridge-homeseer4/index.js:218:11)
6|connectmgr2  |     at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:441:41)
6|connectmgr2  |     at /usr/local/lib/node_modules/homebridge/src/server.ts:426:34
6|connectmgr2  |     at Array.forEach (<anonymous>)
6|connectmgr2  |     at /usr/local/lib/node_modules/homebridge/src/server.ts:416:21
6|connectmgr2  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
6|connectmgr2  |     at HomeSeerPlatform.accessories (/usr/local/lib/node_modules/homebridge-homeseer4/index.js:182:5)
6|connectmgr2  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
6|connectmgr2  | (node:15532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
6|connectmgr2  | (node:15532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
6

**Comment by jvmahon** [comment]
See this thread and how to fix whether your device displays the "F" or "C". Let me know if it works.
https://github.com/jvmahon/Homebridge-HomeSeer4/issues/79

**Comment by jvmahon** [comment]
Update published.
You can now use the "temperatureUnit":"F" or "temperatureUnit":"C" parameters to set a temperature unit if the default detection algorithm doesn't work.
Let me know if this works for you.

**Comment by homeconnector** [comment]
Confirmed this works, and is fixed too
thanks
