### ISSUE TITLE
Garage Door Opener Question

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#81]
I have a garage door opener setup per your directions in example...

					{
						"type": "GarageDoorOpener",
						"name":null,
						"ref": 0,			
						"uuid_base": 0,
						"batteryRef": 0,
						"batteryThreshold": 25,
						"obstructionRef": 0,
						"obstructionClearValues":[0,74],
						"openValue": 255,
						"closedValue": 0,
						"openingValue": 254,
						"closingValue": 252,
						"stoppedValue": 253
					},

My question is, when in the "Closed" position (Value: 0), and I hit the button on my iPhone, it tries to switch it to "Open" (Value: 255).   Is this normal?  Why wouldn't it switch it to "Opening" (Value: 254) and then once the garage is fully opened, it would switch to "Open" (Value: 255)?

**Comment by jvmahon** [comment]
When in the closed position,  the iPhone will send the Open command.
At HomeSeer, one of two things happen, depending on your garage door control plugin:

1. Some plugins transition immediately from closed / open and don't show the intermediate "opening" state. If that's what your plugin does, then the iPhone will report "Open".
2. Other plugins do transition states. For those plugins, when they are sent "Open", they respond with "Opening" (254) and the iPhone will show an opening graphic. When the door reaches the fully opened state, HomeSeer will then report "Open" to the iphone.

You can tell if your plugin supports the intermediate states by looking at the "Status Graphics" page for the device. So, for example, looking at the Status Graphics page for my device (posted below) I set it up using:
`````
{	"type": "GarageDoorOpener",
	"ref": 123,			
	"openValue": 1,
	"closedValue": 2,
	"openingValue": 4,
	"closingValue": 5,
	"stoppedValue": 3
},
`````

![image](https://user-images.githubusercontent.com/15061942/85201885-a76b7300-b2d0-11ea-8e21-285bf5061f51.png)

**Comment by meluvalli** [comment]
Got it!  Ok.   Just seemed odd, but makes sense!
