### ISSUE TITLE
Garage Door - Battery - UnhandledPromiseRegection...

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#82]
Garage Door Opener Per config example should support batteryRef & batteryThreshold parameters.  However, HomeBridge won't load with these values set.

<pre>
(node:12824) UnhandledPromiseRejectionWarning: SyntaxError:
config.json error: property: batteryRef is not a valid property for item named: GarageOpener of type: GarageDoorOpener.
Valid Properties for this type are: type,name,ref,uuid_base,obstructionRef,obstructionClearValues,openValue,closedValue,openingValue,closingValue,stoppedValue,interface_name.
    at Object.hasValidProperties (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\DeviceDefaults.js:626:11)
    at Object.checkConfig (C:\HomeBridge\node_modules\homebridge-homeseer4\lib\HomeSeerUtilities.js:256:18)
    at HomeSeerPlatform.accessories (C:\HomeBridge\node_modules\homebridge-homeseer4\index.js:160:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
</pre>

Snip from Config:
<pre>
                {
                    "type": "GarageDoorOpener",
                    "name": "GarageOpener",
                    "ref": 576,
                    "batteryRef": 572,
                    "batteryThreshold": 25,
                    "openValue": 255,
                    "closedValue": 0,
                    "openingValue": 254,
                    "closingValue": 252,
                    "stoppedValue": 253
                },
</pre>

**Comment by jvmahon** [comment]
I must have never implemented that parameter. It doesn't really make sense for a Garage Door and I don't think HomeKit would support it. Assume that will be deleted in an update to the code, so I suggest you remove it from your config.json

**Comment by jvmahon** [comment]
Same for "batteryThreshold"

**Comment by meluvalli** [comment]
If using a garage door sensor, they require batteries.   So, would be nice
to implement it unless like you said HomeKit doesn’t support it...  Example
would be the TILT-ZWAVE2.5-ECO.

**Comment by meluvalli** [comment]
Also note, if using one of these, would be nice to somehow (not sure if possible) to have the "Open/Close" function use a different reference.  This way, when you click the garage to turn it "on", it would toggle a switch for the opener, but use the sensor for the "opening, closing, stopped" functions.  Maybe I'm thinking to much?

**Comment by jvmahon** [comment]
I've done a patch for the battery issue which I'll roll out at the end of the weekend (I have one more issue I may try to address first). The prior suggestion is something I can't do right now - that being said, its possible to do what you are suggestiong using a "virtual" device to act as a garage door opener and a bunch of events to change states. I started outlining how this might be done here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Garage-Door-Openers

**Comment by jvmahon** [comment]
Also, if you have a MyQ / LiftMaster door opener, this free plugin does the trick:  https://github.com/DoctorMcKay/HSPI_LiftMasterMyQ

**Comment by meluvalli** [comment]
> I've done a patch for the battery issue which I'll roll out at the end of the weekend (I have one more issue I may try to address first). The prior suggestion is something I can't do right now - that being said, its possible to do what you are suggestiong using a "virtual" device to act as a garage door opener and a bunch of events to change states. I started outlining how this might be done here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Garage-Door-Openers

Understood!  Thank you for patching the battery issue!  I'll be using it, so much appreciated! I'll keep an eye out for the update!

**Comment by jvmahon** [comment]
Update published. Now recognizes the battery parameters ("batteryRef" and "batteryThreshold"). Let me know if it works for you.

**Comment by meluvalli** [comment]
THANK YOU so much for doing this so quickly!  I’m happy to report it is working great!  

Thanks again!
