### ISSUE TITLE
Fibaro RGBW Controller 2 Question

### ISSUE THREAD

**Issue by Silas888** [jvmahon/Homebridge-HomeSeer4#88]
Hi. I have more of a question than an issue. In my HS3 setup, I have several Fibaro RGBW Controllers that operate my RGBW LED strips. I was curious if Homebridge-HomeSeer4 supports that controller? I'm aware that there is a Homebridge Fibaro Hc3 plugin but from what I can tell, that is geared towards the Fibaro Home Center 3 controller and not the specific Fibaro RGBW controller that I have.

**Comment by jvmahon** [comment]
Sorry, I have not implemented RGBW control.

**Comment by Silas888** [comment]
OK. Thank you.
