### ISSUE TITLE
New HMS4 Installation with HomeBridge 

### ISSUE THREAD

**Issue by Tesla-P100FX** [jvmahon/Homebridge-HomeSeer4#90]
I had a Homeseer 3 Installation on an older PC and intermittently could get Homebridge to work.  So i started Fresh with a HS4 on a new PC. I have the Tuya and OmniPro and Logitech plugin installed.   However i can not seem to get Homebridge to run and it never starts my devices. 

I am getting error : " **can_dim is not a valid property for item named: BackDeck of type: DimmingLight".**

I have this property on all my lights as they are dimmable and that property did work on my old installation.    I think i have the other parameters right but but attached  my config.json below  

Thank in advance for your assistance.   Stay Safe 

homebridge API version: 2.6
[7/10/2020, 2:15:02 PM] Registering platform 'homebridge-homeseer4.HomeSeer'
[7/10/2020, 2:15:02 PM] ---
[7/10/2020, 2:15:02 PM] Loading 2 platforms...
[7/10/2020, 2:15:02 PM] [HomeSeer] Initializing HomeSeer platform...
[7/10/2020, 2:15:02 PM] [HomeSeer] Start
[7/10/2020, 2:15:02 PM] [Config] Initializing config platform...
[7/10/2020, 2:15:02 PM] [Config] Running in Service Mode
[7/10/2020, 2:15:02 PM] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[7/10/2020, 2:15:02 PM] [HomeSeer] Checking Configuration Data
(node:17968) UnhandledPromiseRejectionWarning: SyntaxError: 
config.json error: property: can_dim is not a valid property for item named: BackDeck of type: DimmingLight. 
Valid Properties for this type are: type,name,ref,uuid_base,levels,interface_name,onValue,offValue.
    at Object.hasValidProperties (C:\Users\Richk\AppData\Roaming\npm\node_modules\homebridge-homeseer4\lib\DeviceDefaults.js:630:11)
    at Object.checkConfig (C:\Users\Richk\AppData\Roaming\npm\node_modules\homebridge-homeseer4\lib\HomeSeerUtilities.js:256:18)
    at HomeSeerPlatform.accessories (C:\Users\Richk\AppData\Roaming\npm\node_modules\homebridge-homeseer4\index.js:160:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[7/10/2020, 2:15:03 PM] [Config] Homebridge Config UI X v4.23.2 is listening on :: port 8581

CONFIG.JSON 
[config.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4905674/config.zip)

**Comment by Tesla-P100FX** [comment]
OK i edited my config.json and removed the can_dim from each light

[config-without can dim.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4906047/config-without.can.dim.zip)

.  It loads now but does not add the accessories.

**Comment by jvmahon** [comment]
You closed this, so I assume that means you have everything working.

Note that you generally don't need to specify the "onValue", "offValue" or  "uuid_base" values - these only need to be specified if you are trying to override defaults. 

Note that there is also a simpler way to configure all of these lights. you could have just entered them into one array like this:

"Lightbulbs":[99, 121, 110, 106, 107, 109],

See the example configuration file "config.simple.json" here: https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config    

And see the explanation here:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

**Comment by Tesla-P100FX** [comment]
I am good, still not fabulous at writing config files so sort of stumbling through it.   That config works now and i was able to set things up an the Home app on my iphone.   Next will add Tuya plug in and see if i can get those to work,  Thank you for reaching out!   I could not get it to work as the config said i had two platforms.  How exactly do you add a second platform to the same config file?

**Comment by jvmahon** [comment]
Post your config.json in which you tried to add the Tuya plugin and I'll take a look.

**Comment by jvmahon** [comment]
Also post your working "config.json" with just the homeseer configuration.

**Comment by Tesla-P100FX** [comment]
Thanks this is the error i am getting.   I get this with no devices added but with the platform configured.

[7/12/2020, 1:55:47 PM] [HomeSeer] Checking Configuration Data
(node:10376) UnhandledPromiseRejectionWarning: SyntaxError: config.json error for device of type: undefined missing mandatory 'ref' property. Specified properties are: {"platform":"TuyaWebPlatform","name":"TuyaWebPlatform","options":{"username":"xxx@outlook.com","password":"xxxxxxx","countryCode":"1","platform":"smart_life","pollingInterval":10}}
    at Object.checkConfig (C:\Users\xxxx\AppData\Roaming\npm\node_modules\homebridge-homeseer4\lib\HomeSeerUtilities.js:94:11)
    at HomeSeerPlatform.accessories (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-homeseer4\index.js:160:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This is how i have the platform configured 

{
  "platform": "TuyaWebPlatform",
  "name": "TuyaWebPlatform",
  "options":
    {
      "username": "xxx@outlook.com",
      "password": "xxxxxx",
      "countryCode": "1",
      "platform": "smart_life",
      "pollingInterval": 10
    },
its a valid config.json but gets the above error

i cant quite figure out how to configure that actual devices to get my four devices configured.  This is what i put in but its not valid.
"defaults": [
    { 
          "id": "03783133807d3a7d04ff",
          “id": "84170378bcddc2097c24",
	  “id": "03783133ecfabc9f3b67",
	  “id": "03783133ecfabc9f69ae"
    }
  ]
}

**Comment by jvmahon** [comment]
I believe you have placed the "Tuya" platform configuration inside of the area for the HomeSeer platform (i.e., inside the brackets that start-end the HomeSeer section).  That's why it is saying that the "HomeSeer" plugin is having problems with the data. Post your entire Config.json and I can check that.

**Comment by Tesla-P100FX** [comment]
[config with Tuya.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4914756/config.with.Tuya.zip)


OK thank you so much , here it is

**Comment by jvmahon** [comment]
It looks like you had the "Tuya" platform information in the wrong place. Also, I think you needed brackets around the "id" information.

I don't know much about "Tuya" specifically, so this is just a rough fix of the general config.json format

Here's the (hopefully) fixed file:
[config with Tuya.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4914800/config.with.Tuya.zip)

**Comment by Tesla-P100FX** [comment]
😊 thank you I’ll play with it and see if I can figure out how to add the devices.


Thanks

Rich

Sent from my Phone 📞, please excuse typos and amusing  autocorrects


On Jul 13, 2020, at 1:03 PM, jvmahon <notifications@github.com> wrote:

﻿

It looks like you had the "Tuya" platform information in the wrong place. Also, I think you needed brackets around the "id" information.

I don't know much about "Tuya" specifically, so this is just a rough fix of the general config.json format

Here's the (hopefully) fixed file:
config with Tuya.zip<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjvmahon%2FHomebridge-HomeSeer4%2Ffiles%2F4914800%2Fconfig.with.Tuya.zip&data=02%7C01%7C%7C79d4a11228f5436f29d608d82767bda1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637302673796313184&sdata=R3QTAx6aiGlZR4x4Xagu8IBCz%2BXlLu3NrbdYAFBk3SM%3D&reserved=0>

**Comment by Tesla-P100FX** [comment]
Hey you got me over the finish line.  Thank you!!!!!    Couple of minor changes and it worked!!!!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
