### ISSUE TITLE
Temperature cannot go above 212

### ISSUE THREAD

**Issue by mwolter805** [jvmahon/Homebridge-HomeSeer4#91]
Hello,
I'm noticing an issue where the reported temperature cannot go above 212f in the Home App. This particular device is reported to HS in C and converted to F by Homebridge-HomeSeer4. However, it does report temperatures below 212f. For instance, if the value reported by HS is under 100c, Home reports the proper temperature in F. 

I am using version 1.00 of Homebridge-HomeSeer4 plugin.

![Screen Shot 2020-07-14 at 9 30 23 AM](https://user-images.githubusercontent.com/24851651/87451579-e8dffd00-c5b4-11ea-9348-a37e69bb4f3f.jpg)
![Screen Shot 2020-07-14 at 9 30 05 AM](https://user-images.githubusercontent.com/24851651/87451591-eed5de00-c5b4-11ea-86ad-a24d67f8054a.jpg)

**Comment by jvmahon** [comment]
The HomeKit Maximum Current Temperature limit is 100 degrees Celsius.

From the HomeKit spec:
![image](https://user-images.githubusercontent.com/15061942/87580309-510e0c00-c6a5-11ea-9358-6ce39ec7b595.png)

**Comment by jvmahon** [comment]
I think I may be able to override this, but it would involve changing the code. Maybe I could do this next time I have to make another code change-- what temperature range do you think you need.

**Comment by mwolter805** [comment]
That would be great. Maximum temperature would be 850f.

**Comment by jvmahon** [comment]
Just curious - what are you using this for?

**Comment by mwolter805** [comment]
It’s to monitor a 3D printer’s hotend (part where the melted plastic comes out) and the heated platform where the plastic is deposited. 

-Matt

**Comment by jvmahon** [comment]
Update to 1.0.4
You can now specify a minimum and maximum value for the temprature range. Note that you must specify the min/max using Celsius degrees, even if HomeSeer reports the temperature in Fahrenheit.
`````
{"type":"TemperatureSensor", "ref":1314, "minCelsius":-100, "maxCelsius":1000, "temperatureUnit":"F"}
`````
