### ISSUE TITLE
RGB Bulbs

### ISSUE THREAD

**Issue by dmike3** [jvmahon/Homebridge-HomeSeer4#92]
Is there anyway to control RGB bulbs (colors) in HomeKit?

**Comment by jvmahon** [comment]
I assume you mean Z-Wave RGB bulbs - Not through my HomeSeer plugin.
I've thought about adding them, but it isn't trivial, and I don't have any, so I haven't.

**Comment by dmike3** [comment]
> I assume you mean Z-Wave RGB bulbs - Not through my HomeSeer plugin.
> I've thought about adding them, but it isn't trivial, and I don't have any, so I haven't.

Okay. It's not a big requirement for me, but I was curious.
