### ISSUE TITLE
Having troble with NodeJS

### ISSUE THREAD

**Issue by JCCcccspud** [jvmahon/Homebridge-HomeSeer4#93]
I am having trouble installing NodeJS. I have a Zee2 running Jesse.

When I run "sudo apt-get install -y nodejs gcc g++ make python" I get:

"Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or have moved out of incoming. The following information may help to resolve the situation.

The following packages have unmet dependencies:
nodejs : Depends: libstdc++6 (>= 5.2) but 4.9.2-10+deb8u2 is to be installed
E: Unable to correct problems, you have held broken packages."

Googling shows others have had this problem but I did not see a solution that I understood other than upgrading to Stretch or Buster (which I am afraid to do for fear of screwing up Homeseer).

Currently it shows that nodejs 0.10.29~dfag-2 is installed.

I posted this question in another Homebridge issue forum but I thought maybe you could help.

Any idea what to do.  Thanks.

**Comment by jvmahon** [comment]
Sorry, I don't know. I generally use Windows for my setup.  Have you looked at the information on www.nodejs.org?
